### ISSUE TITLE
Constraint Error

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#1638]
This should be a findable bug

https://travis-ci.org/daleharvey/pouchdb/jobs/20428276

```
    "title": "Test basic live pull replication",
    "err": {
        "message": "ConstraintError (http://127.0.0.1:8000/dist/pouchdb-nightly.js:2295)",
        "stackTrace": [
            {
                "fileName": "http://127.0.0.1:8000/node_modules/mocha/mocha.js",
                "lineNumber": 5708,
                "methodName": "process.on/global.onerror"
            }
        ]
    }
```

Its pointing to https://github.com/daleharvey/pouchdb/blob/master/lib/adapters/idb.js#L352

A ConstraintError should mean we are managing to generate a duplicate id for something that is supposed to be unique

```
    newRevId = exports.uuid({length: 32, radix: 16}).toLowerCase();
```

is how we generate the uuid which seems like it should be unique

**Comment by russosalv** [comment]
Hi 
i tried to sync pouch with a huge CouchDB (about 0,6 GB)
and during sync i had this error
`ERROR DOMException: Failed to execute 'index' on 'IDBObjectStore': The transaction has finished.
    at IDBRequest.afterPutDocError [as __zone_symbol__ON_PROPERTYerror] (file:///android_asset/www/build/vendor.js:105780:30)
    at IDBRequest.H (file:///android_asset/www/build/polyfills.js:3:23950)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660)
    at Object.onInvokeTask (file:///android_asset/www/build/vendor.js:5126:33)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15581)
    at r.runTask (file:///android_asset/www/build/polyfills.js:3:10834)
    at e.invokeTask [as invoke] (file:///android_asset/www/build/polyfills.js:3:16794)
    at p (file:///android_asset/www/build/polyfills.js:2:27648)
    at IDBRequest.v (file:///android_asset/www/build/polyfills.js:2:27893)`

and sync will pun in PAUSE before the end of sync and future sync will not download remaining data.
