### ISSUE TITLE
Intermittent Object.parse error when conflict occurs during attachment save

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#1861]
The test for POSTing attachments against an invalid document revision (https://github.com/pouchdb/pouchdb/blob/master/tests/test.attachments.js#L317-L335) fails intermittently against Cloudant.

In the failing case, the response body is not received fully before Object.parse is called, resulting in an error:

    1) test.attachments.js-http Testing with invalid rev:
     Uncaught SyntaxError: Unexpected end of input
      at Object.parse (native)
      at Request._callback (/Users/will/dev/willholley/pouchdb/lib/deps/ajax.js:251:21)
      at Request.self.callback (/Users/will/dev/willholley/pouchdb/node_modules/request/request.js:123:22)
      at Request.EventEmitter.emit (events.js:98:17)
      at Request.<anonymous> (/Users/will/dev/willholley/pouchdb/node_modules/request/request.js:878:14)
      at Request.EventEmitter.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/Users/will/dev/willholley/pouchdb/node_modules/request/request.js:828:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickDomainCallback (node.js:459:13)

My initial thought was that this was a problem on the Cloudant end. However, I'm unable to reproduce the error with curl or nano (on nodejs).

I'm also unable to reproduce using PouchDB against local CouchDB (1.5) or IrisCouch (1.5r2). 

Blocker for #136.

**Comment by daleharvey** [comment]
Now that couch-master is tested this should be good
