### ISSUE TITLE
max listener limit hit with continuous change feed

### ISSUE THREAD

**Issue by davedoesdev** [pouchdb/pouchdb#2311]
If I do this:

``` javascript
var PouchDB = require('pouchdb');

var docs = [], i;

for (i = 0; i < 11; i += 1)
{
    docs.push({title: 'foo' + Math.random()});
}

new PouchDB('test.db', function (err, db)
{
    db.info(function (err, info)
    {
        var feed = db.changes({ since: info.update_seq, live: true });
        db.bulkDocs(docs, function (err)
        {
            feed.cancel();
        });
    });
});
```

then I get this:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at PouchDB.EventEmitter.addListener (events.js:160:15)
    at PouchDB.EventEmitter.once (events.js:185:8)
    at new Changes (/home/david/Private/hub/node_modules/pouchdb/lib/changes.js:41:6)
    at PouchDB.AbstractPouchDB.changes (/home/david/Private/hub/node_modules/pouchdb/lib/adapter.js:644:10)
    at EventEmitter.eventFunction (/home/david/Private/hub/node_modules/pouchdb/lib/utils.js:267:10)
    at EventEmitter.emit (events.js:92:17)
    at Object.api.notify (/home/david/Private/hub/node_modules/pouchdb/lib/utils.js:310:18)
    at /home/david/Private/hub/node_modules/pouchdb/lib/adapters/leveldb.js:589:28
    at Array.forEach (native)
    at complete (/home/david/Private/hub/node_modules/pouchdb/lib/adapters/leveldb.js:571:15)
```

**Comment by agozie** [comment]
Getting this on chrome  `(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.`
I'm using db change listener with `{live:true,since:'now'}`

**Comment by nolanlawson** [comment]
Yup, this is a common issue. You need to increase the number of listeners using either `db.setMaxListeners()` or `PouchDB.setMaxListeners()`.

This is like the 10th time this has come up, so I'm going to document it in the "common errors" page.
