### ISSUE TITLE
PouchConstructor is not a constructor

### ISSUE THREAD

**Issue by iivvoo** [pouchdb/pouchdb#2815]
This issue has been reported before: #2741 and #2734 
It should have been fixed in 3.0.6 but it's still occuring for me on both firefox and chrome (different error, same issue)

The relevant code is:

     exports.toPouch = toPouch;
    function toPouch(db, opts) {
      var PouchConstructor = opts.PouchConstructor;
      if (typeof db === 'string') {
        return new PouchConstructor(db);    // <- here
      } else if (db.then) {
        return db;
      } else {
        return utils.Promise.resolve(db);
      }
    }

(line 6540 in pouchdb-3.0.6.js)

The stacktrace from Chrome:

    TypeError: object is not a function
        at u (http://localhost:8000/static/js/pouchdb-3.0.6.min.js:9:12139)
        at o.c (http://localhost:8000/static/js/pouchdb-3.0.6.min.js:9:12415)
        at Object.replicate.from (http://localhost:8000/static/js/angular-pouchdb-fffix.js:129:54)
        at Object.setup (http://localhost:8000/static/js/db.js?master-f19460527fabce7619c13a57857166fbf3936133:61:30)
        at http://localhost:8000/static/js/db.js?master-f19460527fabce7619c13a57857166fbf3936133:130:28
        at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:14158:28
        at completeOutstandingRequest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:4337:10)
        at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:4638:7 

The invoking call at db.js line 61 is:

          this._db.replicate.from(remote, {'live': true}).on(...)

where this._db is an angular-pouchdb wrapped pouch. I'll investigate if angular-pouchdb isn't messing things up here, again.

**Comment by daleharvey** [comment]
We havent seen this reported in a long time, expect angular-pouchdb did something wrong here, please reopen if you have any str, thanks
