### ISSUE TITLE
%1 is not a valid Win32 application. 

### ISSUE THREAD

**Issue by Cedriking** [pouchdb/pouchdb#3052]
Hello everyone,
I've installed the node module for pouchdb, but when I try to run my application I get this error:
```
Uncaught node.js Error 
Error: %1 is not a valid Win32 application. 

c:\App\node_modules\pouchdb\node_modules\leveldown\build\Release\leveldown.node
    at Error (native)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at bindings (C:\App\node_modules\pouchdb\node_modules\leveldown\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\App\node_modules\pouchdb\node_modules\leveldown\index.js:1:99)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:354:32)
```

I dont know if someone else had this and how he/she resolved it.

Thank you for your help.

btw: I'm using Windows 8.1 x64

**Comment by daleharvey** [comment]
Upstream issue that looks fixed
