### ISSUE TITLE
Error while running `npm run build-site`

### ISSUE THREAD

**Issue by webinista** [pouchdb/pouchdb#3163]
Seeing the following error output. 

	/Users/tiff/Desktop/pouchdb/node_modules/exec-sync/bin/index.js:68
					throw new Error(error);
								^
	Error: sh: /Users/tiff/Desktop/pouchdb/bin/../node_modules/less/bin/lessc: No such file or directory
			at module.exports (/Users/tiff/Desktop/pouchdb/node_modules/exec-sync/bin/index.js:68:15)
			at buildCSS (/Users/tiff/Desktop/pouchdb/bin/build-site.js:24:5)
			at Object.<anonymous> (/Users/tiff/Desktop/pouchdb/bin/build-site.js:32:1)
			at Module._compile (module.js:456:26)
			at Object.Module._extensions..js (module.js:474:10)
			at Module.load (module.js:356:32)
			at Function.Module._load (module.js:312:12)
			at Function.Module.runMain (module.js:497:10)
			at startup (node.js:119:16)
			at node.js:906:3

I think this may be a problem with _/exec-sync/bin/index.js_, but it's breaking the documentation build.

**Comment by daleharvey** [comment]
Ok, if theres anything we can do that screws up less with other installs then please file, cheers
