### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3934]
Trying to track them here.

MemDOWN test fails for `#2913 massively parallel compaction`:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
EncodingError: Unexpected token u
    at /home/travis/build/pouchdb/pouchdb/node_modules/levelup/lib/read-stream.js:91:28
    at /home/travis/build/pouchdb/pouchdb/node_modules/pouchdb-server/node_modules/memdown/node_modules/abstract-leveldown/abstract-iterator.js:24:16
    at Object._onImmediate (/home/travis/build/pouchdb/pouchdb/node_modules/pouchdb-server/node_modules/memdown/memdown.js:86:30)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

IE10:

```
{ failures: 
   [ { message: 'expected { Object (_id, _rev, ...) } to deeply equal { Object (foo, _id, ...) }',
       stack: 'AssertionError: expected { Object (_id, _rev, ...) } to deeply equal { Object (foo, _id, ...) }\n   at assert (http://127.0.0.1:8000/node_modules/chai/chai.js:869:7)\n   at assertEql (http://127.0.0.1:8000/node_modules/chai/chai.js:1412:5)\n   at Anonymous function (http://127.0.0.1:8000/node_modules/chai/chai.js:3627:5)\n   at assertEqual (http://127.0.0.1:8000/node_modules/chai/chai.js:1378:7)\n   at Anonymous function (http://127.0.0.1:8000/node_modules/chai/chai.js:3627:5)\n   at Anonymous function (http://127.0.0.1:8000/tests/integration/test.issue3179.js:298:11)\n   at Anonymous function (http://127.0.0.1:8000/dist/pouchdb.js:22961:7)\n   at nextTick (http://127.0.0.1:8000/dist/pouchdb.js:22993:7)\n   at onreadystatechange (http://127.0.0.1:8000/dist/pouchdb.js:23077:7)',
       title: '#3179 conflicts synced, live repl' } ],
  lastPassed: '#3179 conflicts synced, non-live replication',
  failed: 1,
  passed: 715,
  browser: 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0; .NET4.0E; .NET4.0C)' }
```

Android 5.1:

```
{ failures: 
   [ { message: 'expected { Object (_id, _rev, ...) } to deeply equal { Object (foo, _id, ...) }',
       stack: 'AssertionError: expected { Object (_id, _rev, ...) } to deeply equal { Object (foo, _id, ...) }\n    at Assertion.assertEqual (http://127.0.0.1:8000/node_modules/chai/chai.js:1378:19)\n    at Assertion.ctx.(anonymous function) [as equal] (http://127.0.0.1:8000/node_modules/chai/chai.js:3627:25)\n    at http://127.0.0.1:8000/tests/integration/test.issue3179.js:298:33',
       title: '#3179 conflicts synced, live repl' } ],
  lastPassed: '#3179 conflicts synced, live sync',
  browser: 'Mozilla/5.0 (Linux; Android 5.1; Android SDK built for x86 Build/LKY45) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36',
  passed: 541,
  failed: 1 }
```

Node client + CouchDB master server:

```

[0m  1) test.retry.js-local-http #3687 active event only fired once...:

      [31mAssertionError: expected 1 to equal 2[0m
      [42m+ expected[0m [41m- actual[0m

      [42m+2[0m
      [41m-1[0m
      [0m[90m
      at Replication.<anonymous> (/home/travis/build/pouchdb/pouchdb/tests/integration/test.retry.js:138:29)
      at Replication.emit (events.js:117:20)
      at Replication.completeReplication (/home/travis/build/pouchdb/pouchdb/lib/replicate/replicate.js:258:19)
      at Replication.g (events.js:180:16)
      at Replication.emit (events.js:117:20)
      at Replication.cancel (/home/travis/build/pouchdb/pouchdb/lib/replicate/replication.js:33:8)
      at Replication.<anonymous> (/home/travis/build/pouchdb/pouchdb/tests/integration/test.retry.js:120:15)
      at Replication.emit (events.js:92:17)
      at processPendingBatch (/home/travis/build/pouchdb/pouchdb/lib/replicate/replicate.js:180:23)
      at startNextBatch (/home/travis/build/pouchdb/pouchdb/lib/replicate/replicate.js:160:7)
      at tryCatch1 (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/util.js:63:19)
      at Promise$_callHandler [as _callHandler] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/promise.js:695:13)
      at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/promise.js:711:18)
      at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/promise.js:868:14)
      at Promise$_settlePromises [as _settlePromises] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/promise.js:1006:14)
      at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/async.js:74:12)
      at Async$consumeFunctionBuffer (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/async.js:37:14)
      at process._tickCallback (node.js:448:13)
[0m
```

**Comment by nolanlawson** [comment]
```
  1) test.compaction.js-http #2913 massively parallel compaction:

     Uncaught TypeError: Cannot read property 'compact_running' of undefined

      at /home/travis/build/pouchdb/pouchdb/lib/adapters/http/index.js:276:19

      at /home/travis/build/pouchdb/pouchdb/lib/deps/toPromise.js:20:11

      at process._tickCallback (node.js:448:13)
```

**Comment by nolanlawson** [comment]
Android 5.1 inverse:

```
{"message":"[eval(\"window.results\")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command.","status":13,"cause":{"status":13,"sessionId":"74da1c64abf945dd846548189d9bf7d3","value":{"message":"The selendroid server on the device became unreachable.\nThis most likely means the app under test crashed or has been killed by the OS in a way that can't be detected using the default uncaught exception handler.\nTry to look for the reason of the...

Doh, tests failed
```

**Comment by nolanlawson** [comment]
This one appears *so often* but I just can't reproduce it locally:

```
{ failed: 1,
  lastPassed: '#3179 conflicts synced, non-live replication',
  failures: 
   [ { message: 'expected { Object (_id, _rev, ...) } to deeply equal { Object (foo, _id, ...) }',
       stack: 'AssertionError: expected { Object (_id, _rev, ...) } to deeply equal { Object (foo, _id, ...) }',
       title: '#3179 conflicts synced, live repl' } ],
  passed: 721,
  browser: 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36' }
```

**Comment by nolanlawson** [comment]
```
{ completed: true,
  failed: 1,
  passed: 178,
  failures: 
   [ { message: '{"status":404,"name":"not_found","message":"missing"} (http://127.0.0.1:8000/dist/pouchdb.js:12938)',
       stack: null,
       title: '"before each" hook' } ],
  lastPassed: 'Kill database while listening to live changes',
  browser: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/536.30.1 (KHTML, like Gecko) Version/6.0.5 Safari/536.30.1' }
```

**Comment by daleharvey** [comment]
So these have started being super intermittent again, it kinda seems like the travis upgrade has regressedd, investigating now

**Comment by daleharvey** [comment]
Master - https://travis-ci.org/pouchdb/pouchdb/builds/97214561 - 3/10
Reverted leveldown commit - https://travis-ci.org/pouchdb/pouchdb/builds/97823831 - 6/10

**Comment by daleharvey** [comment]
Reverted leveldown + new travis - https://travis-ci.org/pouchdb/pouchdb/builds/97824906 - 10/10

**Comment by daleharvey** [comment]
new travis - https://travis-ci.org/pouchdb/pouchdb/builds/97825751 - 8/10

**Comment by daleharvey** [comment]
Looking at the failures, the 2 failures on new travis were both test suites failures, most failures before that are segmentation faults, so there is definitely a problem with the travis infrastructure, will work on upgrading that first, then there 'may' be an issue with leveldown, will investigate after

**Comment by daleharvey** [comment]
ok so the vast majority of these are fixed by upgrading travis, now investigating the phantom failures and the increase in level base intermittents

**Comment by daleharvey** [comment]
So current level is 10/10 for failures, doing a run @ https://travis-ci.org/daleharvey/pouchdb/builds/97906682 reverting the last phantom update

**Comment by daleharvey** [comment]
Reverted last phantom - https://travis-ci.org/daleharvey/pouchdb/builds/97906682 - 10/10 failures

**Comment by daleharvey** [comment]
And reverted last es5 shim - https://travis-ci.org/daleharvey/pouchdb/builds/97908086 - 10/10 fails

**Comment by daleharvey** [comment]
Opened a PR to add phantomjs to expected failures - https://github.com/pouchdb/pouchdb/pull/4674

**Comment by daleharvey** [comment]
ok now for the node runs, 

master - https://travis-ci.org/pouchdb/pouchdb/builds/97945056 - 9/20 failures

**Comment by daleharvey** [comment]
ok so now we are getting back to relatively more stable, I would like to file seperate bugs for the intermittents we are seeing instead of having a single global issue, I think it is more actionable that way
