### ISSUE TITLE
CouchDB master started failing again

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3951]
Started just today. Failures: https://travis-ci.org/pouchdb/pouchdb/jobs/66147182 and https://travis-ci.org/pouchdb/pouchdb/jobs/66147183.

In particular, we seem to consistently get this error:

```
  6 passing (740ms)

  1 failing

  1) test.all_docs.js-http Testing conflicts:

      Uncaught AssertionError: expected '1-211c37537c043fcb1c4b4936b843966c' to equal '2-ff01552213fafa022e6167113ed01087'

      + expected - actual

      +"2-ff01552213fafa022e6167113ed01087"

      -"1-211c37537c043fcb1c4b4936b843966c"

      

      at /home/travis/build/pouchdb/pouchdb/tests/integration/test.all_docs.js:224:34

      at /home/travis/build/pouchdb/pouchdb/lib/deps/toPromise.js:20:11

      at process._tickCallback (node.js:448:13)
```

**Comment by nolanlawson** [comment]
cc @kxepal @chewbranca @rnewson. I'm sorry that we don't log the commit hash from the CouchDB version, but hopefully the fact that it started failing around today (-ish) can give you some clues.

**Comment by kxepal** [comment]
@nolanlawson seems like document didn't get updated at the moment when you'd requested it for revs comparison. Assuming how travis is slow, that's not surprise.

**Comment by nolanlawson** [comment]
@kxepal The tests are consistently failing. I restarted Travis a few times...

**Comment by daleharvey** [comment]
@kxepal I would be very surprised if this were a race condition in the test itself, we have spent quite a lot of time ironing out any race conditions in the test suite and the ones that may exist will show up with extremely sporadic failures, if couch-master tests just started failing consistently then it seems very likely its a recent change to couch

https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.all_docs.js#L206 is the test in question

**Comment by daleharvey** [comment]
Hrm, I was about to say there hasnt been any changes to couch recently, but forgot the repo has all be split out, @rnewson posted a handy snippet to see recent changes - https://gist.github.com/rnewson/6e7bad37dd8a85d9de05

**Comment by kxepal** [comment]
@daleharvey Well, I cannot explain it either:
```
~ $ curl -XPUT http://localhost:15984/test 
{"ok":true}

~ $ curl -XPOST http://localhost:15984/test/_bulk_docs -d '{"docs": [{"_id": "0", "a": 1, "b": 1}, {"_id": "3", "a": 4, "b": 16}, {"_id": "1", "a": 2, "b": 4}, {"_id": "2", "a": 3, "b": 9}]}' -H 'Content-Type: application/json'
[{"ok":true,"id":"0","rev":"1-fb8a93eb436b7e799a7bbc578a08e9a5"},{"ok":true,"id":"3","rev":"1-211c37537c043fcb1c4b4936b843966c"},{"ok":true,"id":"1","rev":"1-2b6adfdea4e0fd276a861f663cf984ba"},{"ok":true,"id":"2","rev":"1-3a0bf449367880a229ea7c61f9394c83"}]

~ $ curl -XPUT http://localhost:15984/test/3?new_edits=false -d '{"_id": "3", "_rev": "2-aa01552213fafa022e6167113ed01087", "value": "X"}'
{"ok":true,"id":"3","rev":"2-aa01552213fafa022e6167113ed01087"}

~ $ curl -XPUT http://localhost:15984/test/3?new_edits=false -d '{"_id": "3", "_rev": "2-ff01552213fafa022e6167113ed01087", "value": "Z"}'
{"ok":true,"id":"3","rev":"2-ff01552213fafa022e6167113ed01087"}

~ $ curl http://localhost:15984/test/3
{"_id":"3","_rev":"2-ff01552213fafa022e6167113ed01087","value":"Z"}

```

And obliviously test will pass.

**Comment by kxepal** [comment]
The reason is quite trivial: CouchDB 2.0 _may_ return HTTP 202 response [instead](https://github.com/apache/couchdb-chttpd/blob/master/src/chttpd_db.erl#L871-L897) of 201 if fabric fails to have write quorum met or just reached timeout for the [reply](https://github.com/apache/couchdb-fabric/blob/master/src/fabric_doc_update.erl#L39-L48).

I believe, PouchDB tests handles HTTP 202 Accepted as HTTP 201 Created and thinks that all data is updated, but they are doesn't because travis is extremely slow. And here is your RC case.

**Comment by daleharvey** [comment]
hrm not certain that is the error, I cant see a 202 being sent in the logs @ https://pastebin.mozilla.org/8836476, its reproducing locally consistently, its certainly a change in behaviour, should be fairly simple to flesh out from here

**Comment by daleharvey** [comment]
```
pouchdb:http GET http://127.0.0.1:15984/testdb/ +1ms
  pouchdb:api http://127.0.0.1:15984/testdb +1ms put { _id: '0', a: 1, b: 1 }
  pouchdb:http PUT http://127.0.0.1:15984/testdb/ +2ms
  pouchdb:api http://127.0.0.1:15984/testdb +68ms put { _id: '0', a: 1, b: 1 }
  pouchdb:http PUT http://127.0.0.1:15984/testdb/0 +1ms
  pouchdb:api http://127.0.0.1:15984/testdb +26ms put success { ok: true, id: '0', rev: '1-fb8a93eb436b7e799a7bbc578a08e9a5' }
  pouchdb:api http://127.0.0.1:15984/testdb +0ms put success { ok: true, id: '0', rev: '1-fb8a93eb436b7e799a7bbc578a08e9a5' }
  pouchdb:api http://127.0.0.1:15984/testdb +0ms put { _id: '3', a: 4, b: 16 }
  pouchdb:http PUT http://127.0.0.1:15984/testdb/3 +0ms
  pouchdb:api http://127.0.0.1:15984/testdb +13ms put success { ok: true, id: '3', rev: '1-211c37537c043fcb1c4b4936b843966c' }
  pouchdb:api http://127.0.0.1:15984/testdb +0ms put { _id: '1', a: 2, b: 4 }
  pouchdb:http PUT http://127.0.0.1:15984/testdb/1 +0ms
  pouchdb:api http://127.0.0.1:15984/testdb +21ms put success { ok: true, id: '1', rev: '1-2b6adfdea4e0fd276a861f663cf984ba' }
  pouchdb:api http://127.0.0.1:15984/testdb +0ms put { _id: '2', a: 3, b: 9 }
  pouchdb:http PUT http://127.0.0.1:15984/testdb/2 +0ms
  pouchdb:api http://127.0.0.1:15984/testdb +16ms put success { ok: true, id: '2', rev: '1-3a0bf449367880a229ea7c61f9394c83' }
  pouchdb:api http://127.0.0.1:15984/testdb +1ms put { _id: '3',
  _rev: '2-aa01552213fafa022e6167113ed01087',
  value: 'X' } { new_edits: false }
  pouchdb:http PUT http://127.0.0.1:15984/testdb/3?new_edits=false +0ms
  pouchdb:api http://127.0.0.1:15984/testdb +5ms put error { status: 409,
  name: 'conflict',
  message: 'Document update conflict',
  error: true,
  reason: 'Document update conflict.' }
  pouchdb:api http://127.0.0.1:15984/testdb +1ms put { _id: '3',
  _rev: '2-ff01552213fafa022e6167113ed01087',
  value: 'Z' } { new_edits: false }
  pouchdb:http PUT http://127.0.0.1:15984/testdb/3?new_edits=false +0ms
  pouchdb:api http://127.0.0.1:15984/testdb +4ms put error { status: 409,
  name: 'conflict',
  message: 'Document update conflict',
  error: true,
  reason: 'Document update conflict.' }
  pouchdb:api http://127.0.0.1:15984/testdb +0ms get 3
  pouchdb:http GET http://127.0.0.1:15984/testdb/3 +0ms
  pouchdb:api http://127.0.0.1:15984/testdb +4ms get success { _id: '3',
  _rev: '1-211c37537c043fcb1c4b4936b843966c',
  a: 4,
  b: 16 }
``` 
Is the log from pouch

**Comment by daleharvey** [comment]
hrm, I am getting entirely different behaviour on my local master to @kxepal 
```
$ curl -XPUT http://localhost:15984/test
{"ok":true}
~/src/pouchdb (3951)$ curl -XPOST http://localhost:15984/test/_bulk_docs -d '{"docs": [{"_id": "0", "a": 1, "b": 1}, {"_id": "3", "a": 4, "b": 16}, {"_id": "1", "a": 2, "b": 4}, {"_id": "2", "a": 3, "b": 9}]}' -H 'Content-Type: application/json'
[{"ok":true,"id":"0","rev":"1-fb8a93eb436b7e799a7bbc578a08e9a5"},{"ok":true,"id":"3","rev":"1-211c37537c043fcb1c4b4936b843966c"},{"ok":true,"id":"1","rev":"1-2b6adfdea4e0fd276a861f663cf984ba"},{"ok":true,"id":"2","rev":"1-3a0bf449367880a229ea7c61f9394c83"}]
~/src/pouchdb (3951)$ curl -XPUT http://localhost:15984/test/3?new_edits=false -d '{"_id": "3", "_rev": "2-aa01552213fafa022e6167113ed01087", "value": "X"}'
{"error":"conflict","reason":"Document update conflict."}
~/src/pouchdb (3951)$ curl -XPUT http://localhost:15984/test/3?new_edits=false -d '{"_id": "3", "_rev": "2-ff01552213fafa022e6167113ed01087", "value": "Z"}'
{"error":"conflict","reason":"Document update conflict."}
~/src/pouchdb (3951)$ curl http://localhost:15984/test/3
{"_id":"3","_rev":"1-211c37537c043fcb1c4b4936b843966c","a":4,"b":16}
```

**Comment by kxepal** [comment]
What is strange that you get 409 for non-interactive document update.

**Comment by daleharvey** [comment]
Yeh it seems somehow the new_edits is being missed

**Comment by daleharvey** [comment]
On IRC Kxepal has said he has identified the bug in recent changes on the couch side so should be on its way to being fixed

**Comment by kxepal** [comment]
Should be fixed in https://github.com/apache/couchdb-fabric/commit/19df05419048478a92c747cb5c20c0c7a0331f51
Thanks for the report!

**Comment by nolanlawson** [comment]
Seems to be passing now. I feel comfortable closing.

Also, three cheers for PouchDB being a canary in the coalmine for CouchDB. :) I love contributing upstream to our big sister.
