### ISSUE TITLE
Cannot read property 'compact_running' of undefined

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3989]
Seen in the memdown tests a few times now

**Comment by daleharvey** [comment]
This is an error in pouchdb server - https://github.com/pouchdb/pouchdb/issues/3989

**Comment by daleharvey** [comment]
PR for a fix is up @ https://github.com/pouchdb/express-pouchdb/pull/227

**Comment by nolanlawson** [comment]
This is still happening occasionally. I just reproduced it:

```
[info] PUT /testdb/doc/att.txt?rev=4-3b65ee3ab36469f0e2abdd019a018c22 201 - 127.0.0.1

events.js:141
      throw er; // Unhandled 'error' event
      ^
EncodingError: Unexpected token u
    at /home/nolan/.npm-packages/lib/node_modules/pouchdb-server/node_modules/pouchdb/node_modules/levelup/lib/read-stream.js:91:28
    at /home/nolan/.npm-packages/lib/node_modules/pouchdb-server/node_modules/memdown/node_modules/abstract-leveldown/abstract-iterator.js:24:16
    at Immediate._onImmediate (/home/nolan/.npm-packages/lib/node_modules/pouchdb-server/node_modules/memdown/memdown.js:86:30)
    at processImmediate [as _immediateCallback] (timers.js:371:17)

```

```
  1) test.compaction.js-http #2931 - synchronous putAttachment + compact 2:
     Uncaught TypeError: Cannot read property 'compact_running' of undefined
      at /home/nolan/workspace/pouchdb/lib/adapters/http/index.js:263:19
      at /home/nolan/workspace/pouchdb/lib/deps/toPromise.js:20:11
      at doNTCallback0 (node.js:408:9)
      at process._tickCallback (node.js:337:13)

  2) test.compaction.js-http #2931 - synchronous putAttachment + compact 2:
     Uncaught TypeError: Cannot read property 'compact_running' of undefined
      at /home/nolan/workspace/pouchdb/lib/adapters/http/index.js:263:19
      at /home/nolan/workspace/pouchdb/lib/deps/toPromise.js:20:11
      at doNTCallback0 (node.js:408:9)
      at process._tickCallback (node.js:337:13)

  3) test.compaction.js-http #2931 - synchronous putAttachment + compact 2:
     Uncaught TypeError: Cannot read property 'compact_running' of undefined
      at /home/nolan/workspace/pouchdb/lib/adapters/http/index.js:263:19
      at /home/nolan/workspace/pouchdb/lib/deps/toPromise.js:20:11
      at doNTCallback0 (node.js:408:9)
      at process._tickCallback (node.js:337:13)

  4) test.compaction.js-http #2931 - synchronous putAttachment + compact 2:
     Uncaught TypeError: Cannot read property 'compact_running' of undefined
      at /home/nolan/workspace/pouchdb/lib/adapters/http/index.js:263:19
      at /home/nolan/workspace/pouchdb/lib/deps/toPromise.js:20:11
      at doNTCallback0 (node.js:408:9)
      at process._tickCallback (node.js:337:13)

  5) test.compaction.js-http #2931 - synchronous putAttachment + compact 2:
     Uncaught TypeError: Cannot read property 'compact_running' of undefined
      at /home/nolan/workspace/pouchdb/lib/adapters/http/index.js:263:19
      at /home/nolan/workspace/pouchdb/lib/deps/toPromise.js:20:11
      at doNTCallback0 (node.js:408:9)
      at process._tickCallback (node.js:337:13)

  6) test.compaction.js-http #2931 - synchronous putAttachment + compact 2:
     Uncaught TypeError: Cannot read property 'compact_running' of undefined
      at /home/nolan/workspace/pouchdb/lib/adapters/http/index.js:263:19
      at /home/nolan/workspace/pouchdb/lib/deps/toPromise.js:20:11
      at doNTCallback0 (node.js:408:9)
      at process._tickCallback (node.js:337:13)

```

**Comment by nolanlawson** [comment]
Seems we might be able to fix this by upgrading memdown. We are a bit behind.

**Comment by nolanlawson** [comment]
The [offending lines of code](https://github.com/Level/memdown/blob/3803cd3faa316a117144d1fac04df86bca0cd5a8/memdown.js#L78-L81) are from memdown 0.10.0 and it's already on 1.0.0.

**Comment by daleharvey** [comment]
Ok memdown should have fixed this, havent seen it in a while now
