### ISSUE TITLE
Fuzzy test failures are not reproducable

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4108]
I do occasionally see these. If we keep track of the seeds, we can re-seed them and re-run them:
- 1438530651602

```
Seeded with: 1438530651602

[0m[0m
[0m  chaos-monkey[0m
[2K[0G  [31m  1) Do a fuzzy replication run[0m


[92m [0m[32m 0 passing[0m[90m (2s)[0m
[31m  1 failing[0m

[0m  1) chaos-monkey Do a fuzzy replication run:

      [31mAssertionError: expected { Object (total_rows, offset, ...) } to deeply equal { Object (total_rows, offset, ...) }[0m
      [42m+ expected[0m [41m- actual[0m

             }
           }
           {
             "doc": {
      [41m-        "_id": "random-1438530652984"[0m
      [41m-        "_rev": "1-121cfdafe06b812c9d61cb8f18e49c82"[0m
      [41m-        "baz": "fubar"[0m
      [41m-        "foo": "bar"[0m
      [41m-      }[0m
      [41m-      "id": "random-1438530652984"[0m
      [41m-      "key": "random-1438530652984"[0m
      [41m-      "value": {[0m
      [41m-        "rev": "1-121cfdafe06b812c9d61cb8f18e49c82"[0m
      [41m-      }[0m
      [41m-    }[0m
      [41m-    {[0m
      [41m-      "doc": {[0m
               "_id": "random-1438530653150"
               "_rev": "1-8880137ff838c62f4c8caba88f472196"
               "baz": "fubar"
               "foo": "bar"
               "rev": "1-f67b71b49e893010d966be67f4c1c97f"
             }
           }
         ]
      [42m+  "total_rows": 30[0m
      [41m-  "total_rows": 31[0m
       }
      [0m[90m
      at assertEqual (/home/travis/build/pouchdb/pouchdb/node_modules/chai/lib/chai/core/assertions.js:439:19)
      at ctx.(anonymous function) (/home/travis/build/pouchdb/pouchdb/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at doAsserterAsyncAndAddThen (/home/travis/build/pouchdb/pouchdb/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
      at null.<anonymous> (/home/travis/build/pouchdb/pouchdb/node_modules/chai-as-promised/lib/chai-as-promised.js:251:21)
      at ctx.(anonymous function) [as equal] (/home/travis/build/pouchdb/pouchdb/node_modules/chai/lib/chai/utils/overwriteMethod.js:48:33)
      at /home/travis/build/pouchdb/pouchdb/tests/fuzzy/test.fuzzy.js:156:26
      at Array.0 (/home/travis/build/pouchdb/pouchdb/node_modules/lie/lib/unwrap.js:11:21)
      at nextTick (/home/travis/build/pouchdb/pouchdb/node_modules/lie/node_modules/immediate/lib/index.js:21:18)
      at process._tickCallback (node.js:448:13)
[0m
```

**Comment by daleharvey** [comment]
So the issue with this is the seeding functionality isnt working in node, and the browser version isnt running in travis, I will fix one of the 2 of those shortly. So right now these tests arent particularly useful, they are however most definitely finding bugs already and they are currently the most basic tests they can be

**Comment by daleharvey** [comment]
To explain this issue, the fuzzy tests work by performing a random series of actions on a database, those 2 databases are then replicated at the end of the test and a successful test is when the contents of both databases match.

We are getting intermittent failures with this test which suggests a bug somewhere, we generate a seed at the start of every test run which means Math.random should be returning consistent the same numbers given the same seed which in theory should make the test deterministic, however that is not currently working, a possible issue may be timing differences in the event loop?
