### ISSUE TITLE
PouchDB 4.0.3 - db.info() causes uncaught error on down database

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4358]
I can repro in Node with 4.0.3:

```js
var PouchDB = require('pouchdb')
var db = new PouchDB('http://fake.com/foo')
db.info().then(console.log.bind(console)).catch(console.log.bind(console))
```

^ This promise never resolves. Looks like an uncaught exception according to Bluebird:

    Unhandled rejection {"status":405,"name":"unknown_error","message":"Database encountered an unknown error"}

**Comment by nolanlawson** [comment]
Prompted by [a SO question](http://stackoverflow.com/questions/32716840/pouchdb-4-0-3-uncaught-in-promise-when-i-call-info-on-unreachable-database).

**Comment by nolanlawson** [comment]
`bluebird.longStackTraces()` found the culprit:

```
Unhandled rejection {"status":405,"name":"unknown_error","message":"Database encountered an unknown error"}
    (No stack trace)
From previous event:
    at ajaxPromise (/private/tmp/foo/node_modules/pouchdb/lib/adapters/http/index.js:151:12)
    at /private/tmp/foo/node_modules/pouchdb/lib/adapters/http/index.js:193:16
    at bound (domain.js:250:14)
    at runBound (domain.js:263:12)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
From previous event:
    at setup (/private/tmp/foo/node_modules/pouchdb/lib/adapters/http/index.js:189:50)
    at PouchDB.HttpPouch.api._info (/private/tmp/foo/node_modules/pouchdb/lib/adapters/http/index.js:273:5)
    at PouchDB.<anonymous> (/private/tmp/foo/node_modules/pouchdb/lib/adapter.js:709:8)
    at PouchDB.<anonymous> (/private/tmp/foo/node_modules/pouchdb/lib/utils.js:136:21)
    at PouchDB.<anonymous> (/private/tmp/foo/node_modules/pouchdb/node_modules/argsarray/index.js:14:18)
    at /private/tmp/foo/node_modules/pouchdb/lib/deps/toPromise.js:37:21
From previous event:
    at PouchDB.<anonymous> (/private/tmp/foo/node_modules/pouchdb/lib/deps/toPromise.js:24:19)
    at PouchDB.info (/private/tmp/foo/node_modules/pouchdb/node_modules/argsarray/index.js:16:18)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:392:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:546:8)
    at REPLServer.Interface._ttyWrite (readline.js:823:14)
    at ReadStream.onkeypress (readline.js:105:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)
    at emitKeys (readline.js:1247:14)
    at next (native)
    at ReadStream.onData (readline.js:915:36)
    at emitOne (events.js:77:13)
```

This is actually a very serious bug, but also one that I think is within reach of new contributors.

**Comment by colinskow** [comment]
Fixed... added .catch after `setup().then(...)` in `/lib/adapters/http/index.js` line 272.

```js
api._info = function (callback) {
    setup().then(function() {
      ajax({
        headers: clone(host.headers),
        method: 'GET',
        url: genDBUrl(host, '')
      }, function (err, res) {
        /* istanbul ignore next */
        if (err) {
        return callback(err);
        }
        res.host = genDBUrl(host, '');
        callback(null, res);
      });
    })
      .catch(callback);
  };
```

Must also be done for `_destroy`.

**Comment by colinskow** [comment]
Also under `_changes`:
```js
// Get the changes
      setup().then(function() {
        xhr = ajax(xhrOpts, callback);
      }).catch(callback);
```

**Comment by colinskow** [comment]
https://github.com/pouchdb/pouchdb/pull/4359

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/67bce62b618847cd49908da8081db7028347d686
