### ISSUE TITLE
Cannot read property '_rev' of undefined

### ISSUE THREAD

**Issue by nono** [pouchdb/pouchdb#4518]
Hello,

I'm using pouchdb 5.0.0 and I've found a bug. The pouchdb logs are here:

```
  pouchdb:adapter Picked adapter: leveldb +0ms
  pouchdb:adapter Picked adapter: http +13ms
  pouchdb:api tmp/cc/.cozy-desktop/db +34ms get _design/byPath
  pouchdb:api tmp/cc/.cozy-desktop/db +7ms get _design/byPath
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms get success { views: { byPath: { map: 'function (doc) {\n        var parts;\n        if (\'docType\' in doc) {\n          parts = doc._id.split(\'/\');\n          parts.pop();\n          return emit(parts.join(\'/\'), {\n            _id: doc._id\n          });\n        }\n      }' } },
  _id: '_design/byPath',
  _rev: '6-1c919b75349672c879f7dcd6e933fca5' }
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms get success { views: { byPath: { map: 'function (doc) {\n        var parts;\n        if (\'docType\' in doc) {\n          parts = doc._id.split(\'/\');\n          parts.pop();\n          return emit(parts.join(\'/\'), {\n            _id: doc._id\n          });\n        }\n      }' } },
  _id: '_design/byPath',
  _rev: '6-1c919b75349672c879f7dcd6e933fca5' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms put { _id: '_design/byPath',
  views: { byPath: { map: 'function (doc) {\n        var parts;\n        if (\'docType\' in doc) {\n          parts = doc._id.split(\'/\');\n          parts.pop();\n          return emit(parts.join(\'/\'), {\n            _id: doc._id\n          });\n        }\n      }' } },
  _rev: '6-1c919b75349672c879f7dcd6e933fca5' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms bulkDocs { docs: 
   [ { _id: '_design/byPath',
       views: [Object],
       _rev: '6-1c919b75349672c879f7dcd6e933fca5' } ] } {}
  pouchdb:api tmp/cc/.cozy-desktop/db +4ms bulkDocs success [ { ok: true,
    id: '_design/byPath',
    rev: '7-d19941f3a062c49934af5e1664dd1b44' } ]
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms put success { ok: true,
  id: '_design/byPath',
  rev: '7-d19941f3a062c49934af5e1664dd1b44' }
  pouchdb:api tmp/cc/.cozy-desktop/db +30ms get _design/byChecksum
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms get success { views: { byChecksum: { map: 'function (doc) {\n        if (\'checksum\' in doc) {\n          return emit(doc.checksum);\n        }\n      }' } },
  _id: '_design/byChecksum',
  _rev: '6-2dc1fdfea95ecba7e04f386bdea15a21' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms put { _id: '_design/byChecksum',
  views: { byChecksum: { map: 'function (doc) {\n        if (\'checksum\' in doc) {\n          return emit(doc.checksum);\n        }\n      }' } },
  _rev: '6-2dc1fdfea95ecba7e04f386bdea15a21' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms bulkDocs { docs: 
   [ { _id: '_design/byChecksum',
       views: [Object],
       _rev: '6-2dc1fdfea95ecba7e04f386bdea15a21' } ] } {}
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms bulkDocs success [ { ok: true,
    id: '_design/byChecksum',
    rev: '7-6333ca8382e9641b20ed96647583005b' } ]
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms put success { ok: true,
  id: '_design/byChecksum',
  rev: '7-6333ca8382e9641b20ed96647583005b' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get _design/byRemoteId
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { views: { byRemoteId: { map: 'function (doc) {\n        if (\'remote\' in doc) {\n          return emit(doc.remote._id);\n        }\n      }' } },
  _id: '_design/byRemoteId',
  _rev: '6-48ac403b297be8a1215fe66a27ab660f' }
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms put { _id: '_design/byRemoteId',
  views: { byRemoteId: { map: 'function (doc) {\n        if (\'remote\' in doc) {\n          return emit(doc.remote._id);\n        }\n      }' } },
  _rev: '6-48ac403b297be8a1215fe66a27ab660f' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms bulkDocs { docs: 
   [ { _id: '_design/byRemoteId',
       views: [Object],
       _rev: '6-48ac403b297be8a1215fe66a27ab660f' } ] } {}
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms bulkDocs success [ { ok: true,
    id: '_design/byRemoteId',
    rev: '7-fd94229002935612859c27b76de79b16' } ]
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms put success { ok: true,
  id: '_design/byRemoteId',
  rev: '7-fd94229002935612859c27b76de79b16' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get _local/remoteSeq
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { _id: '_local/remoteSeq', seq: 1976, _rev: '0-32' }
  pouchdb:http GET http://localhost:9104/cozy/ +1ms
  pouchdb:http GET http://localhost:9104/cozy/_changes?timeout=25000&include_docs=true&heartbeat=10000&since=1976&limit=25 +13ms
  pouchdb:api tmp/cc/.cozy-desktop/db +53ms get _design/byRemoteId
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get _design/byRemoteId
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms get _local/localSeq
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get _local/remoteSeq
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { _id: '_local/localSeq', _rev: '0-21', seq: 29 }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms info
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms get _design/byPath
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms info success { doc_count: 12,
  update_seq: 42,
  backend_adapter: 'LevelDOWN',
  db_name: 'tmp/cc/.cozy-desktop/db',
  auto_compaction: false,
  adapter: 'leveldb' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { _id: '_local/remoteSeq', seq: 1976, _rev: '0-32' }
  pouchdb:api http://localhost:9104//cozy +0ms info
  pouchdb:http GET http://localhost:9104/cozy/ +0ms
  pouchdb:http GET http://localhost:9104/cozy/_changes?timeout=25000&include_docs=true&feed=longpoll&heartbeat=10000&since=1976&limit=25 +1ms
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { views: { byRemoteId: { map: 'function (doc) {\n        if (\'remote\' in doc) {\n          return emit(doc.remote._id);\n        }\n      }' } },
  _id: '_design/byRemoteId',
  _rev: '7-fd94229002935612859c27b76de79b16' }
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms info
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms info success { doc_count: 12,
  update_seq: 42,
  backend_adapter: 'LevelDOWN',
  db_name: 'tmp/cc/.cozy-desktop/db',
  auto_compaction: false,
  adapter: 'leveldb' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get _local/mrviews
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { views: { byRemoteId: { map: 'function (doc) {\n        if (\'remote\' in doc) {\n          return emit(doc.remote._id);\n        }\n      }' } },
  _id: '_design/byRemoteId',
  _rev: '7-fd94229002935612859c27b76de79b16' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms info
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms info success { doc_count: 12,
  update_seq: 42,
  backend_adapter: 'LevelDOWN',
  db_name: 'tmp/cc/.cozy-desktop/db',
  auto_compaction: false,
  adapter: 'leveldb' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get _local/mrviews
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { views: 
   { 'byRemoteId/byRemoteId': { 'tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a': true },
     'byChecksum/byChecksum': { 'tmp/cc/.cozy-desktop/db-mrview-4c9aa8c3523df85c132b95a3c31fa6e4': true } },
  _id: '_local/mrviews',
  _rev: '0-2' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms registerDependentDatabase tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a
  pouchdb:adapter Picked adapter: leveldb +1ms
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get _local/_pouch_dependentDbs
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { views: 
   { 'byRemoteId/byRemoteId': { 'tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a': true },
     'byChecksum/byChecksum': { 'tmp/cc/.cozy-desktop/db-mrview-4c9aa8c3523df85c132b95a3c31fa6e4': true } },
  _id: '_local/mrviews',
  _rev: '0-2' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms registerDependentDatabase tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a
  pouchdb:adapter Picked adapter: leveldb +0ms
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms get _local/_pouch_dependentDbs
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { dependentDbs: 
   { 'tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a': true,
     'tmp/cc/.cozy-desktop/db-mrview-4c9aa8c3523df85c132b95a3c31fa6e4': true },
  _id: '_local/_pouch_dependentDbs',
  _rev: '0-2' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms registerDependentDatabase success { db: 
   { __opts: {},
     auto_compaction: undefined,
     prefix: '_pouch_',
     domain: null,
     _events: {},
     _maxListeners: 10,
     taskqueue: { isReady: false, failed: false, queue: [] },
     _adapter: 'leveldb',
     _db_name: 'tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a',
     adapter: 'leveldb',
     replicate: { from: [Function], to: [Function], sync: [Function] },
     sync: [Function],
     type: [Function],
     _id: [Function],
     _info: [Function],
     _get: [Function],
     _getAttachment: [Function],
     _bulkDocs: [Function],
     _allDocs: [Function],
     _changes: [Function],
     _close: [Function],
     _getRevisionTree: [Function],
     _doCompaction: [Function],
     _doCompactionNoLock: [Function],
     _getLocal: [Function],
     _putLocal: [Function],
     _putLocalWithLock: [Function],
     _putLocalNoLock: [Function],
     _removeLocal: [Function],
     _removeLocalWithLock: [Function],
     _removeLocalNoLock: [Function],
     _destroy: [Function],
     then: [Function],
     catch: [Function] } }
  pouchdb:api tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a +1ms get _local/lastSeq
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms get success { views: { byPath: { map: 'function (doc) {\n        var parts;\n        if (\'docType\' in doc) {\n          parts = doc._id.split(\'/\');\n          parts.pop();\n          return emit(parts.join(\'/\'), {\n            _id: doc._id\n          });\n        }\n      }' } },
  _id: '_design/byPath',
  _rev: '7-d19941f3a062c49934af5e1664dd1b44' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms info
  pouchdb:api tmp/cc/.cozy-desktop/db +3ms info success { doc_count: 12,
  update_seq: 42,
  backend_adapter: 'LevelDOWN',
  db_name: 'tmp/cc/.cozy-desktop/db',
  auto_compaction: false,
  adapter: 'leveldb' }
  pouchdb:api tmp/cc/.cozy-desktop/db +1ms get success { dependentDbs: 
   { 'tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a': true,
     'tmp/cc/.cozy-desktop/db-mrview-4c9aa8c3523df85c132b95a3c31fa6e4': true },
  _id: '_local/_pouch_dependentDbs',
  _rev: '0-2' }
  pouchdb:api tmp/cc/.cozy-desktop/db +0ms registerDependentDatabase success { db: 
   { __opts: {},
     auto_compaction: undefined,
     prefix: '_pouch_',
     domain: null,
     _events: {},
     _maxListeners: 10,
     taskqueue: { isReady: false, failed: false, queue: [] },
     _adapter: 'leveldb',
     _db_name: 'tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a',
     adapter: 'leveldb',
     replicate: { from: [Function], to: [Function], sync: [Function] },
     sync: [Function],
     type: [Function],
     _id: [Function],
     _info: [Function],
     _get: [Function],
     _getAttachment: [Function],
     _bulkDocs: [Function],
     _allDocs: [Function],
     _changes: [Function],
     _close: [Function],
     _getRevisionTree: [Function],
     _doCompaction: [Function],
     _doCompactionNoLock: [Function],
     _getLocal: [Function],
     _putLocal: [Function],
     _putLocalWithLock: [Function],
     _putLocalNoLock: [Function],
     _removeLocal: [Function],
     _removeLocalWithLock: [Function],
     _removeLocalNoLock: [Function],
     _destroy: [Function],
     then: [Function],
     catch: [Function] } }
  pouchdb:api tmp/cc/.cozy-desktop/db-mrview-5fe5a33e24e84ff6898d2f6b8cefc95a +0ms get _local/lastSeq
  pouchdb:api http://localhost:9104//cozy +3ms info success { db_name: 'cozy',
  doc_count: 60,
  doc_del_count: 141,
  update_seq: 1979,
  purge_seq: 0,
  compact_running: false,
  disk_size: 15421547,
  data_size: 2065553,
  instance_start_time: '1446018792944912',
  disk_format_version: 6,
  committed_update_seq: 1979,
  host: 'http://localhost:9104/cozy/',
  auto_compaction: false,
  adapter: 'http' }

/home/nono/cc/desktop/node_modules/pouchdb/lib/changes.js:93
  var changeList = [{rev: doc._rev}];
                             ^
TypeError: Cannot read property '_rev' of undefined
  at Object.processChange (/home/nono/cc/desktop/node_modules/pouchdb/lib/changes.js:93:30)
  at onGetWinningDoc (/home/nono/cc/desktop/node_modules/pouchdb/lib/adapters/leveldb/index.js:1003:29)
  at /home/nono/cc/desktop/node_modules/pouchdb/lib/adapters/leveldb/index.js:1047:11
  at /home/nono/cc/desktop/node_modules/pouchdb/node_modules/level-sublevel/shell.js:101:15
  at /home/nono/cc/desktop/node_modules/pouchdb/node_modules/level-sublevel/nut.js:120:19
```

I'm not sure exactly which operation fails, but I think it is on a live changes:

```coffee
            opts =
                live: true
                since: seq
                include_docs: true
                returnDocs: false
                filter: '_view'
                view: 'byPath'
            @pouch.db.changes(opts)
```

What do you think?

**Comment by nono** [comment]
I'm also using the pouchdb library as a client to a remote couchdb on http://localhost:9104/cozy.

```coffee
            @changes = @couch.client.changes
                filter: (doc) ->
                    doc.docType?.toLowerCase() in ['file', 'folder']
                live: options.live
                retry: true
                since: seq
                include_docs: true
```

**Comment by nono** [comment]
On this line (https://github.com/pouchdb/pouchdb/blob/5.0.0/lib/adapters/leveldb/index.js#L1046), the callback is called with `err='NotFoundError: Key not found in database'` and `doc=undefined`.

**Comment by nolanlawson** [comment]
Thanks for reporting! If you had a test to reproduce, that would be awesome. Looks like it's a purely local error - nothing to do with the remote CouchDB? Also seems LevelDB-specific, so it would be good to know what kind of OS you're using.

**Comment by nono** [comment]
I'm on linux:

```
$ uname -a
Linux lechat 3.19.0-31-generic #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nono** [comment]
For the moment, I don't find how to extract a test case from my software. Even with it, it doesn't seem to be very deterministic.

**Comment by nolanlawson** [comment]
I'm going to close until we have a reproducible test case. Unfortunately we cannot fix the bug with the information provided, although I believe you that it is an error.

**Comment by ngrj** [comment]
Hi, thanks for the awesome work on pouchdb,
I've a node webkit application which is installed around few hundred places, almost every other day one of the clients application faces these issue, we have to delete the local pouch database and replicate the same database to use it. Re replicating the database fixes the issue. But since I've very large amount of docs these does not seem to be a ideal solution. So, I tried debugging the issue. Here are the things I've found out from my debugging: 

- If you call allDocs with option include_docs True, it will raise the above issue

- If you call allDocs without include_docs, it won't raise the issue, so it led me to believe that some doc content must be missing , so I called allDocs with include_docs:false and then for every id I've received I called db.get() and I found a Id for which I've recieved a 404 error instead of doc. 
`Object {status: 404, name: "not_found", message: "missing", error: true}`
I thought the temporary fix is to just purge that document and let it replicate from server but I don't seem to find a way to purge document. So, I tried db.remove, my doc revision id was 12-something and after db.remove it went to 10-something instead of 13-something but even after deleting I get the same issue and if I delete it this time , the rev id will be 14-something and the problem gets resolved.

**Comment by julianhille** [comment]
Package.json:
```
{
  "dependencies": {
    "express-pouchdb": "^4.0.0",
    "pouchdb": "^6.4.3"
  }
}
```

Create a file name `rev_undefined.js`


```
let PouchDB = require('pouchdb')
let express = require('express')
let fs = require('fs')
const dbPath = './databases/'
const localPort = 5100
const amountDBs = 10

const baseItem = {
	name: 'someName',
	aField: 123,
	type: 'item'
}
let baseItemID
let expressPouch = require('express-pouchdb')
let MyPouch = PouchDB.defaults({prefix: dbPath, adapter: 'leveldb', revs_limit: 5, auto_compaction: true, use_prefix: true})


async function conflictHandling(database, doc) {
	try {
		if (doc === null || doc.doc === undefined || doc.deleted) {
    		return
  		}
  		if (!doc.doc._conflicts || doc.doc.length === 0) {
    		return
  		}
		let conflictRevs = doc.doc._conflicts
  		let conflictingItems = [doc.doc]
    	for (let rev of conflictRevs) {
    	  conflictingItems.push(await database.get(doc.id, {rev: rev}))
    	}

    	let resolvedDoc = conflictingItems.shift()
    	for (let oldDoc of conflictingItems) {
		    await database.remove(oldDoc._id, oldDoc._rev)
    	}
    	resolvedDoc._rev = doc.doc._rev
    	delete resolvedDoc._conflicts
    	await database.put(resolvedDoc)
	} catch (error) {
		console.log('conflict solver issue', error)
	}
}


async function createDatabase (dbNumber) {
	let database = new MyPouch(`db${dbNumber}`)
	let info = await database.info()
	database.changes(
	{
		conflicts: true, 
		include_docs: true, 
		live: true
	}).on('change', conflictHandling.bind(undefined, database))
	return database
}


function createApp() {
	let app = express()
	let routeObject = expressPouch(MyPouch)
	app.use(`/`, routeObject)
	app.listen(5003)
	return app
}



async function syncAll (databases) {

	for(let srcIndex = 0; srcIndex < databases.length; srcIndex++) {
		let src = databases[srcIndex]
		for (let targetIndex = srcIndex + 1; targetIndex < databases.length; targetIndex++) {
			console.log(`Start sync DB${srcIndex + 1} with DB${targetIndex + 1}`)
			let target = new PouchDB(`http://localhost:5003/db${targetIndex}`)
			try {
				let result = await src.sync(target, {live: false, retry: false})
			} catch (error) {
				console.log('catch error', error)
			}
                         console.log(`Stop sync DB${srcIndex + 1} with DB${targetIndex + 1}`)
		}
	}
}

async function changeAll (databases) {
	for (let database of databases) {
		let item = await database.get(baseItemID)
		console.log('before', item)
		await database.put(item)
		console.log('after', item)
		item = await database.get(baseItemID)
	}
}

async function start() {
	if (!fs.existsSync(dbPath)) {
		fs.mkdirSync(dbPath)
	}
	createApp()
	let databases = []
	for (let i =0; i < amountDBs; i ++) {
		console.log(`Create DB ${i + 1}`)
		let database = await createDatabase(i)
		databases.push(database)
	}
	let result = await databases[0].post(baseItem)
	baseItemID = result.id
	
	for (let i = 0; i < 178; i++ ) {
		await syncAll(databases)
		await changeAll(databases)
	}
}

start()

```

Call:
`node rev_undefined.js`
This always triggers the issue. It feels like the conflict handler kills the sync ability as it seems it deletes the item while the other is syncing with it.

Maybe i'm holding it wrong.

**Comment by julianhille** [comment]
I guess i found my issue, the order of actions in a `changes` conflict handler is important.
One MUST update to the newest item, before deleting all other conflicts.
This seems to be obvious but i completely missed that point.
