### ISSUE TITLE
QuotaExceededError with pouchdb

### ISSUE THREAD

**Issue by louisdoe** [pouchdb/pouchdb#4531]
I have a similar error to this one : https://github.com/pouchdb/pouchdb/issues/4023

I get a strange 500 error, with my cloudant database.

```
POST https://louisromain.cloudant.com/boardline_users/_bulk_get?revs=true&attachments=true&_nonce=1446478625328 400 (Bad Request)
pouchdb.min.js:8 Database has a global failure DOMError {}message: ""name: "QuotaExceededError"__proto__: DOMErrora.8.G.onsuccess.H.onabort @ pouchdb.min.js:8
ionic.bundle.min.js:139 o {status: 500, name: "abort", message: "unknown", error: true, reason: "QuotaExceededError"}error: truemessage: "unknown"name: "abort"reason: "QuotaExceededError"result: Objectdoc_write_failures: 1docs_read: 1docs_written: 0end_time: Mon Nov 02 2015 16:37:05 GMT+0100 (CET)errors: Array[1]last_seq: "3478-g1AAAAFJeJzLYWBgYMlgTmGQT0lKzi9KdUhJMtXLSs1LLUst0kvOyS9NScwr0ctLLckBKmRKZEiy____f1YGUxIDA3N6LlCMPdXM1MzEMo1oM5IcgGRSPcKYcLAxKZYGlslpSajGmOA2Jo8FSDI0ACmgSftRXJSSamFoYWmOapQ5IaMOQIwCuooZZFQhxHPmJkCURtigLAAxFGUZ"ok: falsestart_time: Mon Nov 02 2015 16:36:59 GMT+0100 (CET)status: "aborting"__proto__: Objectstatus: 500__proto__: r(anonymous function) @ ionic.bundle.min.js:139b.$get @ ionic.bundle.min.js:111(anonymous function) @ ionic.bundle.min.js:151a.$get.n.$eval @ ionic.bundle.min.js:165a.$get.n.$digest @ ionic.bundle.min.js:163(anonymous function) @ ionic.bundle.min.js:166e @ ionic.bundle.min.js:74(anonymous function) @ ionic.bundle.min.js:76
11ionic.bundle.min.js:139 Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Error (native)
    at a.9.n.openTransactionSafely (http://localhost:8101/lib/pouchdb/dist/pouchdb.min.js:8:9233)
    at i.a.8.e._getLocal (http://localhost:8101/lib/pouchdb/dist/pouchdb.min.js:8:2521)
    at i.<anonymous> (http://localhost:8101/lib/pouchdb/dist/pouchdb.min.js:7:6737)
    at i.<anonymous> (http://localhost:8101/lib/pouchdb/dist/pouchdb.min.js:10:28092)
    at i.a.90.t.exports (http://localhost:8101/lib/pouchdb/dist/pouchdb.min.js:10:28931)
    at http://localhost:8101/lib/pouchdb/dist/pouchdb.min.js:9:28802
    at i.<anonymous> (http://localhost:8101/lib/pouchdb/dist/pouchdb.min.js:9:28722)
    at i.a.90.t.exports [as get] (http://localhost:8101/lib/pouchdb/dist/pouchdb.min.js:10:28931)
    at i.angular.module.constant.service.$q.qify [as get] (http://localhost:8101/lib/angular-pouchdb/angular-pouchdb.js:35:27)(anonymous function) @ ionic.bundle.min.js:139b.$get @ ionic.bundle.min.js:111(anonymous function) @ ionic.bundle.min.js:151a.$get.n.$eval @ ionic.bundle.min.js:165a.$get.n.$digest @ ionic.bundle.min.js:163(anonymous function) @ ionic.bundle.min.js:166e @ ionic.bundle.min.js:74(anonymous function) @ ionic.bundle.min.js:76
```

**Comment by daleharvey** [comment]
This is an error thrown by the local storage instance to say that you have hit the maximum quota of data you can store

**Comment by louisdoe** [comment]
Ok thanks a lot Dale !

2015-11-14 1:26 GMT+01:00 Dale Harvey <notifications@github.com>:
