### ISSUE TITLE
Destroying a db with http adapter is failing.

### ISSUE THREAD

**Issue by jerem** [pouchdb/pouchdb#4616]
With PouchDB 5.1.0, destroying a database using the http adaptor without passing any option fails with this message:

    Uncaught (in promise) TypeError: Cannot read property 'ajax' of undefined
        at ajax (http://localhost:8000/assets/vendor/pouchdb/dist/pouchdb.js:1066:27)
        at PouchDB.HttpPouch.api._destroy (http://localhost:8000/assets/vendor/pouchdb/dist/pouchdb.js:1855:5)
        at destroyDb (http://localhost:8000/assets/vendor/pouchdb/dist/pouchdb.js:864:10)
        at PouchDB.<anonymous> (http://localhost:8000/assets/vendor/pouchdb/dist/pouchdb.js:875:12)
        at PouchDB.<anonymous> (http://localhost:8000/assets/vendor/pouchdb/dist/pouchdb.js:5997:21)
        at PouchDB.<anonymous> (http://localhost:8000/assets/vendor/pouchdb/dist/pouchdb.js:11044:18)
        at http://localhost:8000/assets/vendor/pouchdb/dist/pouchdb.js:8253:21
        at PouchDB.<anonymous> (http://localhost:8000/assets/vendor/pouchdb/dist/pouchdb.js:8240:19)
        at PouchDB.destroy (http://localhost:8000/assets/vendor/pouchdb/dist/pouchdb.js:11044:18)
        at http://localhost:8000/services/Household.js:505:24

**Comment by nolanlawson** [comment]
See https://github.com/pouchdb/pouchdb/pull/4617#issuecomment-164207869
