### ISSUE TITLE
 test.changes.js-http Kill database while listening to live changes

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4677]

**Comment by daleharvey** [comment]
https://travis-ci.org/pouchdb/pouchdb/jobs/97945070

**Comment by daleharvey** [comment]
http adapter, complete isnt being called in some cases of the destroy path, looking now

**Comment by daleharvey** [comment]
I have no idea how this can fail, the changes object on setup adds the event listener for `destroyed` (https://github.com/pouchdb/pouchdb/blob/master/lib/changes.js#L46), this is during the constructor so there is no way it cannot be listening by the time the database gets destroyed, its also never reproduced locally

**Comment by daleharvey** [comment]
Added some debugging @ https://travis-ci.org/daleharvey/pouchdb/builds/98008401

**Comment by daleharvey** [comment]
omg 

```
  1) test.changes.js-http Kill database while listening to live changes:
     Error: Parse Error
      at onError (lib/deps/ajax/ajaxCore.js:52:18)
      at Request._callback (lib/deps/ajax/ajaxCore.js:90:14)
      at self.callback (node_modules/request/request.js:198:22)
      at Request.onRequestError (node_modules/request/request.js:820:8)
      at Socket.socketOnData (_http_client.js:322:9)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:540:20)
```

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/7ede502720dea30c87b02608c5710ec62698cf58
