### ISSUE TITLE
Node latest stable is permafail

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4694]
Something changed in the last 2 days, its completely broken

```Error: Cannot find module 'inherits'```

```
  1) test.all_docs.js-local Testing all docs:

     Uncaught expected [Error: Error: Could not locate the bindings file. Tried:

 → /home/travis/build/pouchdb/pouchdb/node_modules/leveldown/build/leveldown.node

 → /home/travis/build/pouchdb/pouchdb/node_modules/leveldown/build/Debug/leveldown.node

 → /home/travis/build/pouchdb/pouchdb/node_modules/leveldown/build/Release/leveldown.node

 → /home/travis/build/pouchdb/pouchdb/node_modules/leveldown/out/Debug/leveldown.node

 → /home/travis/build/pouchdb/pouchdb/node_modules/leveldown/Debug/leveldown.node

 → /home/travis/build/pouchdb/pouchdb/node_modules/leveldown/out/Release/leveldown.node

 → /home/travis/build/pouchdb/pouchdb/node_modules/leveldown/Release/leveldown.node

 → /home/travis/build/pouchdb/pouchdb/node_modules/leveldown/build/default/leveldown.node

 → /home/travis/build/pouchdb/pouchdb/node_modules/leveldown/compiled/5.3.0/linux/x64/leveldown.node: unable to import leveldown] to not exist

  AssertionError: expected [Error: Error: Could not locate the bindings file. Tried:

   → node_modules/leveldown/build/leveldown.node

   → node_modules/leveldown/build/Debug/leveldown.node

   → node_modules/leveldown/build/Release/leveldown.node

   → node_modules/leveldown/out/Debug/leveldown.node

   → node_modules/leveldown/Debug/leveldown.node

   → node_modules/leveldown/out/Release/leveldown.node

   → node_modules/leveldown/Release/leveldown.node

   → node_modules/leveldown/build/default/leveldown.node

   → node_modules/leveldown/compiled/5.3.0/linux/x64/leveldown.node: unable to import leveldown] to not exist

      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)

      at null.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:282:25)

      at Object.defineProperty.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:49:37)

      at Object.should.not.exist (node_modules/chai/lib/chai/interface/should.js:87:37)

      at tests/integration/test.all_docs.js:31:22

      at lib/deps/toPromise.js:23:11
```

**Comment by nolanlawson** [comment]
fixed by https://github.com/pouchdb/pouchdb/pull/4698
