### ISSUE TITLE
Wrong ELF class: ELFCLASS32 in Express

### ISSUE THREAD

**Issue by alexcheninfo** [pouchdb/pouchdb#4888]
This happened after integrating PouchDB with Express. This is my server.js file:

```
var express = require('express')
var PouchDB = require('pouchdb')
var webpack = require('webpack')
var config = require('./webpack.dev.conf')

var app = express()
var compiler = webpack(config)
var db = new PouchDB('vuedb')
var remotedb = new PouchDB('http://localhost:5984/vuedb')

// handle fallback for HTML5 history API
app.use(require('connect-history-api-fallback')())

// serve webpack bundle output
app.use(require('webpack-dev-middleware')(compiler, {
  publicPath: config.output.publicPath,
  stats: {
    colors: true,
    chunks: false
  }
}))

// enable hot-reload and state-preserving
// compilation error display
app.use(require('webpack-hot-middleware')(compiler))

function map (doc, emit) {
  if (doc.type === 'project') {
    emit(doc.createdAt)
  }
}

db.query(map, {include_docs: true}).then(function (projects) {
  console.log('PROJECTS', projects)
}).catch(function (err) {
  console.log(err)
})
```

`console.log('PROJECTS', projects)` outputs the following error:

`[Error: Error: /home/alex/node/project/node_modules/leveldown/build/Release/leveldown.node: wrong ELF class: ELFCLASS32: unable to import leveldown]`

I'm using "express": "^4.13.3", "pouchdb": "^5.2.1", and I'm using Ubuntu 15.10 on a 64bits machine.

What could be causing this?

_NOTE_: Strangely, it works okay if I use pouch on the client:

**index.js:**

```
import PouchDB from 'pouchdb'

const db = new PouchDB('vuedb')
const remotedb = new PouchDB('http://localhost:5984/vuedb')
const store = {}

store.findProjects = () => {
// Some code 
```

**Comment by nickcolley** [comment]
PouchDB uses leveldown as the adapter for NodeJS, that error message suggests the binary that npm has pulled down is 32bit not 64bit as your version of Ubuntu needs.

Leveldown is shipped with prebuilt binaries so you don't have to build them yourself, so you should be getting the 64bit version.

I'm not sure the solution at this time, you could try `npm cache clean` then `npm install` again.

**Comment by alexcheninfo** [comment]
@nickcolley Thanks for the reply. I'm running node v5.0.0 and npm 3.3.6.

I did npm cache clean and npm install and I got this:

```
alex@alex-M52AD-M12AD-A-F-K31AD:~/node/project$ npm install
npm WARN install Couldn't install optional dependency: Unsupported

> leveldown@1.4.4 install /home/alex/node/project/node_modules/leveldown
> prebuild --install

module.js:339
    throw err;
    ^

Error: Cannot find module './lib/utils'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/alex/node/project/node_modules/.bin/rc:2:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/alex/.nvm/versions/node/v5.0.0/bin/node" "/home/alex/.nvm/versions/node/v5.0.0/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! leveldown@1.4.4 install: `prebuild --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.4.4 install script 'prebuild --install'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/node/project/npm-debug.log
```

Seems like it's really a problem with `leveldown` not sure how to solve this, though.

**Comment by nickcolley** [comment]
Could you try `npm install leveldown --verbose`

This might give us a bit more detail to figure it out.

**Comment by alexcheninfo** [comment]
It's very long, ha:

```
alex@alex-M52AD-M12AD-A-F-K31AD:~/node/project$ npm install leveldown --verbose
npm info it worked if it ends with ok
npm verb cli [ '/home/alex/.nvm/versions/node/v5.0.0/bin/node',
npm verb cli   '/home/alex/.nvm/versions/node/v5.0.0/bin/npm',
npm verb cli   'install',
npm verb cli   'leveldown',
npm verb cli   '--verbose' ]
npm info using npm@3.3.6
npm info using node@v5.0.0
npm verb request uri https://registry.npmjs.org/leveldown
npm verb request no auth needed
npm info attempt registry request try #1 at 10:51:33 PM
npm verb request id 4c9833a26140e0af
npm http request GET https://registry.npmjs.org/leveldown
npm http 200 https://registry.npmjs.org/leveldown
npm verb headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
npm verb headers   etag: '"7YSZTQCNRZ0IO3O2GD2JW7X88"',
npm verb headers   'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '157978',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Sat, 13 Feb 2016 14:51:33 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '115',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-hkg6826-HKG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1455375093.542477,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb get saving leveldown to /home/alex/.npm/registry.npmjs.org/leveldown/.cache.json
npm verb cache add spec leveldown
npm verb addNamed "*" is a valid semver range for leveldown
npm verb addNameRange registry:https://registry.npmjs.org/leveldown not in flight; fetching
npm verb get https://registry.npmjs.org/leveldown not expired, no request
npm verb addNamed "1.4.4" is a plain semver version for leveldown
npm verb addRemoteTarball https://registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz',
npm verb addRemoteTarball   '5978b7b3e7ffa595b179391126035a9717ead765' ]
npm info retry fetch attempt 1 at 10:51:34 PM
npm info attempt registry request try #1 at 10:51:34 PM
npm http fetch GET https://registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz
npm http fetch 200 https://registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz
npm verb addTmpTarball /tmp/npm-8925-4472df33/registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for leveldown@1.4.4
npm verb afterAdd /home/alex/.npm/leveldown/1.4.4/package/package.json not in flight; writing
npm verb afterAdd /home/alex/.npm/leveldown/1.4.4/package/package.json written
npm verb request uri https://registry.npmjs.org/abstract-leveldown
npm verb request no auth needed
npm info attempt registry request try #1 at 10:51:36 PM
npm http request GET https://registry.npmjs.org/abstract-leveldown
npm http 200 https://registry.npmjs.org/abstract-leveldown
npm verb headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
npm verb headers   etag: '"49J8A8D38LQICSTNFEZX4KGQK"',
npm verb headers   'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '115916',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Sat, 13 Feb 2016 14:51:37 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-hkg6826-HKG',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1455375096.332348,VS0,VE1491',
npm verb headers   vary: 'Accept' }
npm verb get saving abstract-leveldown to /home/alex/.npm/registry.npmjs.org/abstract-leveldown/.cache.json
npm verb cache add spec abstract-leveldown@~2.4.0
npm verb addNamed ">=2.4.0 <2.5.0" is a valid semver range for abstract-leveldown
npm verb addNameRange registry:https://registry.npmjs.org/abstract-leveldown not in flight; fetching
npm verb get https://registry.npmjs.org/abstract-leveldown not expired, no request
npm verb addNamed "2.4.1" is a plain semver version for abstract-leveldown
npm verb addRemoteTarball https://registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz',
npm verb addRemoteTarball   'b3bfedb884eb693a12775f0c55e9f0a420ccee64' ]
npm info retry fetch attempt 1 at 10:51:38 PM
npm info attempt registry request try #1 at 10:51:38 PM
npm http fetch GET https://registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz
npm http fetch 200 https://registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz
npm verb addTmpTarball /tmp/npm-8925-4472df33/registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for abstract-leveldown@2.4.1
npm verb afterAdd /home/alex/.npm/abstract-leveldown/2.4.1/package/package.json not in flight; writing
npm verb afterAdd /home/alex/.npm/abstract-leveldown/2.4.1/package/package.json written
npm verb request uri https://registry.npmjs.org/fsevents
npm verb request no auth needed
npm info attempt registry request try #1 at 10:51:39 PM
npm verb etag "D9PC4PL08KP2KF4WZ96D0QN5T"
npm http request GET https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/fsevents
npm verb headers { date: 'Sat, 13 Feb 2016 14:51:39 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"D9PC4PL08KP2KF4WZ96D0QN5T"',
npm verb headers   age: '107',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-hkg6824-HKG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '5',
npm verb headers   'x-timer': 'S1455375099.244342,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb etag https://registry.npmjs.org/fsevents from cache
npm verb get saving fsevents to /home/alex/.npm/registry.npmjs.org/fsevents/.cache.json
npm WARN install Couldn't install optional dependency: Unsupported
npm verb install Error: Unsupported
npm verb install     at checkPlatform (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-install-checks/index.js:46:14)
npm verb install     at Array.<anonymous> (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm verb install     at LOOP (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm verb install     at /home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
npm verb install     at checkEngine (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-install-checks/index.js:25:10)
npm verb install     at Array.<anonymous> (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm verb install     at LOOP (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm verb install     at chain (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm verb install     at module.exports.isInstallable (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/install/validate-args.js:26:3)
npm verb install     at resolveWithNewModule (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/install/deps.js:408:12)
npm verb lock using /home/alex/.npm/_locks/staging-67c35ae24f3c6fda.lock for /home/alex/node/project/node_modules/.staging
npm verb unbuild node_modules/.staging/leveldown-ca7bc831b0c29a053aa2192192bd2681
npm verb gentlyRm don't care about contents; nuking /home/alex/node/project/node_modules/.staging/leveldown-ca7bc831b0c29a053aa2192192bd2681
npm verb tar unpack /home/alex/.npm/leveldown/1.4.4/package.tgz
npm verb tar unpacking to /home/alex/node/project/node_modules/.staging/leveldown-ca7bc831b0c29a053aa2192192bd2681
npm verb gentlyRm don't care about contents; nuking /home/alex/node/project/node_modules/.staging/leveldown-ca7bc831b0c29a053aa2192192bd2681
npm info lifecycle leveldown@1.4.4~preinstall: leveldown@1.4.4
npm info linkStuff leveldown@1.4.4
npm verb linkBins leveldown@1.4.4
npm verb linkMans leveldown@1.4.4
npm verb rebuildBundles leveldown@1.4.4
npm verb rebuildBundles [ 'abstract-leveldown' ]
npm info lifecycle leveldown@1.4.4~install: leveldown@1.4.4

> leveldown@1.4.4 install /home/alex/node/project/node_modules/leveldown
> prebuild --install

module.js:339
    throw err;
    ^

Error: Cannot find module './lib/utils'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/alex/node/project/node_modules/.bin/rc:2:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
npm verb lifecycle leveldown@1.4.4~install: unsafe-perm in lifecycle true
npm verb lifecycle leveldown@1.4.4~install: PATH: /home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin:/home/alex/node/project/node_modules/leveldown/node_modules/.bin:/home/alex/node/project/node_modules/.bin:/home/alex/mongodb/bin:/home/alex/.nvm/versions/node/v5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/alex/.fzf/bin
npm verb lifecycle leveldown@1.4.4~install: CWD: /home/alex/node/project/node_modules/leveldown
npm info lifecycle leveldown@1.4.4~install: Failed to exec install script
npm verb unlock done using /home/alex/.npm/_locks/staging-67c35ae24f3c6fda.lock for /home/alex/node/project/node_modules/.staging
npm verb stack Error: leveldown@1.4.4 install: `prebuild --install`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid leveldown@1.4.4
npm verb cwd /home/alex/node/project
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/alex/.nvm/versions/node/v5.0.0/bin/node" "/home/alex/.nvm/versions/node/v5.0.0/bin/npm" "install" "leveldown" "--verbose"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.4 install: `prebuild --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.4.4 install script 'prebuild --install'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/node/project/npm-debug.log
```

**Comment by nolanlawson** [comment]
Closing since we have identified this as a `leveldown` issue rather than a PouchDB issue. Your OS is unsupported:

> Error: Unsupported

As a workaround, you may try the `sqldown` adapter or really any other *down adapter: http://pouchdb.com/adapters.html#pouchdb_in_node_js

**Comment by marten-de-vries** [comment]
Worth noting, it is something in your setup: 64bit ubuntu 15.10 with a different (older) node + npm works fine here. The binary for the architecture does exist.

**Comment by alexcheninfo** [comment]
@nolanlawson Yes you can close this. Sorry, it was my fault. I somehow installed the 32 bit version of Leveldown in my 64 bit machine. I fixed this by wiping `~/.npm` and `node_modules` and installing everything from scratch.

(By the way, thanks for
