### ISSUE TITLE
Saving an object with a Circular reference

### ISSUE THREAD

**Issue by staxmanade** [pouchdb/pouchdb#4901]
It was initially difficult to tell what the problem was when I tried to save an object using PouchDB. Eventually found out that it had a circular reference.

I created the following plnkr sample: http://plnkr.co/edit/5f7m5g?p=preview

Also included a comment in #3635 where I originally found a related error.

Could this possibly be detected and a useful error message be thrown?

Current Error/stack
```
Unhandled promise rejection RangeError: Maximum call stack size exceeded
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2067:23)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2057:32)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2057:32)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2057:32)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
```

**Comment by nolanlawson** [comment]
I'm not sure there's any way we could solve this and give a more useful error to the user other than including our own cycle detection library, which would slow down PouchDB (due to needing to check every input object for cycles) as well as adding to the module size. I agree it's a confusing error, but I'm not sure there's much we can reasonably do here.
