### ISSUE TITLE
node leveldb pouch instance complains on changes

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb#5129]
```js
test('changes', (t) => {
  var p = new PouchDB(path.join(__dirname, './.test-db-dir/changesdb'))
  t.plan(1)
  p.changes().on('changed', (info) => {
    t.pass('info passed')
    t.end()
  })
  p.put({ _id: '123', dummy: 1 })
})
```

```
    var changeStream = stores.bySeqStore.readStream(streamOpts);
                                        ^

TypeError: Cannot read property 'readStream' of undefined
    at PouchDB.LevelPouch.api._changes (/Users/cdieringer/node/pouchy/node_modules/pouchdb/lib/index.js:7928:41)
    at Changes.doChanges (/Users/cdieringer/node/pouchy/node_modules/pouchdb/lib/index.js:843:28)
    at /Users/cdieringer/node/pouchy/node_modules/pouchdb/lib/index.js:745:14
    at TaskQueue.execute (/Users/cdieringer/node/pouchy/node_modules/pouchdb/lib/index.js:2210:7)
    at TaskQueue.fail (/Users/cdieringer/node/pouchy/node_modules/pouchdb/lib/index.js:2221:8)
    at /Users/cdieringer/node/pouchy/node_modules/pouchdb/lib/index.js:2382:24
    at /Users/cdieringer/node/pouchy/node_modules/pouchdb/lib/index.js:7086:16
    at dispatchError (/Users/cdieringer/node/pouchy/node_modules/pouchdb/node_modules/levelup/lib/util.js:64:35)
    at /Users/cdieringer/node/pouchy/node_modules/pouchdb/node_modules/levelup/lib/levelup.js:119:14
    at /Users/cdieringer/node/pouchy/node_modules/pouchdb/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

ref: https://github.com/cdaringe/pouchy/blob/master/test/index.js#L389

will look into more late, but figured y'all may have a hint-skie

**Comment by nolanlawson** [comment]
That's really weird. Never seen this bug before, no.

**Comment by cdaringe** [comment]
until i can provide a more concise and shareable example, closing. thx for the first pass though :) 👍

**Comment by nono** [comment]
@cdaringe hello, did you find what was the cause of this bug? I'm asking because a user of cozy-desktop, an application I develop, has exactly the same bug (https://github.com/cozy-labs/cozy-desktop/issues/355).

**Comment by cdaringe** [comment]
@nono, the good news is that the issue did get resolved. the bad news is that I wasn't able to root cause it. good luck! :)

**Comment by nono** [comment]
Thanks for the answer

**Comment by Robbert** [comment]
Had the same problem just now. Maybe it has something to do with creating a database from Node.js and a datase using `pouch-server` with the same name from the same working directory?
