### ISSUE TITLE
npm build failing

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5204]
After hitting https://github.com/pouchdb/pouchdb/issues/5203 I tried a manual rebuild, it started failing

```
~/src/pouchdb (master)$ npm run build

> pouchdb-monorepo@0.0.0 build /Users/daleharvey/src/pouchdb
> lerna bootstrap && npm run build-modules && npm run build-test

Lerna v2.0.0-beta.9
Linking all dependencies
Errored while running BootstrapCommand.execute
Error: Command failed: /bin/sh -c npm install js-extend@1.0.1 websql@0.4.4
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/daleharvey/.nvm/versions/node/v5.4.0/bin/node" "/Users/daleharvey/.nvm/versions/node/v5.4.0/bin/npm" "install" "js-extend@1.0.1" "websql@0.4.4"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! path /Users/daleharvey/src/pouchdb/packages/pouchdb-adapter-node-websql/node_modules/sqlite3/node_modules/mkdirp/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/daleharvey/src/pouchdb/packages/pouchdb-adapter-node-websql/node_modules/sqlite3/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daleharvey/src/pouchdb/packages/pouchdb-adapter-node-websql/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/daleharvey/.nvm/versions/node/v5.4.0/bin/node" "/Users/daleharvey/.nvm/versions/node/v5.4.0/bin/npm" "run" "build"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! pouchdb-monorepo@0.0.0 build: `lerna bootstrap && npm run build-modules && npm run build-test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pouchdb-monorepo@0.0.0 build script 'lerna bootstrap && npm run build-modules && npm run build-test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pouchdb-monorepo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap && npm run build-modules && npm run build-test
npm ERR! You can get their info via:
npm ERR!     npm owner ls pouchdb-monorepo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daleharvey/src/pouchdb/npm-debug.log
```

**Comment by nolanlawson** [comment]
This is an issue with `node-websql` and `sqlite3`. I dunno, in cases like this I usually just `rm -fr node_modules`, or in this case of our new arch, `rm -fr node_modules packages/*/node_modules`.

**Comment by nolanlawson** [comment]
You might also want to `npm install -g npm` just to be sure. I'm using 3.8.6.

**Comment by daleharvey** [comment]
hrm seems to have gone, will close for now, cheers

**Comment by daleharvey** [comment]
ok I am getting this again, there is one definite issue in that it seems to assume anything inside `packages` is a module https://gist.github.com/daleharvey/6a01d7ae673f77419c4eb484b4d6870c, but this is the 3rd time today I have had to wipe `node_modules` without any changes to the package so something is broken

**Comment by nolanlawson** [comment]
I see the issue. Somehow a `npm-debug.log`

**Comment by daleharvey** [comment]
yeh I had an `npm-debug.log` inside `packages`, deleting that got rid of that last error but I have still seen the first one a few times today

**Comment by nolanlawson** [comment]
yeah the real question is how that npm-debug.log got in there in the first place, and what caused the original error

**Comment by daleharvey** [comment]
oh the `npm-debug.log` was just there because I ran some npm command that failed from that directory, however yeh no idea what is causing the original error but I do know that I have seen it a few times after wiping node_modules

**Comment by daleharvey** [comment]
In terms of how `npm-debug.log` got in there, looks like it happens a lot, I just did `git clean -dfx` and got 

```
~/src/pouchdb (master)$ git clean -dfx
Removing docs/_site/
Removing docs/static/css/
Removing lerna-debug.log
Removing lib/
Removing node_modules/
Removing npm-debug.log
Removing packages/npm-debug.log
Removing packages/pouchdb-adapter-fruitdown/lib/
Removing packages/pouchdb-adapter-fruitdown/node_modules/
Removing packages/pouchdb-adapter-http/lib/
Removing packages/pouchdb-adapter-http/node_modules/
Removing packages/pouchdb-adapter-idb/
Removing packages/pouchdb-adapter-indexeddb/lib/
Removing packages/pouchdb-adapter-indexeddb/node_modules/
Removing packages/pouchdb-adapter-leveldb-core/lib/
Removing packages/pouchdb-adapter-leveldb-core/node_modules/
Removing packages/pouchdb-adapter-leveldb/lib/
Removing packages/pouchdb-adapter-leveldb/node_modules/
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.1bff9add4219cb8e0f375ec67fd1bb3c
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.1fa1f7c35fd318ce5e358cab62f1f549
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.5f158e16dadb8396c2185dac0462114c
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.786e004645ff2bcc466200b9e280df71
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.833f35b8bbe43c178cdb12d69810b1db
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.9ac6dc5279522dd633ac0b20d191196d
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.9e83c2f5e26e5bfb198f95956640e8e8
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.a0d0f2a4d689d8d6b7faadbac61fb453
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.afd595f02ae492281ade8a0a8490ab7b
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.cc542470d20773071ad0e0d30d3dbfdf
Removing packages/pouchdb-adapter-leveldb/npm-debug.log.cd97462b0b07cf1e3dfc8e3ddbea16bd
Removing packages/pouchdb-adapter-localstorage/lib/
Removing packages/pouchdb-adapter-localstorage/node_modules/
Removing packages/pouchdb-adapter-memory/lib/
Removing packages/pouchdb-adapter-memory/node_modules/
Removing packages/pouchdb-adapter-node-websql/lib/
Removing packages/pouchdb-adapter-node-websql/node_modules/
Removing packages/pouchdb-adapter-utils/lib/
Removing packages/pouchdb-adapter-utils/node_modules/
Removing packages/pouchdb-adapter-utils/npm-debug.log.31b81f23a6458042411e8818d636240a
Removing packages/pouchdb-adapter-websql-core/lib/
Removing packages/pouchdb-adapter-websql-core/node_modules/
Removing packages/pouchdb-adapter-websql-core/npm-debug.log.1372459f170f3ae3d14b28494db90e00
Removing packages/pouchdb-adapter-websql-core/npm-debug.log.1d52ca0a9943aa13d2591aad70d0edad
Removing packages/pouchdb-adapter-websql/lib/
Removing packages/pouchdb-adapter-websql/node_modules/
Removing packages/pouchdb-ajax/lib/
Removing packages/pouchdb-ajax/node_modules/
Removing packages/pouchdb-ajax/npm-debug.log.15624ca0726e05f2e9a856337897930a
Removing packages/pouchdb-ajax/npm-debug.log.2e26924d9dc7286b0c2d103dffa68a45
Removing packages/pouchdb-ajax/npm-debug.log.4aa88b948560397dd6c14fca11b29885
Removing packages/pouchdb-ajax/npm-debug.log.821938adfff584353a4ce6dd54253047
Removing packages/pouchdb-ajax/npm-debug.log.b52ea528ed8f2f0432b0457458d24147
Removing packages/pouchdb-ajax/npm-debug.log.d03eca091865c40f1e34fea5779862ce
Removing packages/pouchdb-ajax/npm-debug.log.e6552632e0f381944ca83a415aee0d2f
Removing packages/pouchdb-binary-utils/lib/
Removing packages/pouchdb-binary-utils/node_modules/
Removing packages/pouchdb-browser/lib/
Removing packages/pouchdb-browser/node_modules/
Removing packages/pouchdb-checkpointer/lib/
Removing packages/pouchdb-checkpointer/node_modules/
Removing packages/pouchdb-core/lib/
Removing packages/pouchdb-core/node_modules/
Removing packages/pouchdb-errors/lib/
Removing packages/pouchdb-errors/node_modules/
Removing packages/pouchdb-for-coverage/lib/
Removing packages/pouchdb-for-coverage/node_modules/
Removing packages/pouchdb-for-coverage/npm-debug.log.e4f0036563e040c47f556085c829fce9
Removing packages/pouchdb-for-coverage/npm-debug.log.f477ee655755d80e6b48b5c5a86016a8
Removing packages/pouchdb-generate-replication-id/lib/
Removing packages/pouchdb-generate-replication-id/node_modules/
Removing packages/pouchdb-http/lib/
Removing packages/pouchdb-http/node_modules/
Removing packages/pouchdb-json/lib/
Removing packages/pouchdb-json/node_modules/
Removing packages/pouchdb-json/npm-debug.log.e4cb01201a53a4ed6a2f751e806bda0b
Removing packages/pouchdb-mapreduce-utils/lib/
Removing packages/pouchdb-mapreduce-utils/node_modules/
Removing packages/pouchdb-mapreduce/lib/
Removing packages/pouchdb-mapreduce/node_modules/
Removing packages/pouchdb-md5/lib/
Removing packages/pouchdb-md5/node_modules/
Removing packages/pouchdb-merge/lib/
Removing packages/pouchdb-merge/node_modules/
Removing packages/pouchdb-next/
Removing packages/pouchdb-node/lib/
Removing packages/pouchdb-node/node_modules/
Removing packages/pouchdb-promise/lib/
Removing packages/pouchdb-promise/node_modules/
Removing packages/pouchdb-promise/npm-debug.log.b1d7b39a1ccd2e0bd5efae8a44c13a8d
Removing packages/pouchdb-replication/lib/
Removing packages/pouchdb-replication/node_modules/
Removing packages/pouchdb-replication/npm-debug.log.682a19d370719aabb1b2f7e6961cc7e3
Removing packages/pouchdb-utils/lib/
Removing packages/pouchdb-utils/node_modules/
Removing packages/pouchdb/dist/
Removing packages/pouchdb/lib/
Removing packages/pouchdb/node_modules/
Removing packages/pouchdb/npm-debug.log.04dfdec4155efe1fcd8174c90f8bc1df
Removing packages/pouchdb/npm-debug.log.06756fe4be919ff34b9ac9d453fe4573
Removing packages/pouchdb/npm-debug.log.49c0561bf18da1f1176bb60309ef0140
Removing packages/pouchdb/npm-debug.log.9023c232f3e5765f8b957bcdba121575
Removing packages/pouchdb/npm-debug.log.912a664476ca6e032a4e4c85596c22de
Removing packages/pouchdb/npm-debug.log.adfa885b2787025dcb9e1c36fc028093
Removing packages/pouchdb/npm-debug.log.b184db7e3270be1f1356f782151c0dcd
Removing packages/pouchdb/npm-debug.log.cbd356d40a0e60f5d25dcbbd0342d1c2
Removing packages/pouchdb/npm-debug.log.d90c005beb4203d5ecc8e8d3ccff880f
Removing packages/pouchdb/npm-debug.log.d99e0f8dca456bd93e703a3ec72e18aa
Removing tests/integration/utils-bundle.js
Removing tests/performance-bundle.js
```

**Comment by daleharvey** [comment]
actually none of those are in the top level, that must have been when I was running things from inside `packages`

**Comment by daleharvey** [comment]
but yeh, this error has starting happening to me all the time now, I suspect that the websql install is fragile and `lerna` does something that either races, or if something fails it leaves it in a permanently broken state

**Comment by daleharvey** [comment]
ok so I give up, I must have been doing something really weird with my `idb` patch previously because I havent seen this in a while now
