### ISSUE TITLE
I'm trying migrate my local data for remote database

### ISSUE THREAD

**Issue by gpaixao** [pouchdb/pouchdb#5769]
### Issue
I'm trying migrate my local data for remote database

### Info
- Environment: Node.js
- Server: MongoDB

### Code
```javascript
const PouchDB = require('pouchdb');
const db = new PouchDB('my_database');

db.replicate.from("http://localhost:27017/mydb", {
    live: true
})
.then(r => {
    console.log("Result");
    console.log(r);
})
.catch(e => {
    console.log("Error");
    console.log(e);
});
```

### Stdout
```bash
Error
{ SyntaxError: Unexpected token I in JSON at position 0
    at Object.parse (native)
    at onSuccess (/Users/guilhermepaixao/Projects/src/github.com/gpaixao/learnPouchDB/node_modules/pouchdb/lib/index.js:5400:20)
    at Request._callback (/Users/guilhermepaixao/Projects/src/github.com/gpaixao/learnPouchDB/node_modules/pouchdb/lib/index.js:5460:7)
    at Request.self.callback (/Users/guilhermepaixao/Projects/src/github.com/gpaixao/learnPouchDB/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/guilhermepaixao/Projects/src/github.com/gpaixao/learnPouchDB/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/guilhermepaixao/Projects/src/github.com/gpaixao/learnPouchDB/node_modules/request/request.js:965:12)
  result: 
   { ok: false,
     start_time: 2016-10-12T06:35:23.589Z,
     docs_read: 0,
     docs_written: 0,
     doc_write_failures: 0,
     errors: [],
     status: 'aborting',
     end_time: 2016-10-12T06:35:23.629Z,
     last_seq: 0 } }
```

**Comment by daleharvey** [comment]
You say the server is MongoDB? PouchDB cannot replicate from MongoDB, it needs a server that speaks the couchdb replication protocol
