### ISSUE TITLE
/dbs/<db_name>/_changes: limit parameter accepts negative values and crashes the server

### ISSUE THREAD

**Issue by bjendyk** [pouchdb/pouchdb#5808]
### Issue
When calling the _changes API, if a negative value is passed to limit parameter in query string (e.g. ?limit=-20) it will crash the server.

### Info
- Environment: Node.js 5.10.1, Chrome, Safari
- Adapter: IndexedDB, WebSQL, LevelDB
- Server based on express-pouchdb v.1.0.7

### Reproduce
Make a GET request to /dbs/<db_name>/_changes?limit=-20

Stack trace:

Application has thrown an uncaught exception and is terminated:
RangeError: Invalid array length
    at DestroyableTransform._flush (D:\home\site\wwwroot\node_modules\pouchdb\lib\index.js:4948:26)
    at DestroyableTransform.<anonymous> (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at prefinish (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:465:12)
    at finishMaybe (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:473:7)
    at endWritable (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:455:41)
    at ReadStream.onend (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at ReadStream.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at ReadStream.emit (events.js:179:7)
    at D:\home\site\wwwroot\node_modules\pouchdb\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)

**Comment by mohlsen** [comment]
Obviously this is not a normal condition (should never happen with real usage), but a malicious user could use this.

**Comment by nolanlawson** [comment]
This is a bug in express-pouchdb not pouchdb, but good find! We should fix this. :)

**Comment by nolanlawson** [comment]
closing in favor of https://github.com/pouchdb/express-pouchdb/issues/394
