### ISSUE TITLE
Maximum callstack 

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#6145]
When replicating from a CouchDB 1.6.1 instance to PouchDB I get the following error:

```js
RangeError: Maximum call stack size exceeded
    at Array.sort (native)
    at doMerge (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-merge/lib/index.js:306:11)
    at Object.merge (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-merge/lib/index.js:358:17)
    at updateDoc (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-utils/lib/index.js:288:29)
    at nextDoc (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-utils/lib/index.js:414:9)
    at docWritten (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-utils/lib/index.js:403:9)
    at finish (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:755:9)
    at writeDoc (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:759:9)
    at updateDoc (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-utils/lib/index.js:326:3)
    at nextDoc (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-utils/lib/index.js:414:9)
    at docWritten (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-utils/lib/index.js:403:9)
    at finish (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:755:9)
    at writeDoc (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:759:9)
    at updateDoc (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-utils/lib/index.js:326:3)
    at nextDoc (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-utils/lib/index.js:414:9)
    at docWritten (/Users/ronagy/.nvm/versions/node/v7.0.0/lib/node_modules/pouchdb-server/node_modules/pouchdb-adapter-utils/lib/index.js:403:9)
```

**Comment by nolanlawson** [comment]
Which device? Which browser? Which PouchDB version? Looks like you may be using pouchdb-server; which adapter?

Also a repro would be very helpful.

**Comment by nolanlawson** [comment]
Based on your stacktrace, it seems the line that's throwing is probably [this one](https://github.com/pouchdb/pouchdb/blob/2cdbecd10f71e763001805f87d1d62723e95ac73/packages/node_modules/pouchdb-merge/src/merge.js#L177). This might be hit if you have very large documents with lots and lots of revisions. Have you increased the revs_limit beyond the default of 1000?

**Comment by ronag** [comment]
Latest pouchdb-server and I have not modified the revs_limit.

**Comment by nolanlawson** [comment]
We'd need a reproducible test case to solve this issue, thanks!
