### ISSUE TITLE
pouchdb http uses all available sockets on node.js

### ISSUE THREAD

**Issue by jefbarn** [pouchdb/pouchdb#6210]
### Issue
Have a project that is using Pouchdb on node as an http driver. Just noticed that it is eating up all the sockets (10s of thousands) instead of pooling.
Wondering, is this a bug or is there some setting for connection pooling on node that I'm missing?

Edit: 
also set
```
require('http').globalAgent.maxSockets = 100
```
and
```
export let couch = new PouchDB(couchHost, {
  ajax: {
    pool: {
      maxSockets: 100
    }
  }
})
```
neither helped

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
Node.js 7.5.0 (latest) on Windows
Edit: Tried rolling back to Node 6.9.5 and Pouch 6.0.6, no help.
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
Windows
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
http
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)
Couchdb 2.0.0

### Reproduce
Stream of updates to 10s of thousands of documents.

```
dbadapter: START: The operation completed successfully.

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
1417

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
2834

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
4042

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
4830

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
5759

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
6422

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
6980

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
7588

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
8323

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
8832

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
9507

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
9970

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
10599

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
10807

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
10836

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
11319

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
11890

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
12517

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
12812

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
13127

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
13250

C:\projects\dbadapter>netstat -a -n | find /c "127.0.0.1:5984"
13250
```

Eventually ending in...

```
[Mon Feb 06 2017 11:46:19] [WARN]  upsert error retrieving old doc 1 500 { Error: connect EADDRINUSE 127.0.0.1:5984
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5984,
  status: 500 } equipment:347
```

**Comment by jefbarn** [comment]
Found the magic sauce, need to set keepAlive to true so that sockets get reused...
```
export let couch = new PouchDB(couchHost, {
  ajax: {
    agent: new http.Agent({
      keepAlive: true,
      maxSockets: 25
    })
  }
})
```
