### ISSUE TITLE
"TypeError: Cannot convert undefined or null to object" when adding sort

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6254]
_From @josh-m-sharpe on February 14, 2017 2:26_

Pretty hacky example I came across as I was learning pouch-db.  This only started happening after I added the 'sort' attr.  I added the ['pinned', 'starts_at'] in order to accomodate the sort options per the sort syntax docs https://docs.cloudant.com/cloudant_query.html#sort-syntax

```
    var oneDayAgo = new Date();
    var oneDayAgoStr = (new Date(oneDayAgo.setDate(oneDayAgo.getDate() - 1))).toISOString();

    let _db = new PouchDB('events_current', {adapter: 'idb'});

    _db.createIndex({
      index: {
        fields: ['pinned', 'starts_at']
      }
    }).then(() => {
      _db.createIndex({
        index: {
          fields: ['starts_at']
        }
      }).then(() => {
        _db.find({
          selector: {
            starts_at: {$gte: oneDayAgoStr}
          },
          sort: [{pinned: 'desc'}, {starts_at: 'asc'}]
        }).then((_events) => {
          console.log(_events);
        });
      });
    });




EXCEPTION: Uncaught (in promise): TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getKey (http://localhost:8100/build/main.js:15692:17)
    at userOperatorLosesPrecision (http://localhost:8100/build/main.js:115859:22)
    at getBasicInMemoryFields (http://localhost:8100/build/main.js:115894:24)
    at getInMemoryFields (http://localhost:8100/build/main.js:115919:5)
    at planQuery (http://localhost:8100/build/main.js:116258:24)
    at http://localhost:8100/build/main.js:115741:21
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9094)
    at Object.onInvoke (http://localhost:8100/build/main.js:37088:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9045)
    at e.run (http://localhost:8100/build/polyfills.js:3:6481)
    at http://localhost:8100/build/polyfills.js:3:4583
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:37079:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7083)
    at i (http://localhost:8100/build/polyfills.js:3:3671)
    at IDBTransaction.invoke (http://localhost:8100/build/polyfills.js:3:10876)
```

_Copied from original issue: nolanlawson/pouchdb-find#253_

**Comment by nolanlawson** [comment]
_From @garrensmith on February 15, 2017 11:44_

Thanks @josh-m-sharpe this is a bug in the sense we should give you a better warning. You cannot sort on two rows in different directions ` sort: [{pinned: 'desc'}, {starts_at: 'asc'}]`. You need to change that to ` sort: [{pinned: 'desc'}, {starts_at: 'desc'}]` or  sort: [{pinned: 'asc'}, {starts_at: 'asc'}]

**Comment by nolanlawson** [comment]
Agreed, we should have a better error message.

**Comment by ednsinf** [comment]
This error persists:
Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
[...]pouchdb-find\lib\index.js:1245:21
