### ISSUE TITLE
I can't seem to use $nin right

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6280]
_From @megaed on January 3, 2016 12:10_

``` js
db.createIndex({
            index: {
                fields: ['lastName','absents','year','type'],
                name: 'myIndex',
                ddoc: 'myIndex'
            }
     })
    });
```

---

``` js
var date = '10/10/15'
 db.find({
    selector: {
        lastName: {$gt: null},
        year: {$gt: null},
        type: 'something',
        absents: {
            $nin: [date]
        }
    },
```

---

What im trying to do is get a list of results where the specfied date is not found.

Since im trying to check absences.. I want to get a list of results where the current date is not found. 

So that i can check who are not currently absent.

I thought of using $nin since that seemed to be able to check arrays.. but im getting this error whenever I execute the db.find command.

```
TypeError: Cannot use 'in' operator to search for 'startkey' in undefined
    at m (http://127.0.0.1:52906/js/pouchdb.find.min.js:1:22127)
    at b (http://127.0.0.1:52906/js/pouchdb.find.min.js:1:22468)
    at k (http://127.0.0.1:52906/js/pouchdb.find.min.js:1:22979)
    at http://127.0.0.1:52906/js/pouchdb.find.min.js:1:18535
```

What am I doing wrong? I'm not really sure if I should put this issue here but I don't know where else to ask questions.

I apologize in advance.

_Copied from original issue: nolanlawson/pouchdb-find#140_

**Comment by nolanlawson** [comment]
_From @megaed on January 3, 2016 17:9_

I got it to work but it's definitely a strange behavior.

It only started working after I added _id as a criteria.. 

by adding "_id: {$gt: null}"  as a selector it suddenly started working and it only works with the $gt operator it doesn't work with $exists: true.. which I find quite strange since $gt: null should be equal to $exists.. atleast that's what I believe..

none of my selectors work with $exists: true but whenever I add in the "_id: {$gt: null}" in the first criteria of my selector $exists:true starts working for all the other criteria..

Also I noticed that if I add "type" in my selector I get the TYPE ERROR msg that I posted earlier after removing it , everything started to work.

I'm not really sure if that's an abnormal behavior or I'm just not used to this plugin.

Still a very useful plugin though.

**Comment by nolanlawson** [comment]
> $gt: null should be equal to $exists

Yes, this  has been covered in #138. It's very counter-intuitive. :(

Adding _id: {$gt: null} is probably only fixing your issue because it chooses the built-in `allDocs()` index, and then does your entire query in-memory, which is probably not what you want.

I think the fix is that you need to remove `absents` from your index, because since you're using `$nin`, it's not going to be using the index for it at all.

However, the fact that it throws an error is less than optimal, so I'll keep this issue open.

**Comment by nolanlawson** [comment]
_From @megaed on January 4, 2016 9:37_

Removing absents from my index did the trick. I was able to retrieve the data from pouchdb without adding _id as a selector.
but using $exists: true still doesn't work so I decided to go with $gt: null.

You raised some good points in #138. Great job maintaining this plugin. It really does make querying in pouch easier.
