### ISSUE TITLE
$ne not working on $or

### ISSUE THREAD

**Issue by CarlosAyala** [pouchdb/pouchdb#6403]
### Issue

The following error appears when using $ne

```
Error: Uncaught (in promise): TypeError: userValue.every is not a function
TypeError: userValue.every is not a function
    at Object.$ne (http://localhost:8100/build/main.js:186608:22)
    at match (http://localhost:8100/build/main.js:186471:32)
    at http://localhost:8100/build/main.js:186442:12
    at Array.every (native)
    at matchSelector (http://localhost:8100/build/main.js:186440:31)
    at http://localhost:8100/build/main.js:186426:12
    at Array.every (native)
    at rowFilter (http://localhost:8100/build/main.js:186414:25)
    at http://localhost:8100/build/main.js:186450:14
    at Array.some (native)
    at matchCominationalSelector (http://localhost:8100/build/main.js:186449:20)
    at http://localhost:8100/build/main.js:186423:14
    at Array.every (native)
    at rowFilter (http://localhost:8100/build/main.js:186414:25)
    at http://localhost:8100/build/main.js:186391:12
    at v (http://localhost:8100/build/polyfills.js:3:4864)
    at s (http://localhost:8100/build/polyfills.js:3:4289)
    at s (http://localhost:8100/build/polyfills.js:3:4112)
    at http://localhost:8100/build/polyfills.js:3:4652
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10284)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:54857:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10220)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7637)
    at i (http://localhost:8100/build/polyfills.js:3:3707)
    at invoke (http://localhost:8100/build/polyfills.js:3:11437)
    at e.args.(anonymous function) (http://localhost:8100/build/polyfills.js:2:30193)
```

### Info
- Environment: Ionic Framework 2
- Platform: All
- Adapter: WebSQL
- Server:  None

### Reproduce
```
return this._db.find({
            selector: {
                id_presentation_frontend: presentation,
                $or: [
                    //Todos los no linkeados
                    { linked : { $exists : false } },
                    //Los linkeados menos los legales
                    { linked_type : { $ne : 'legal' } },
                ],
                deleted: { 
                    $exists : false
                }
            }
        });
```

**Comment by CarlosAyala** [comment]
If I change the query to:

```
return this._db.find({
            selector: {
                id_presentation_frontend: presentation,
                $or: [
                    //Todos los no linkeados
                    { linked : { $exists : false } },
                    //Los linkeados menos los legales
                    { linked_type : { $nin  : ['legal'] } },
                ],
                deleted: { 
                    $exists : false
                }
            }
        });
```


It works well
