### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by semiautomatix** [pouchdb/pouchdb#6432]
Good day, I've downloaded the latest source and am attempting to build. Unfortunately I'm receiving and error on the pouchdb-find module:

```
git clone https://github.com/pouchdb/pouchdb.git
cd pouchdb
npm install
```

```
build error
Error: Could not resolve './create-index' from packages\node_modules\pouchdb-find\src\adapters\local\index.js
    at error (E:\tim\React Projects\pouchdb\node_modules\rollup\dist\rollup.js:170:12)
    at E:\tim\React Projects\pouchdb\node_modules\rollup\dist\rollup.js:9534:7
    at Array.<anonymous> (E:\tim\React Projects\pouchdb\node_modules\lie\lib\index.js:88:21)
    at nextTick (E:\tim\React Projects\pouchdb\node_modules\immediate\lib\index.js:61:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

All files seem to be in place, so this is a bit strange.

**Comment by semiautomatix** [comment]
Note: I haven't attempted a build with the final 6.2.0 update.
