### ISSUE TITLE
Changes feed live doesn't work for remote PouchDB

### ISSUE THREAD

**Issue by FelipeTaiarol** [pouchdb/pouchdb#6491]
### Issue
Changes feed only runs once even though 'live' option is set.

### Info
- Environment: Browser
- Platform: Chrome latest
- Server: CouchDB 2.0 behind NGINX
- PouchDB: 6.2.0 

### Reproduce

```javascript
var db = new PouchDB(url);

localDB.changes({
   since: 'now',
   include_docs: true,
   live: true
})
```

This triggers an http request which runs for 30s until it times out and then nothing happens.  

/_changes?timeout=25000&include_docs=true&feed=longpoll&heartbeat=10000&since=1281-g1AAAAEzeJzLYWBg4MhgTmHgzcvPy09JdcjLz8gvLskBCjMlMiTJ____PytxOQ4FSQpAMskerGY9LjUOIDXxYDW9uNQkgNTUg9UsxKEmjwVIMjQAKaCy-VmJ8_GqWwBRtz8rcQledQcg6u5nJc7Dq-4BRB3QfXOyAEc5Z_c&limit=25

This works when I am listening to a local PouchDB which is being synced with a remote one. If I listen to the remote directly it doesn't work.

**Comment by willholley** [comment]
@FelipeTaiarol does it work without nginx in the middle?

**Comment by FelipeTaiarol** [comment]
@willholley , same problem with and without nginx.

**Comment by willholley** [comment]
@FelipeTaiarol does [PouchDB debug mode](https://pouchdb.com/api.html#debug_mode) give you a clue as to what's happening? I'd basically expect the `_changes` feed to run for 25 seconds before timing out, at which point Pouch should create a new `_changes` request.

**Comment by FelipeTaiarol** [comment]
pouchdb:http GET +6ms https://db-staging.ruumapp.com/ruum_1495096285067oyhzf7lq08nwwf4hkhrq/_chan…r2Uh1WeWpkaJaZA_Yj2Ul5WeWtl3v6FQsFcb2KVj1XMXTyjFCGNaZh1d6ovOOOoqg&limit=25

**Comment by FelipeTaiarol** [comment]
@willholley , I turned debug mode on but it didn't really help. I see this:

pouchdb:http GET +6ms https://MY_DATABASE/_changes?timeout=25000&include_docs=true&feed=longpoll&heartbeat=10000&since=170-g1AAAAIjeJyV0TsOgkAQBuCNmmhDYeGjMXoEWNCFSm6iMyyEENwttNeb6E30JnoT3AeNJCZL808ymfmKmZoQMimHnHhCCsnzVMhSni-1ag-A4LppmqocwuKkGuMgSDKW8e7wn3XcqMR9K8yMkDBGkQWuQqqFw4_g58BZAa7CUQvXVlhZIdkCxDtHQYxUkpsqCrlrZWmUnCMgRr2Uh1WeWpkaJaZA_Yj2Ul5WeWtl3v6FQsFcb2KVj1XMXTyjFCGNaZh1d6ovOOOoqg&limit=25

which is the connection to the changes feed, that runs for 30s until it times out and then nothing happens, no extra log is outputted either. 

![image](https://cloud.githubusercontent.com/assets/859559/26195247/6ba922f2-3bbb-11e7-89ba-e63419afc1f8.png)

**Comment by FelipeTaiarol** [comment]
[changes feed bug.zip](https://github.com/pouchdb/pouchdb/files/1276615/changes.feed.bug.zip)

@willholley ,follow attached a way to reproduce the issue with CouchDB 2.0 running on localhost. I also attached my CouchDB config file.

**Comment by willholley** [comment]
@FelipeTaiarol can you try using PouchDB 6.3.4? We fixed a few timing issues with `_changes` in that release.

**Comment by FelipeTaiarol** [comment]
@willholley , I tried with 6.3.4, same problem. The zip I attached in my previous comment has the code to reproduce the issue.

**Comment by big-r81** [comment]
Hi,

i want to listen to remote db changes and i get the following error after 30 seconds:
```
Error in remote changes feed  Error: ETIMEDOUT
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:8100/build/vendor.js:121925:15)
    at XMLHttpRequest.H (http://localhost:8100/build/polyfills.js:3:23950)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4970:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16794)
    at p (http://localhost:8100/build/polyfills.js:2:27648)
    at XMLHttpRequest.v (http://localhost:8100/build/polyfills.js:2:27893)
    at e.l [as cancelFn] (http://localhost:8100/build/polyfills.js:3:30767)
    at t.cancelTask (http://localhost:8100/build/polyfills.js:3:15884)
    at Object.onCancelTask (http://localhost:8100/build/polyfills.js:3:12694)
    at t.cancelTask (http://localhost:8100/build/polyfills.js:3:15758)
    at r.cancelTask (http://localhost:8100/build/polyfills.js:3:12115)
    at http://localhost:8100/build/polyfills.js:3:31556
    at XMLHttpRequest.o.(anonymous function) [as abort] (http://localhost:8100/build/polyfills.js:2:26580)
    at timeoutReq (http://localhost:8100/build/vendor.js:121829:9)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4970:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at e.invokeTask (http://localhost:8100/build/polyfills.js:3:16794)
    at i.isUsingGlobalCallback.invoke (http://localhost:8100/build/polyfills.js:3:16682)
    at n (http://localhost:8100/build/polyfills.js:3:61)
```

This is the coresponding code:
```
private registerRemoteDbCallbacks() {
    let remote = this.db.getRemoteDbObject();
    this.changes = remote.changes({
      since: 'now',
      live: true,
      include_docs: true
    })
      .on('change', this.logDatabaseChangestoConsole)
      .on('error', function (err) {
        console.log("Error in remote changes feed ", err);
      });
  }

  private logDatabaseChangestoConsole(data) {
    console.log("Changes in remote DB...");
    console.log(data);
  }
```

**Comment by big-r81** [comment]
Ok,

i found this thread #6431.
I'm using nginx as proxy and it works now!
I added only the following option to the configuration of nginx:
```
proxy_buffering off;
```
