### ISSUE TITLE
TypeError: requestsById[request.id].push is not a function

### ISSUE THREAD

**Issue by gabrielcsapo** [pouchdb/pouchdb#6514]
### Issue

The issue exists when trying to push to `requestsById[request.id]` resulting in `TypeError:` requestsById[request.id].push is not a function`

### Info
- Environment: Node.js
- Platform: OSX
- Adapter: LevelDB
- Server: PouchDB Server

### Reproduce

Cross posting the issue from `local-npm`

https://github.com/local-npm/local-npm/issues/131

```
I understand this project is no longer actively maintained. I'm just posting this bug report here in case any other users of this project might be able to suggest a fix. :)

I installed and ran local-npm yesterday and it worked fine. Then this morning when I tried to launch it I got this error message:

```
~/programs/local-npm > local-npm

Welcome!
To start using local-npm, just run: 

  $ npm set registry http://127.0.0.1:5080

To switch back, you can run: 

  $ npm set registry https://registry.npmjs.org

A simple npm-like UI is available here: http://127.0.0.1:5080/_browse

PouchDB Server listening on port 16984.
Navigate to http://localhost:16984/_utils for the Fauxton UI.

/usr/lib/node_modules/local-npm/node_modules/pouchdb/lib/index.js:247
      requestsById[request.id].push(request);
                               ^

TypeError:` requestsById[request.id].push is not a function
    at /usr/lib/node_modules/local-npm/node_modules/pouchdb/lib/index.js:247:32
    at Array.forEach (native)
    at bulkGet (/usr/lib/node_modules/local-npm/node_modules/pouchdb/lib/index.js:245:12)
    at doBulkGetShim (/usr/lib/node_modules/local-npm/node_modules/pouchdb/lib/index.js:5438:9)
    at /usr/lib/node_modules/local-npm/node_modules/pouchdb/lib/index.js:5460:13
    at Request._callback (/usr/lib/node_modules/local-npm/node_modules/pouchdb/lib/index.js:5128:7)
    at Request.self.callback (/usr/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

npm: 2.15.9
node: 4.6.1
local-npm: 1.6.0

From the stack it looks like it's an issue relating to pouchdb. The version of pouchdb I've got installed under local-npm, is 5.4.5

```
> npm -g ls pouchdb
/usr/lib
└─┬ local-npm@1.6.0
  └── pouchdb@5.4.5 
```

**Comment by willholley** [comment]
@gabrielcsapo that's quite an old version of pouchdb - is the issue fixed if you update to the latest version?

**Comment by gabrielcsapo** [comment]
@willholley let me update and get back to you, thanks for the response!

**Comment by gabrielcsapo** [comment]
looks like the issue no longer persists when I upgrade! Thanks @willholley!
