### ISSUE TITLE
Missing dependencies in 6.3.0 - cannot find module clone-buffer

### ISSUE THREAD

**Issue by p-thorpe** [pouchdb/pouchdb#6600]
I see the following error using `pouchdb@6.3.0`:

```
Error: Cannot find module 'clone-buffer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...node_modules\pouchdb\lib\index.js:7:35)
```

Looking in https://github.com/pouchdb/pouchdb/archive/6.3.0.zip, it appears that `6.3.0` is missing a dependencies section in `package.json`?

**Comment by jure** [comment]
Yeah there's a bunch of similar issues. Our CI started failing with:

```
    Cannot find module 'pouchdb-utils' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/pouchdb-core/lib/index.js:5:20)
```

Looks like the thing that determines dependencies at publish-time has broken somehow.

**Comment by jure** [comment]
Even locking to 6.2.0 doesn't help...
```
    Cannot find module 'pouchdb-adapter-leveldb-core' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/pouchdb-adapter-memory/lib/index.js:6:38)
```

**Comment by p-thorpe** [comment]
Locking the following to `6.2.0` worked for us:
```
    "pouchdb": "6.2.0",
    "pouchdb-adapter-memory": "6.2.0",
    "pouchdb-core": "6.2.0"
```

**Comment by daleharvey** [comment]
Fixed by 6.3.2

**Comment by willholley** [comment]
Apologies for the botched release - 6.3.2 should fix the issues.

**Comment by p-thorpe** [comment]
np, thanks for the speedy turn-around!
I do see one further error @`6.3.2`:

```
Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...\node_modules\pouchdb-utils\lib\index.js:14:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...\node_modules\pouchdb-adapter-memory\lib\index.js:5:20)
```

Would you prefer a separate issue for this?

**Comment by willholley** [comment]
thanks @p-thorpe - can you open a new issue please?

**Comment by p-thorpe** [comment]
Could be related to https://github.com/pouchdb/pouchdb/issues/6607, I'll keep an eye on that before raising.

**Comment by p-thorpe** [comment]
Confirmed working @`6.3.4`.
