### ISSUE TITLE
local build failure

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#6623]
```
  ✓ wrote packages/node_modules/pouchdb/dist/pouchdb.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:800:14)
```

Isnt failing in CI, would prefer not to back anything out as I have seen this a lot and never properly debugged

**Comment by daleharvey** [comment]
`TRAVIS=1 npm run build` works fine, it looks like an issue with https://github.com/pouchdb/pouchdb/blob/master/bin/build-utils.js#L36

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/b337b80bfc228ba04fba5f628d282e9dde338a10
