### ISSUE TITLE
TypeError: Cannot read property 'def' of undefined

### ISSUE THREAD

**Issue by JeevanJain** [pouchdb/pouchdb#6755]
### Issue
PouchDB-find query not working.
After updating to latest Pouchdb: 6.3.4 and Pouchdb-find: 6.3.4

### Info
- Environment: Node.js
- Adapter: LevelDB
- Server: CouchDB

### Reproduce
Error: 
TypeError: Cannot read property 'def' of undefined
    at <path>\node_modules\pouchdb-find\lib\index.js:666:44
    at Array.map (native)
    at <path>\node_modules\pouchdb-find\lib\index.js:660:24
    at Array.map (native)
    at <path>\node_modules\pouchdb-find\lib\index.js:657:8
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by JeevanJain** [comment]
Solved issue

Deleted db folder and recreated it
