### ISSUE TITLE
Typescript not working anymore

### ISSUE THREAD

**Issue by vinz243** [pouchdb/pouchdb#6767]
### Issue

I am trying to use latest version of pouchdb with typescript, however I can't import, only require will work, which breaks typings. If I try this with version `6.3.4`:

```ts
> import PouchDB from 'pouchdb'
undefined
> PouchDB
undefined
```

### Info

- Environment: Node v8.5.0, Typescript 2.5.2
- Platform: Ubuntu 16.04.3 LTS WSL

### Reproduce

```
❯ npm install pouchdb@6.3.4
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pouchdb@6.3.4
added 114 packages and updated 5 packages in 44.435s

compactd git/master*  48s
❯ node test
undefined

compactd git/master*  
❯ ts-node
>  import * as PouchDB from 'pouchdb';
[eval].ts:2
Object.defineProperty(exports, "__esModule", { value: true });
                      ^

ReferenceError: exports is not defined
    at [eval].ts:2:23
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at ContextifyScript.Script.runInNewContext (vm.js:59:15)
    at _eval (/home/vincent/.nvm/versions/node/v8.5.0/lib/node_modules/ts-node/dist/_bin.js:181:29)
    at REPLServer.replEval (/home/vincent/.nvm/versions/node/v8.5.0/lib/node_modules/ts-node/dist/_bin.js:220:18)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:115:13)
    at REPLServer.emit (events.js:210:7)
> import PouchDB2 from 'pouchdb';
undefined
> PouchDB2
undefined
```

**Comment by bbenezech** [comment]
`import PouchDB from "pouchdb-browser";` ?

**Comment by vinz243** [comment]
It's not in the browser but in node, best I could do it 

```ts
import Pouch from 'pouchdb';
const PouchDB: typeof Pouch = require('pouchdb');
```

**Comment by daleharvey** [comment]
Closing out typescript bugs, we do not use typescript for this repo and if typescript projects cant use other javascript projects then I would suggest that they fix that
