### ISSUE TITLE
Encountered `Cannot sort on field(s) ... when using the default index` using the `memory` adapter or the leveldb adapter, but the same query works on couchdb.

### ISSUE THREAD

**Issue by kevinjqiu** [pouchdb/pouchdb#6973]
### Issue
Write the description of the issue here
Encountered `Cannot sort on field(s) ... when using the default index` using the `memory` adapter or the leveldb adapter, but the same query works on couchdb.

### Info
- Environment: Node.js/browser
- Platform: Chrome
- Adapter: Memory/LevelDB
- Server: CouchDB

### Reproduce

https://gist.github.com/kevinjqiu/9d74befc20e60826a4c34c6b4a971812

```
node bug.js 
(node:4532) UnhandledPromiseRejectionWarning: Error: Cannot sort on field(s) "date" when using the default index
    at validateSort (/home/kevin/src/florinapp/v2/node_modules/pouchdb-find/lib/index.js:493:13)
    at /home/kevin/src/florinapp/v2/node_modules/pouchdb-find/lib/index.js:1206:5
    at <anonymous>
```

UPDATE: Can't even `explain` on the query:

```javascript
var PouchDB = require('pouchdb');

PouchDB.plugin(require('pouchdb-find'));

db = new PouchDB("test");

db.explain({
        selector: {
            $and: [
                {"metadata.type": "Transaction"},
                {"date": {$exists: true}}
            ]
        },
        sort: ["date"]
}).then((e) => {
    console.log(e);
});
```

```
node bug.js 
(node:8472) UnhandledPromiseRejectionWarning: Error: Cannot sort on field(s) "date" when using the default index
    at validateSort (/home/kevin/src/florinapp/v2/node_modules/pouchdb-find/lib/index.js:493:13)
    at /home/kevin/src/florinapp/v2/node_modules/pouchdb-find/lib/index.js:1206:5
    at <anonymous>
(node:8472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ednsinf** [comment]
This issue not solved at this current version ("pouchdb-find": "^7.2.2"):
Cannot sort on field(s) "price" when using the default index
[...]node_modules\pouchdb-find\lib\index.js:1250:5
