### ISSUE TITLE
Calling destroy() from a client make crashing the PouchDB Server with memdown adapter

### ISSUE THREAD

**Issue by daweedm** [pouchdb/pouchdb#7216]
### Issue
Calling `destroy()` from a client make crashing the PouchDB Server with memdown adapter

```bash
/node_modules/pouchdb/lib/index.js:6201
    leveldown.destroy(name, cb);
              ^

TypeError: leveldown.destroy is not a function
    at callDestroy (/Users/Daweed/Documents/Caira's projects/papyrus-pos/node_modules/pouchdb/lib/index.js:6201:15)
    at /Users/Daweed/Documents/Caira's projects/papyrus-pos/node_modules/pouchdb/lib/index.js:6194:9
    at /Users/Daweed/Documents/Caira's projects/papyrus-pos/node_modules/levelup/lib/levelup.js:114:16
    at /Users/Daweed/Documents/Caira's projects/papyrus-pos/node_modules/abstract-leveldown/abstract-leveldown.js:67:5
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Info
- Environment: nodejs
- Platform: macOS
- Adapter: memdown
- Server: PouchDB server

### Reproduce

Start a PouchDB Server with leveldown adapter

```js
var pouchdb = require('pouchdb');
pouchdb.plugin(require('pouchdb-authentication'));

var InMemoryPouchdb = pouchdb.defaults({
    //prefix: './tmp-db/'
    db: require('memdown')
});

var express = require('express');
var expressPouchdb = require('express-pouchdb');
var app = express();

app.use('/', expressPouchdb(InMemoryPouchdb, {
        mode: 'fullCouchDB',
        inMemoryConfig: true
    }));

app.listen(1234);

```
Open fauxton, create a simple database and try to delete it. The server crashes.

**Comment by daweedm** [comment]
May be related to https://github.com/Level/memdown/issues/146

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/6e49c10a3e5482887731b765c17d0ea6d2c98014
