### ISSUE TITLE
Crash at domain.enter on Node >v9.5

### ISSUE THREAD

**Issue by sax1johno** [pouchdb/pouchdb#7257]
### Issue
When attempting to create a Pouch database in NodeJS >v9.5, creating a new database connection causes the process to crash with the following stack trace:
```
> domain.js:101
    domain.enter();
           ^
TypeError: domain.enter is not a function
    at topLevelDomainCallback (domain.js:101:12)
```

### Info
- Environment: (Node.js/browser/hybrid app/etc.):
NodeJS >9.5 (this does NOT happen in version v9.5 or lower)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
NodeKS on Mac OSX
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
LevelDB
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)
File

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

The following code on version >v9.5 will reproduce the issue:
```
const Pouch = require('pouchdb');
var pt = new Pouch("test");
```

**Comment by daleharvey** [comment]
So looks the same as the mysql issue, I have run the test suite and looks to be passing fine so it looks like some 3rd party dep is breaking? either way its a good idea for us to be testing v10 so added a PR @ https://github.com/pouchdb/pouchdb/pull/7302

**Comment by felixrabe** [comment]
Just want to add that trying to use PouchDB from the Node REPL gives this same error:

    $ node --version
    v10.4.1
    
    $ node
    > const PouchDB = require('pouchdb')
    undefined
    > const db = new PouchDB('my_database')
    undefined
    > domain.js:120
        domain.enter();
               ^

    TypeError: domain.enter is not a function
        at topLevelDomainCallback (domain.js:120:12)
    
    $ cat package.json 
    {
      "dependencies": {
        "pouchdb": "^6.4.3"
      }
    }

But putting the same code into index.js and running `node index.js` works fine (at least does not give the error).

**Comment by garbados** [comment]
I am experiencing the same issue:

```bash
$ node
> const PouchDB = require('pouchdb')
undefined
> const db = new PouchDB('.db')
undefined
> domain.js:120
    domain.enter();
           ^

TypeError: domain.enter is not a function
    at topLevelDomainCallback (domain.js:120:12)
$ cat package.json | jq .dependencies.pouchdb
"^7.0.0"
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

**Comment by k-j-kleist** [comment]
I am getting the same error as felixrabe and garbados, using pouchdb-node@7.0.0 / Node.js v10.15.0 / Windows 10.

This could possibly be related to `leveldown`'s usage of an old version of `nan`:
```
+-- pouchdb-node@7.0.0
. . .
| +-- leveldown@3.0.0
. . .
| | +-- nan@2.8.0

```
see https://github.com/aerospike/aerospike-client-nodejs/issues/254
and https://github.com/aerospike/aerospike-client-nodejs/pull/255
