### ISSUE TITLE
How to handle multiple PouchDB instances?

### ISSUE THREAD

**Issue by akowald** [pouchdb/pouchdb#7261]
### Issue
I created a bug the other day which created and closed a local database in different instances during a sync and I got this nasty error:
```
Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at openTransactionSafely (https://localhost/assets/pouchdb/pouchdb-6.4.3.js:7346:16)
    at PouchAlt.api._getLocal (https://localhost/assets/pouchdb/pouchdb-6.4.3.js:8777:21)
    at PouchAlt.<anonymous> (https://localhost/assets/pouchdb/pouchdb-6.4.3.js:4701:17)
    at PouchAlt.<anonymous> (https://localhost/assets/pouchdb/pouchdb-6.4.3.js:2797:21)
    at PouchAlt.<anonymous> (https://localhost/assets/pouchdb/pouchdb-6.4.3.js:21:18)
    at https://localhost/assets/pouchdb/pouchdb-6.4.3.js:2736:21
    at new Promise (<anonymous>)
    at PouchAlt.<anonymous> (https://localhost/assets/pouchdb/pouchdb-6.4.3.js:2723:19)
    at PouchAlt.get (https://localhost/assets/pouchdb/pouchdb-6.4.3.js:21:18)
    at updateCheckpoint (https://localhost/assets/pouchdb/pouchdb-6.4.3.js:13810:13)
```
I figured it would be safe to .close() one PouchDB instance without causing ill effects on another instance with the same database but I guess I was wrong. What's the best practice for keeping track of multiple instances of the same database? Right now I create a new instance for each type of function and close them when the function completes. This was to ensure that the database isn't closed for the duration of the function and to make clean up easy.

Would I be better off just creating one instance for each database and not worry about closing them? There is a limited number of databases in my app. I noticed that the changes feed works between different instances so I was wondering what would be best practice.. thanks!

### Info
- Environment: Browser / PouchDB 6.4.3
- Platform: Chrome 66.0.3359.139
- Adapter: IndexedDB
- Server: CouchDB

**Comment by daleharvey** [comment]
Under the hood we only ever keep open one open indexeddb database and we dont refcount so if you close it, it closes them all (https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-idb/src/index.js#L53) so I wouldnt worry about closing any of them until you are completely done

**Comment by akowald** [comment]
Thanks for the clarification!
