### ISSUE TITLE
Update leveldown to 3.0.2 at least.

### ISSUE THREAD

**Issue by britishd** [pouchdb/pouchdb#7405]
I use `nodejs-mobile-cordova` with `pouchdb-server` in my cordova application.

So, i have a build issues when trying to compile `leveldown` as dependencies in pouchdb.

```
gyp verb command build []
gyp verb build type Release
gyp verb architecture x86
gyp verb node dev dir /Users/user/Documents/Work/project/platforms/android/src/com/janeasystems/cdvnodejsmobile/jni/libnode/
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
../deps/snappy/snappy-1.1.4/snappy.cc:99:3: error: unknown type name '__m128i'
  __m128i x = _mm_loadu_si128(static_cast<const __m128i*>(src));
  ^
../deps/snappy/snappy-1.1.4/snappy.cc:99:49: error: unknown type name '__m128i'
  __m128i x = _mm_loadu_si128(static_cast<const __m128i*>(src));
                                                ^
../deps/snappy/snappy-1.1.4/snappy.cc:99:15: error: use of undeclared identifier '_mm_loadu_si128'
  __m128i x = _mm_loadu_si128(static_cast<const __m128i*>(src));
              ^
../deps/snappy/snappy-1.1.4/snappy.cc:100:32: error: unknown type name '__m128i'
  _mm_storeu_si128(static_cast<__m128i*>(dst), x);
                               ^
4 errors generated.
make: *** [Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/Documents/Work/project/node_modules/nodejs-mobile-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/user/n/bin/node" "/Users/user/Documents/Work/project/node_modules/nodejs-mobile-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Documents/Work/project/platforms/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-x86/nodejs-project/node_modules/pouchdb/node_modules/leveldown
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v0.2.0
gyp ERR! not ok 
npm verb lifecycle leveldown@3.0.0~install: unsafe-perm in lifecycle true
npm verb lifecycle leveldown@3.0.0~install: CWD: /Users/user/Documents/Work/project/platforms/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-x86/nodejs-project/node_modules/pouchdb/node_modules/leveldown
npm info lifecycle leveldown@3.0.0~install: Failed to exec install script
npm verb stack Error: leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/user/Documents/Work/project/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/Users/user/Documents/Work/project/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:920:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
npm verb pkgid leveldown@3.0.0
npm verb cwd /Users/user/Documents/Work/project/platforms/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-x86/nodejs-project
npm verb Darwin 17.7.0
npm verb argv "/Users/user/n/bin/node" "/Users/user/Documents/Work/project/node_modules/.bin/npm" "--verbose" "rebuild" "--build-from-source"
npm verb node v6.12.3
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-07-26T07_48_24_282Z-debug.log

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':BuildNpmModulesx86'.
> Process 'command 'npm'' finished with non-zero exit value 1
```

That error has already fixed in `3.0.2` version of leveldown. 

And as you can understand with `leveldown@3.0.0` my build always is failed and I must add some workarounds like changing `package-lock.json` to fix it (change version of `leveldown` to 3.0.2).

**Comment by daleharvey** [comment]
If you could make a PR with the latest version that would be great
