### ISSUE TITLE
db.fetch is not a function

### ISSUE THREAD

**Issue by oh-moses** [pouchdb/pouchdb#7426]
### Issue
Using the pouchdb-find plugin, when I call `db.createIndex`, I get the following error:
```
TypeError: db.fetch is not a function
    at dbFetch (/home/moses/dev/safecontracts/backend/accounts-app/node_modules/pouchdb-find/lib/index.js:46:6)
    at createIndex (/home/moses/dev/safecontracts/backend/accounts-app/node_modules/pouchdb-find/lib/index.js:63:3)
    at PouchDB.<anonymous> (/home/moses/dev/safecontracts/backend/accounts-app/node_modules/pouchdb-find/lib/index.js:1371:3)
    at /home/moses/dev/safecontracts/backend/accounts-app/node_modules/pouchdb-utils/lib/index.js:118:21
    at new Promise (<anonymous>)
    at PouchDB.<anonymous> (/home/moses/dev/safecontracts/backend/accounts-app/node_modules/pouchdb-utils/lib/index.js:105:19)
    at PouchDB.createIndex (/home/moses/dev/safecontracts/backend/accounts-app/node_modules/argsarray/index.js:14:18)
    […]
```

`console.log(db.fetch)` gives `undefined`.

### Info
- Environment: Node.js
- Server: CouchDB 2.1
- Plugins used: find, upsert

**Comment by AntonPilyak** [comment]
Maybe, you have to initialize it properly? In my case, the following works:
import PouchDB from 'pouchdb';
import PouchDBFind from 'pouchdb-find';
PouchDB.plugin(PouchDBFind);

**Comment by oh-moses** [comment]
@AntonPilyak I `require` the packages because I'm in Node, but otherwise I do the same. Thanks though.

Reading the `pouchdb-find` code, I can't even tell how the `fetch` method is supposed to get attached to PouchDB, so it's really hard to debug.

**Comment by oh-moses** [comment]
Oops, I'm an idiot. I didn't notice the plugin was on different major version (v7.0) than Pouch itself (v6.4). Solved.
