### ISSUE TITLE
`npm run dev` fails with `Error: Cannot find module 'lie'`

### ISSUE THREAD

**Issue by ptitjes** [pouchdb/pouchdb#7535]
### Issue
Running tests with `npm run dev` fails.

```bash
$ npm install
...
    
$ npm run dev            

> pouchdb-monorepo@7.0.0-prerelease dev /home/didier/Code/external/pouchdb
> bash bin/run-dev.sh

Waiting for host to start .
Host started :)
> pouchdb-monorepo@7.0.0-prerelease launch-dev-server /home/didier/Code/external/pouchdb
> node ./bin/dev-server.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'lie'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/didier/Code/external/pouchdb/bin/dev-server.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pouchdb-monorepo@7.0.0-prerelease launch-dev-server: `node ./bin/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pouchdb-monorepo@7.0.0-prerelease launch-dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/didier/.npm/_logs/2018-11-21T17_48_46_579Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pouchdb-monorepo@7.0.0-prerelease dev: `bash bin/run-dev.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pouchdb-monorepo@7.0.0-prerelease dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/didier/.npm/_logs/2018-11-21T17_48_46_608Z-debug.log
```

### Info
- Environment: n/a
- Platform: n/a
- Adapter: n/a
- Server: n/a

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
Mentioned on irc, but we dont need the require(lie) in dev-server, we only need to polyfill promises for running tests in browsers that dont support them so I dont know why its breaking but if someone wants to take it out that would be great
