### ISSUE TITLE
Installing PouchDB on NodeJs 11.6.0 gives errors. The project is on ionic 4 beta (brand new project)

### ISSUE THREAD

**Issue by helenakohan** [pouchdb/pouchdb#7595]
<!--
### Issue
I am trying to install PouchDB (for ionic 4 beta) on NodeJs 11.6.0 on X64 Windows 10.
What should I do in order to get the package installed?

### Info
- Environment: Node.js, Ionic 4 beta (totally new project)
- Platform: Chrome & Android
- Adapter & Server: PouchDB

### Reproduce
Step 1. create ionic 4 beta project: 
(link: https://ionicframework.com/getting-started#cli)
npm install -g ionic
ionic start myApp tabs

Step 2. Now install PouchDB:
npm install pouchdb --save

### The NodeJs output

npm install pouchdb --save

> leveldown@3.0.0 install C:\a\1\myApp\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.6.0 runtime=node arch=x64 platform=win32)

C:\a\1\myApp\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Users\HP\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platfo
rm for project 'leveldb.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to b
uild a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [
C:\a\1\myApp\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platfo
rm for project 'snappy.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to bu
ild a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [C
:\a\1\myApp\node_modules\leveldown\deps\snappy\snappy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\a\1\myApp\node_modules\leveldown
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
myApp@0.0.1 C:\a\1\myApp
+-- argsarray@0.0.1  extraneous
+-- clone-buffer@1.0.0  extraneous
+-- UNMET PEER DEPENDENCY cordova-plugin-ionic@^5.0.0
+-- double-ended-queue@2.1.0-0  extraneous
+-- fetch-cookie@0.7.0  extraneous
+-- level-codec@7.0.1  extraneous
+-- level-packager@2.1.1  extraneous
+-- level-write-stream@1.0.0  extraneous
+-- levelup@3.0.1  extraneous
+-- ltgt@2.2.1  extraneous
+-- node-fetch@2.3.0  extraneous
+-- opencollective-postinstall@2.0.1  extraneous
+-- spark-md5@3.0.0  extraneous
`-- vuvuzela@1.0.3  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /@angular/compiler-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN @ionic/pro@2.0.4 requires a peer of cordova-plugin-ionic@^5.0.0 but none was installed.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "pouchdb" "--save"
npm ERR! node v11.6.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE

npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@3.0.0 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\a\1\myApp\npm-debug.log

**Comment by helenakohan** [comment]
### Issue
I am trying to install PouchDB [for the ionic 4 beta project] on NodeJS 11.6.0
It won't let me to do it.

See below the entire Command Line output text it produces.

### Info
- Environment: Node.js, Ionic 4 beta
- Platform: Command Line (cmd)
- Adapter & Server: PouchDB

### Reproduce
Step 1. Start a brand new Ionic 4 beta project on Node 11.6.0:
[  Link: https://ionicframework.com/getting-started#cli  ]

npm install -g ionic
ionic start myApp tabs

Step 2. Try to install PouchDB:

npm install pouchdb --save


### CMD output


npm install pouchdb --save

> leveldown@3.0.0 install C:\a\1\myApp\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.6.0 runtime=node arch=x64 platform=win32)

C:\a\1\myApp\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Users\HP\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platfo
rm for project 'leveldb.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to b
uild a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [
C:\a\1\myApp\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platfo
rm for project 'snappy.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to bu
ild a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [C
:\a\1\myApp\node_modules\leveldown\deps\snappy\snappy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\a\1\myApp\node_modules\leveldown
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
myApp@0.0.1 C:\a\1\myApp
+-- argsarray@0.0.1  extraneous
+-- clone-buffer@1.0.0  extraneous
+-- UNMET PEER DEPENDENCY cordova-plugin-ionic@^5.0.0
+-- double-ended-queue@2.1.0-0  extraneous
+-- fetch-cookie@0.7.0  extraneous
+-- level-codec@7.0.1  extraneous
+-- level-packager@2.1.1  extraneous
+-- level-write-stream@1.0.0  extraneous
+-- levelup@3.0.1  extraneous
+-- ltgt@2.2.1  extraneous
+-- node-fetch@2.3.0  extraneous
+-- opencollective-postinstall@2.0.1  extraneous
+-- spark-md5@3.0.0  extraneous
`-- vuvuzela@1.0.3  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /@angular/compiler-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN @ionic/pro@2.0.4 requires a peer of cordova-plugin-ionic@^5.0.0 but none was installed.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "pouchdb" "--save"
npm ERR! node v11.6.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE

npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@3.0.0 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\a\1\myApp\npm-debug.log

**Comment by pubkey** [comment]
I had the same problem several times.
It occurs because the binaries of leveldown are not shipped for brand new node versions. Usually this takes some weeks and then they are shipped and will work.

If you do not want to wait for this, I recommend to switch to the lastest LTS version of node `10.15.0`.

**Comment by helenakohan** [comment]
Hi:

10x for the answer.

I switched to this version o node (unibstalled 11.6.0 and installed 10.15.0)

and it gave me this:


+-- argsarray@0.0.1  extraneous
+-- clone-buffer@1.0.0  extraneous
+-- UNMET PEER DEPENDENCY cordova-plugin-ionic@^5.0.0
+-- double-ended-queue@2.1.0-0  extraneous
+-- fetch-cookie@0.7.0  extraneous
+-- level-codec@7.0.1  extraneous
+-- level-packager@2.1.1  extraneous
+-- level-write-stream@1.0.0  extraneous
+-- levelup@3.0.1  extraneous
+-- ltgt@2.2.1  extraneous
+-- node-fetch@2.3.0  extraneous
+-- opencollective-postinstall@2.0.1  extraneous
+-- spark-md5@3.0.0  extraneous
`-- vuvuzela@1.0.3  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.6
npm WARN optional Skipping failed optional dependency /@angular/compiler-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.6
npm WARN @ionic/pro@2.0.4 requires a peer of cordova-plugin-ionic@^5.0.0 but none was installed.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "pouchdb" "--save"
npm ERR! node v10.15.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE

npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@3.0.0 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\a\1\gp\npm-debug.log
