### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Alecyrus** [pouchdb/pouchdb#7623]
### Issue
```
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at dirname (path.js:1268:5)
    at Function.getRoot (webpack:///./node_modules/bindings/bindings.js?:154:13)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:60:32)
    at eval (webpack:///./node_modules/level/node_modules/leveldown/leveldown.js?:4:101)
    at Object../node_modules/level/node_modules/leveldown/leveldown.js (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:1397:1)
    at __webpack_require__ (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:20:30)
    at eval (webpack:///./node_modules/level/level.js?:1:111)
    at Object../node_modules/level/level.js (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:1364:1)
    at __webpack_require__ (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:20:30)
```
### Info
- Environment: node 10.14.2
- Platform: mac, electron 4.0.1
- Adapter: LevelDB
- Server: CouchDB

### Reproduce
run `yarn add pouchde-node`, 
```javascript

let PouchDB = require('pouchdb-node');

let db = new PouchDB('mydb');
```

**Comment by Alecyrus** [comment]
// vue.config.js
module.exports = {
  configureWebpack: {
  },
  pluginOptions: {
    electronBuilder: {
      externals: ['leveldown', 'level', 'pouchdb'],
    },
  },
};
