### ISSUE TITLE
Unhandled exception during replication

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#7690]
This crashed me in production :( 

```bash
{
  "level":60,
  "time":1552915712712,
  "msg":"error caused exit",
  "pid":1,
  "hostname":"705281bffe15",
  "name":"deepstream",
  "err":{
    "type":"TypeError",
    "message":"Cannot read property 'ids' of null",
    "stack":"TypeError: Cannot read property 'ids' of null
    at /usr/src/app/node_modules/pouchdb-node/lib/index.js:2176:32
    at /usr/src/app/node_modules/pouchdb-node/lib/index.js:4975:18
    at /usr/src/app/node_modules/argsarray/index.js:14:18
    at /usr/src/app/node_modules/pouchdb-node/lib/index.js:5090:16
    at /usr/src/app/node_modules/pouchdb-node/lib/index.js:4095:9
    at /usr/src/app/node_modules/pouchdb-node/lib/index.js:3926:13"
  },
  "v":1
}
```

```js

    this._remoteDb = new PouchDB(options.url)
    this._localDb = new PouchDB(path.join(options.revsPath, '.nxt-backup'))

    // PouchDB
    //   .replicate(this._localDb, this._remoteDb, {
    //     live: true,
    //     retry: true
    //   })
    //   .on('paused', info => {
    //     logger.debug({ info }, 'replication paused')
    //   })
    //   .on('active', info => {
    //     logger.debug({ info }, 'replication active')
    //   })
    //   .on('error', err => {
    //     logger.error({ err }, 'replication failed')
    //   })
```

**Comment by ronag** [comment]
```

pouchdb-node@^7.0.0:
  version "7.0.0"
  resolved "https://registry.yarnpkg.com/pouchdb-node/-/pouchdb-node-7.0.0.tgz#70b9be9a7f4fda141250a313886d5b342161ad54"
  integrity sha512-sE+yqfBtz7ckX3a0MnfHLz2VfUHh7Znnau/bnoSRreBLUGWABAMV0X0QQZUTh+Q3PK5EIZEG0Dk28nU6LKQeFQ==
  dependencies:
    argsarray "0.0.1"
    buffer-from "1.1.0"
    clone-buffer "1.0.0"
    double-ended-queue "2.1.0-0"
    fetch-cookie "0.7.0"
    inherits "2.0.3"
    level "3.0.2"
    level-codec "7.0.1"
    level-write-stream "1.0.0"
    leveldown "3.0.0"
    levelup "3.0.1"
    ltgt "2.2.1"
    node-fetch "^2.0.0"
    readable-stream "1.0.33"
    through2 "2.0.3"
    uuid "3.2.1"
    vuvuzela "1.0.3"
```

**Comment by ronag** [comment]
ping? should I give up here?

**Comment by ronag** [comment]
![Screenshot 2019-04-29 at 15 15 54](https://user-images.githubusercontent.com/3065230/56898597-b8846f80-6a91-11e9-81dd-75042b58471e.png)

**Comment by ronag** [comment]
It seems like if a revision is missing in the rev list then `paths` can be empty which causes a crash.

So if replicating a corrupted database it will crash the whole process.

**Comment by sansato** [comment]
@ronag can you share a patch to fix this?

**Comment by ronag** [comment]
It’s already been merged
