### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ceremcem** [pouchdb/pouchdb#7864]
### Issue
`npm i pouchdb` throws error both on Windows 7 and Linux Debian 9. Here is the error output for Debian: 

```
...
In file included from ../binding.cc:3:
../binding.cc:1837:24: error: invalid conversion from ‘napi_value__* (*)(napi_env, napi_callback_info)’ {aka ‘napi_value__* (*)(napi_env__*, napi_callback_info__*)’} to ‘void*’ [-fpermissive]
   NAPI_EXPORT_FUNCTION(batch_write);
                        ^~~~~~~~~~~
../../napi-macros/napi-macros.h:21:8: note: in definition of macro ‘NAPI_STATUS_THROWS’
   if ((call) != napi_ok) { \
        ^~~~
../binding.cc:1837:3: note: in expansion of macro ‘NAPI_EXPORT_FUNCTION’
   NAPI_EXPORT_FUNCTION(batch_write);
   ^~~~~~~~~~~~~~~~~~~~
../../napi-macros/napi-macros.h:111:81: error: too many arguments to function ‘napi_status napi_create_function(napi_env, const char*, napi_callback, void*, napi_value__**)’
 API_STATUS_THROWS(napi_create_function(env, NULL, 0, name, NULL, &name##_fn)) \
                                                                            ^

../../napi-macros/napi-macros.h:21:8: note: in definition of macro ‘NAPI_STATUS_THROWS’
   if ((call) != napi_ok) { \
        ^~~~
../binding.cc:1837:3: note: in expansion of macro ‘NAPI_EXPORT_FUNCTION’
   NAPI_EXPORT_FUNCTION(batch_write);
   ^~~~~~~~~~~~~~~~~~~~
In file included from ../binding.cc:4:
/home/ceremcem/.node-gyp/8.0.0/include/node/node_api.h:139:25: note: declared here
 NAPI_EXTERN napi_status napi_create_function(napi_env env,
                         ^~~~~~~~~~~~~~~~~~~~
In file included from ../binding.cc:3:
../../napi-macros/napi-macros.h:22:49: error: too many arguments to function ‘napi_status napi_throw_error(napi_env, const char*)’
     napi_throw_error(env, NULL, #call " failed!"); \
                                                 ^
../../napi-macros/napi-macros.h:111:5: note: in expansion of macro ‘NAPI_STATUS_THROWS’
     NAPI_STATUS_THROWS(napi_create_function(env, NULL, 0, name, NULL, &name##_fn)) \
     ^~~~~~~~~~~~~~~~~~
../binding.cc:1837:3: note: in expansion of macro ‘NAPI_EXPORT_FUNCTION’
   NAPI_EXPORT_FUNCTION(batch_write);
   ^~~~~~~~~~~~~~~~~~~~
In file included from ../binding.cc:4:
/home/ceremcem/.node-gyp/8.0.0/include/node/node_api.h:395:25: note: declared here
 NAPI_EXTERN napi_status napi_throw_error(napi_env env, const char* msg);
                         ^~~~~~~~~~~~~~~~
In file included from ../binding.cc:3:
../../napi-macros/napi-macros.h:22:49: error: too many arguments to function ‘napi_status napi_throw_error(napi_env, const char*)’
     napi_throw_error(env, NULL, #call " failed!"); \
                                                 ^
../../napi-macros/napi-macros.h:112:5: note: in expansion of macro ‘NAPI_STATUS_THROWS’
     NAPI_STATUS_THROWS(napi_set_named_property(env, exports, #name, name##_fn)) \
     ^~~~~~~~~~~~~~~~~~
../binding.cc:1837:3: note: in expansion of macro ‘NAPI_EXPORT_FUNCTION’
   NAPI_EXPORT_FUNCTION(batch_write);
   ^~~~~~~~~~~~~~~~~~~~
In file included from ../binding.cc:4:
/home/ceremcem/.node-gyp/8.0.0/include/node/node_api.h:395:25: note: declared here
 NAPI_EXTERN napi_status napi_throw_error(napi_env env, const char* msg);
                         ^~~~~~~~~~~~~~~~
make: *** [leveldown.target.mk:112: Release/obj.target/leveldown/binding.o] Error 1
make: Leaving directory '/home/ceremcem/tmp/a/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.19.0-1-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ceremcem/tmp/a/node_modules/leveldown
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN a@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@5.0.2 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ceremcem/.npm/_logs/2019-08-05T08_31_38_583Z-debug.log

```

### Info
- Environment: Node.js
- Platform: Debian
- Adapter: ?
- Server: ?

**Comment by MichaelJCole** [comment]
Unable to reproduce, works for me :-)

This is a problem with your local config.  Google `node-gyp` to resolve.  Your local machine needs to have the toolchain to build LevelDown (PouchDB's server-side key-value store) which looks like it's written in some kind of C

**Comment by ceremcem** [comment]
What is your `node -v` and `node-gyp -v`?

**Comment by MichaelJCole** [comment]
I'm not debugging this with you.  Good luck!

**Comment by karlwestin** [comment]
Hi @ceremcem this is highly likely an issue with your windows setup and building the native extension leveldown with node-gyp. Node-gyp is using Python and is notoriously tricky on windows. 

Unfortunately i can't answer about debian, but also there i'm almost sure you have python/node-gyp issues. [Check that you're not using python 3](https://github.com/nodejs/node-gyp#on-unix)

- read our [FAQ on leveldown on windows errors](https://pouchdb.com/errors.html#pouchdb_install_errors_windows)
- please search other tickets in this repo for leveldown and build issues, there's a lot of info collected in those
- if you're building a client-side only app, try using [pouchdb-browser](https://www.npmjs.com/package/pouchdb-browser) instead. That one does not need leveldown.

Please post follow-ups if you find something more so others can find it.
