### ISSUE TITLE
7.1.1 replication http>local cant start if leveldb prefix is specified

### ISSUE THREAD

**Issue by wizzard0** [pouchdb/pouchdb#7892]
### Issue
While trying to replace couchdb with pouchdb-express I found out I can't replicate anymore if I specify the leveldb prefix for pouchdb.

It seems that prefix gets added regardless of the adapter, or just concatenated in the wrong place, see the exception text. Maybe I'm misusing the api in some way? I need to wrap leveldown but that does not look like it can affect the replicator.
> When using the 'leveldb' adapter (the default on Node), any other options given will be passed to levelup. [api#create_database](https://pouchdb.com/api.html#create_database)

I'm starting replication from the fauxton UI.

Thanks in advance!

```
Error in .on("change", function): Error: Invalid Adapter: test-prefixhttp
    at PouchAlt.PouchDB (node_modules\pouchdb\lib\index.js:2663:11)
    at new PouchAlt (node_modules\pouchdb\lib\index.js:2791:13)
    at staticSecurityWrappers.replicate (node_modules\pouchdb-security\lib\index.js:211:62)
    at callHandlers (node_modules\pouchdb-wrappers\lib\index.js:467:17)
    at Function.replicate (node_modules\pouchdb-wrappers\lib\index.js:428:12)
    at onChanged (node_modules\pouchdb-replicator\lib\index.js:174:31)
    at Changes$1.<anonymous> (node_modules\pouchdb-replicator\lib\index.js:94:9)
    at Changes$1.emit (events.js:198:13)
    at tryCatchInChangeListener (node_modules\pouchdb\lib\index.js:1391:10)
    at Object.Changes$1.opts.onChange (node_modules\pouchdb\lib\index.js:1429:5)
    at EventEmitter.<anonymous> (node_modules\pouchdb\lib\index.js:491:14)
    at EventEmitter.emit (events.js:198:13)
    at EventEmitter.emit (events.js:198:13)
    at Changes$1.emit (events.js:198:13)
    at tryCatchInChangeListener (node_modules\pouchdb\lib\index.js:1391:10)
    at Object.Changes$1.opts.onChange (node_modules\pouchdb\lib\index.js:1429:5)
```

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
Node v10.16.3
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
reproduceable on Ubuntu 18.04LTS/Windows Server 2016
 express-pouchdb v. 4.1.0
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
LevelDB, http
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)
PouchDB Server 6/7, CouchDB 2.1 =>(http pull)=> Pouch v7.1.1

### Reproduce
step 1:
```
let opts={prefix:'test-prefix'}
let factory=(levelOpts) => wrapped(leveldown(levelOpts),wrapperOpts);
let ouch = PouchDB.defaults(Object.assign({db: factory}, opts));
app.use('/', require('express-pouchdb')(ouch));
app.listen(3001);
```
step 2: create replication from fauxton UI

**Comment by gaodeng** [comment]
?

**Comment by wizzard0** [comment]
I can try look into this issue myself, but some pointers on pouch internals would be helpful too.
