### ISSUE TITLE
"fetch" is not defined after including pouchdb-browser

### ISSUE THREAD

**Issue by brettins** [pouchdb/pouchdb#8022]
#7895 # Issue
Cannot compile run electron project with pouchdb-browser. 

ReferenceError: fetch is not defined
   at Object.<anonymous> ([proj_dir]\node_modules\pouchdb-browser\lib\index.js:2869:11)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)

### Info
- Environment: Node & Electron
- Platform: Electron
- Adapter: None specified
- Server: PouchDB

**Comment by vjau** [comment]
I got the same problem.
I think browser APIs are not available in the main thread and so fetch is not available there. You have to use pouchdb-browser in render threads. It's what i did with success.

**Comment by BillMeyerRSA** [comment]
> I got the same problem.
> I think browser APIs are not available in the main thread and so fetch is not available there. You have to use pouchdb-browser in render threads. It's what i did with success.

Have the same issue - but don't understand what is meant with: "You have to use pouchdb-browser in render threads"

**Comment by vjau** [comment]
If you want to use pouchdb in the main thread, you have to use pouchdb (and a native db).
If you want to use pouchdb in renderer threads, you have to use pouchdb-browser.
