### ISSUE TITLE
TypeError: Cannot convert undefined or null to object" when adding sort

### ISSUE THREAD

**Issue by ednsinf** [pouchdb/pouchdb#8240]
Code:
db.createIndex({
  index: {
    fields: ['order', 'name']
  }
})

Error:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.getKey ([...]\node_modules\pouchdb-selector-core\lib\index.js:62:17)
    at userOperatorLosesPrecision ([...]\node_modules\pouchdb-find\lib\index.js:727:42)
    at getBasicInMemoryFields ([...]\node_modules\pouchdb-find\lib\index.js:762:24)
    at getInMemoryFields ([...]\node_modules\pouchdb-find\lib\index.js:787:5)
    at planQuery ([...]\node_modules\pouchdb-find\lib\index.js:1164:24)
    at [...]\node_modules\pouchdb-find\lib\index.js:1245:21

**Comment by daleharvey** [comment]
It looks like a common error / lack of support, could you provide a more complete runnable example of it failing @ https://glitch.com/~pouchdb-bug-helper ? Cheers
