### ISSUE TITLE
Implement partial_filter_selector?

### ISSUE THREAD

**Issue by garbados** [pouchdb/pouchdb#8276]
### Issue

The `partial_filter_selector` property of Mango indexes is not handled by pouchdb-find. It should be!

### Info
- Environment: N/A
- Platform: N/A
- Adapter: Local (Remote CouchDB automatically handles partial indexes)
- Server: N/A

### Reproduce

Consider this example script, `partial_index_test.js`:

```js
const assert = require('assert').strict

const PouchDB = require('pouchdb')
PouchDB.plugin(require('pouchdb-find'))

async function setup (db) {
  await db.createIndex({
    index: {
      fields: ['user_id'],
      partial_filter_selector: { type: 'post' },
      ddoc: 'queries',
      name: 'posts'
    }
  })
  await db.put({
    _id: 'user/test',
    type: 'user'
  })
  await db.put({
    _id: 'post/test',
    user_id: 'user/test',
    type: 'post',
    created_at: Date.now()
  })
  await db.put({
    _id: 'not-post/test',
    user_id: 'user/test',
    type: 'not-post',
    created_at: Date.now()
  })
}

const COUCH_URL = process.env.COUCH_URL
const DB_NAME = COUCH_URL ? `${COUCH_URL}/test` : '.test'
const db = new PouchDB(DB_NAME)

Promise.resolve().then(async () => {
  // create indexes, populate db
  await setup(db)
  // test the index
  const result = await db.find({
    selector: { user_id: 'user/test' },
    use_index: ['_design/queries', 'posts']
  })
  assert.equal(result.docs.length, 1)
  console.log('Output correct.')
}).catch((err) => {
  console.log(err)
}).then(async () => {
  await db.destroy()
})
```

This script instantiates a database with a Mango index and two documents. The index is created with a partial index that only returns documents of type "post". If this partial index is not applied, a similar document of type "not-post" will also be returned. As you can see...:

```bash
$ COUCH_URL="" node partial_index_test.js 
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

2 !== 1

    at /home/deus/code/scratch/db_find.js:45:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 2,
  expected: 1,
  operator: 'strictEqual'
}
```

Using a CouchDB installation by setting `COUCH_URL` generates the correct result:

```bash
$ COUCH_URL="http://[user:pass]@localhost:5984" node partial_index_test.js
Output correct.
```

**Comment by dheimoz** [comment]
Plase do not close this.

**Comment by dheimoz** [comment]
hey @daleharvey little help here, please.

**Comment by daleharvey** [comment]
Sorry about that, definitely need to reconsider this bot given the current activity levels

**Comment by dheimoz** [comment]
Thank you very much @daleharvey 

I also want to take the opportunity, to all those interested, to invite you to the Pouchdb Channel from the official Couchdb Slack workspace.
https://couchdb.slack.com/archives/C016TJAE7A4

I believe we can collaborate further there.

Thanks.

**Comment by garbados** [comment]
GITHUB. BAD GITHUB.

**Comment by dheimoz** [comment]
Hi @daleharvey , @garbados has been working on this tirelessly. Her work will benefit Pouchdb. I will keep tracking the issue.
@garbados Keep it up! you can do it.

**Comment by garbados** [comment]
Hey, I'm still on this. You know how it is with volunteer labor. I'm getting to it this evening.
