### ISSUE TITLE
Unable to use the module

### ISSUE THREAD

**Issue by EnderInvader** [pouchdb/pouchdb#8283]
### Issue
I am simply trying to run in a javascript file in Visual Studio Code, however the require statement does not seems to be working.

```Javascript
var PouchDB = require('pouchdb');
```
This is the only line in the file.

```
Exception has occurred: TypeError: Cannot assign to read only property 'name' of function 'function generateUUID(value, namespace, buf, offset) {
    const off = buf && offset || 0;
    if (typeof value...<omitted>... }'
  at _default (c:\Users\derek\node_modules\uuid\dist\v35.js:69:23)
    at Object.<anonymous> (c:\Users\derek\node_modules\uuid\dist\v3.js:14:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (c:\Users\derek\node_modules\uuid\dist\index.js:33:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

### Info
- Environment: (Node.js)
- Platform: (Visual Studio Code)

**Comment by dheimoz** [comment]
Hello @EnderInvader 

Could you try?
```js
const PouchDB = require('pouchdb')
```

The error is shown where? Also, are you starting the Database?
```js
const db = new PouchDB(this.name)
```

I have tried in Node 15 and works great.
