### ISSUE TITLE
No native build was found for platform=darwin arch=arm64

### ISSUE THREAD

**Issue by MeiJo88** [pouchdb/pouchdb#8416]
### Issue
Hey, i want to create an electron app and want you use pouchDB.
When using couchDB i get this error:
`[1] App threw an error during load
[1] Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=99 uv=1 armv=8 libc=glibc
[1]     at Function.load.path (.../node_modules/pouchdb/node_modules/node-gyp-build/index.js:56:9)
[1]     at load (../node_modules/pouchdb/node_modules/node-gyp-build/index.js:20:30)
[1]     at Object.<anonymous> (.../node_modules/pouchdb/node_modules/leveldown/binding.js:1:43)`

### Info
- Environment: (Node.js/Electron.)

### Reproduce
create electron app by boilerplate code, add pouchdb dependency and call this:
`var PouchDB = require('pouchdb');
var db = new PouchDB();`

Thanks

**Comment by dheimoz** [comment]
hey @MeiJo88 I am not familiar con Electron. I wonder if you can create a minimal reproduction.
