### ISSUE TITLE
EventEmitter memory leak when replication fails

### ISSUE THREAD

**Issue by michael42** [pouchdb/pouchdb#8447]
### Issue

It seems to me that PouchDB 7.2.2 has a memory leak when the replication fails.

### Info
- Environment: Node.js 16
- Platform: n/a
- Adapter: memory
- Server: n/a

### Reproduce
Running `MaxListenersExceededWarning.mjs`:
```js
import PouchDBAdapterHttp from "pouchdb-adapter-http"
import PouchDBAdapterMemory from "pouchdb-adapter-memory"
import PouchDB from "pouchdb-core"
import PouchDBReplication from "pouchdb-replication"


PouchDB.plugin(PouchDBAdapterMemory)
PouchDB.plugin(PouchDBAdapterHttp)
PouchDB.plugin(PouchDBReplication)


const local = new PouchDB("local", {adapter: "memory"})
const remote = new PouchDB("http://remote.example")

for (let index = 0; index < 10; index++)
    await local.replicate.to(remote).catch(() => undefined)
```

with `node --trace-warnings` prints:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added to [PouchDB]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at PouchDB.addListener (node:events:487:10)
    at PouchDB.once (node:events:531:8)
    at Replication.ready ([...]/node_modules/pouchdb-replication/lib/index.js:750:7)
    at replicate ([...]/node_modules/pouchdb-replication/lib/index.js:261:15)
    at Function.replicateWrapper [as replicate] ([...]/node_modules/pouchdb-replication/lib/index.js:792:3)
    at Object.to ([...]/node_modules/pouchdb-replication/lib/index.js:1018:37)
    at file:///[...]/MaxListenersExceededWarning.mjs:16:27
```

Using a `while (true)` loop and limiting heap space (`--max-old-space-size=256`) causes the process to reliably run out of memory in a few minutes.

I don't think I'm doing something wrong in my example code, so I looked at the PouchDB source and added a few thoughts:

```js
Replication.prototype.ready = function (src, target) {
  var self = this;
  if (self._readyCalled) {
    return;
  }
  self._readyCalled = true;

  function onDestroy() {
    self.cancel();
  }
  src.once('destroyed', onDestroy);    // <- this seems to leak
  target.once('destroyed', onDestroy); // <- this seems to leak, too
  function cleanup() {
    src.removeListener('destroyed', onDestroy);
    target.removeListener('destroyed', onDestroy);
  }
  self.once('complete', cleanup); // maybe 'complete' isn't triggered when the replication fails?
};
```

**Comment by michael42** [comment]
Just noticed (while preparing a pull request) that there was a duplicate issue (#8161) that was closed due to inactivity, but that *did* result in a fix on `master`. It seems to me that only a new release is missing.

**Comment by AlbaHerrerias** [comment]
This was fixed and merged to master in this PR https://github.com/pouchdb/pouchdb/pull/8419. Therefore I'm closing this issue. We're working in a new release, it will land soon. Thank you.
