### ISSUE TITLE
Pouch replication does not recover when network connection is broken

### ISSUE THREAD

**Issue by grahamdaw** [pouchdb/pouchdb#8462]
### Issue
The replication between PouchDB to a remote CouchDB becomes unresponsive when the network connectivity between the PouchDB system & CouchDB is interrupted.

We have tried several setups and broken the network connectivity in different ways ( network disconnected, internet connectivity loss, etc) which all result in similar behavior. When the network is interrupted the replication never recovers and remains broken (no records are received from the remote DB).

Looking into the network traffic it seems the long poll for replication hangs and never detects the broken connection. Even setting the `timeout` setting when starting the replication doesn't seem to change this behavior. Finally, as the replication just hangs, no error events are emitted by the `PouchDB.replicate`.

### Info
- Environment: Pouch 7.1.1
- Platform: Both Node 14 & Chrome 98
- Adapter: indexeddb/memory
- Server: CouchDB 2.3.1 and PouchDB Server

### Reproduce

We have been using scripts to recreate the issue, one of which is attached to this issue.

The general steps to recreate this are:
1. Set up Pouch on a device replicating to/from a remote CouchDB instance
1. Break the network connection between the PouchDB and CouchDB
1. When the network connection is restored, the replication/sync will not recover. Documents are not received from the remote CouchDB.

```
// This script is used to demonstrate issues in replication for PouchDB.
​
// Setup:
// 1. Connect your laptop to your mobile hotspot wifi
// 2. Start Couch
// docker run -d --name couchTest -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=admin -p 5984:5984 couchdb:latest
// 3. Start ngrok - (this is both used to monitor traffic sent/received for Couch replication and also ensures replication traffic must flow via the remote proxy)
// npx ngrok http 5984
//
// 4. Set the ngrok http host here:
const ngrokHost = 'xxxxx.ngrok.io';
​
// To observe the issue:
// 1. Start this script
// 2. Notice docs replicating from remote on every 10 seconds
// 3. Disconnect Internet connectivity (mobile data) from your hotspot (do not connect to another network in this time).
// 4. Restore Internet connectivity on your hotspot
// 5. Notice replication not working anymore
​
const startedAt = Date.now();
​
function log(message, ...args) {
  console.log(`${Date.now() - startedAt} ${message}`, args);
}
​
log('started');
const internetAvailable = require("internet-available");
var PouchDB = require('pouchdb');
var localDb = new PouchDB('kittens');
var remoteDb = new PouchDB(`http://admin:admin@${ngrokHost}/testdb`);
​
remoteDb
.info()
.then(function (info) {
  log('Got DB info');
})
.catch((err) => {
  log('Error with replication');
});
​
PouchDB.replicate(remoteDb, localDb, {
  live: true,
  retry: true,
})
.on('change', function (info) {
  log(`replicated from remote`);
})
.on('paused', function (err) {
  log(`paused`, err);
})
.on('active', function () {
  log(`active`);
})
.on('denied', function (err) {
  log(`denied`, err);
})
.on('complete', function (info) {
  log(`complete`);
})
.on('error', function (err) {
  log(`error`, err);
});
​
// This interval continuously updates a doc in Couch that should be replicated to Pouch.
setInterval(() => {
  remoteDb.put({
    _id: `${Date.now()}`,
    test: 'foo',
  })
  .then(result => log('put', result.id))
  .catch(err => log('error with put', err));
}, 10000);
​
// Printing the Internet status
setInterval(() => {
  internetAvailable({
    timeout: 200,
    retries: 0,
  }).then(function () {
    log('Internet status', 'OK');
  }).catch(function () {
    log('Internet status', 'FAILED');
  });
}, 1000);

```

**Comment by pturner1989** [comment]
The script is failing because you are not handling errors on the put operation.

If you update the last block of code to the following it will work as expected:

`
// This interval continuously updates a doc in Couch that should be replicated to Pouch.
setInterval(() => {
  remoteDb.put({
    _id: `${Date.now()}`,
    test: 'foo',
  })
  **.then(result => console.log('put', result.id))
  .catch(err => console.log('error', err))**
}, 10000);`

**Comment by pturner1989** [comment]
I use PouchDB sync with remote CouchDB extensively over patchy connections and have not had this issue. Would be happy to help if you can provide example code to reproduce the issue.

**Comment by grahamdaw** [comment]
Would it be possible for you to check the steps to reproduce are listed at the start of the attached script. There could be easier ways to reproduce it but the listed setup is one we find that seems to cause the issue rather reliably (9/10 times testing). 

The crux of the steps is that the machine running the replication is connected to a router that loses Internet connectivity. It's worthwhile noting that it appears to be the replication from remote to local that is especially sensitive to connectivity breaks.

**Comment by grahamdaw** [comment]
Thanks for the feedback @pturner1989, I updated the sample included in this ticket to include that handling when putting records to the DB and also log message monitoring the internet availability.

<details>
  <summary>Raw output from the extended script</summary>
  
Running this test, the output shows that messages are put to the Couch instance and replicated to the `kittens` Pouch DB.

When the internet is disconnected then reconnected, there are successful `put` operations, but the replication does not get any documents from the remote Couch instance
  
  ```
  pouchtest node index.js
0 started []
1248 Internet status [ 'OK' ]
1485 Got DB info []
2220 Internet status [ 'OK' ]
2892 active []
3239 Internet status [ 'OK' ]
3420 replicated from remote []
4261 Internet status [ 'OK' ]
5011 paused [ undefined ]
5227 Internet status [ 'OK' ]
6283 Internet status [ 'OK' ]
7239 Internet status [ 'OK' ]
8255 Internet status [ 'OK' ]
9237 Internet status [ 'OK' ]
10259 Internet status [ 'OK' ]
10749 put [ '1646807228846' ]
10750 active []
11406 replicated from remote []
11434 Internet status [ 'OK' ]
12245 Internet status [ 'OK' ]
12357 paused [ undefined ]
13340 Internet status [ 'OK' ]
14252 Internet status [ 'OK' ]
15277 Internet status [ 'OK' ]
16257 Internet status [ 'OK' ]
17286 Internet status [ 'OK' ]
18421 Internet status [ 'OK' ]
19288 Internet status [ 'OK' ]
20373 Internet status [ 'OK' ]
20724 put [ '1646807238847' ]
20725 active []
21272 Internet status [ 'OK' ]
21354 replicated from remote []
22302 Internet status [ 'OK' ]
22891 paused [ undefined ]
23281 Internet status [ 'OK' ]
24496 Internet status [ 'FAILED' ]
25511 Internet status [ 'FAILED' ]
26517 Internet status [ 'FAILED' ]
27373 Internet status [ 'OK' ]
28297 Internet status [ 'OK' ]
29311 Internet status [ 'OK' ]
30297 Internet status [ 'OK' ]
30762 put [ '1646807248850' ]
31328 Internet status [ 'OK' ]
32400 Internet status [ 'OK' ]
33302 Internet status [ 'OK' ]
34381 Internet status [ 'OK' ]
35310 Internet status [ 'OK' ]
36316 Internet status [ 'OK' ]
37337 Internet status [ 'OK' ]
38357 Internet status [ 'OK' ]
39330 Internet status [ 'OK' ]
40338 Internet status [ 'OK' ]
40683 put [ '1646807258853' ]
41394 Internet status [ 'OK' ]
42377 Internet status [ 'OK' ]
43377 Internet status [ 'OK' ]
44378 Internet status [ 'OK' ]
45356 Internet status [ 'OK' ]
46470 Internet status [ 'OK' ]
47417 Internet status [ 'OK' ]
48462 Internet status [ 'OK' ]
49377 Internet status [ 'OK' ]
50377 Internet status [ 'OK' ]
50762 put [ '1646807268858' ]
51378 Internet status [ 'OK' ]
52368 Internet status [ 'OK' ]
53357 Internet status [ 'OK' ]
54386 Internet status [ 'OK' ]
55506 Internet status [ 'OK' ]
56377 Internet status [ 'OK' ]
57424 Internet status [ 'OK' ]
58399 Internet status [ 'OK' ]
  ```
</details>

In this issue, it is not the put operations to Pouch (where you helped add the error handling) but the replication _from_ the remote Couch instance. In our system, these document `put` operations are made by separate connected clients using similar code & those do not have errors. The replication code we have is the same as in the provide script and this is where we have failures to resume replication. We've tested this in quite a few ways, but this example was the way we can consistently observe the problem we have.

**Comment by pturner1989** [comment]
I do understand your problem is with replication restarting, but in your original code the crash was due to an unhanded error elsewhere. We had to fix that before troubleshooting the replication issue.

I have run your updated code with PouchDB 7.1.1 (and latest 7.2.2), following all the steps in your post, and it works as expected here, output below. 

Sorry, as I can't reproduce the error I'll leave it for someone else to comment further. If you find another way to reproduce this I'll be happy to jump back in.

```
0 started []
{
  db_name: 'testdb',
  purge_seq: '0-g1AAAABXeJzLYWBgYMpgTmEQTM4vTc5ISXIwNDLXMwBCwxyQVB4LkGRoAFL_gSArkQGP2kSGpHqIoiwAtOgYRA',
  update_seq: '79-g1AAAABXeJzLYWBgYMpgTmEQTM4vTc5ISXIwNDLXMwBCwxyQVB4LkGRoAFL_gSArURGP2kSGpHqwIr0sALpLGJM',
  sizes: { file: 577954, external: 1024, active: 12440 },
  props: {},
  doc_del_count: 0,
  doc_count: 74,
  disk_format_version: 8,
  compact_running: false,
  cluster: { q: 2, n: 1, w: 1, r: 1 },
  instance_start_time: '0',
  host: 'http://e5a9-91-109-236-79.ngrok.io/testdb/',
  auto_compaction: false,
  adapter: 'http'
}
1105 Internet status [ 'OK' ]
paused undefined
2091 Internet status [ 'OK' ]
3093 Internet status [ 'OK' ]
4092 Internet status [ 'OK' ]
5094 Internet status [ 'OK' ]
6098 Internet status [ 'OK' ]
7095 Internet status [ 'OK' ]
8307 Internet status [ 'FAILED' ]
9308 Internet status [ 'FAILED' ]
10095 error with put [
  FetchError: request to http://e5a9-91-109-236-79.ngrok.io/testdb/1646820469822 failed, reason: getaddrinfo ENOTFOUND e5a9-91-109-236-79.ngrok.io
      at ClientRequest.<anonymous> (/home/pete/dev/poucchtest/node_modules/node-fetch/lib/index.js:1455:11)
      at ClientRequest.emit (events.js:400:28)
      at Socket.socketErrorListener (_http_client.js:475:9)
      at Socket.emit (events.js:400:28)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    type: 'system',
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    docId: '1646820469822'
  }
]
10321 Internet status [ 'FAILED' ]
11325 Internet status [ 'FAILED' ]
12328 Internet status [ 'FAILED' ]
13330 Internet status [ 'FAILED' ]
14326 Internet status [ 'FAILED' ]
15324 Internet status [ 'FAILED' ]
16333 Internet status [ 'FAILED' ]
17328 Internet status [ 'FAILED' ]
18181 Internet status [ 'OK' ]
19208 Internet status [ 'OK' ]
20115 Internet status [ 'OK' ]
20435 put [ '1646820479822' ]
active
replicated from remote: {"ok":true,"start_time":"2022-03-09T10:07:39.821Z","docs_read":1,"docs_written":1,"doc_write_failures":0,"errors":[],"last_seq":"80-g1AAAACbeJzLYWBgYMpgTmEQTM4vTc5ISXIwNDLXMwBCwxyQVCJDUv3___-zMpgT9XOBAuypqUapyclJ2DTgMSaPBUgyNACp_1DTFMGmGSQbGxgaG2LTlwUAbwQo6g","docs":[{"_id":"1646820479822","_rev":"1-8faebf904b39abb25f4ce960347896db","test":"foo"}],"pending":0}
21120 Internet status [ 'OK' ]
paused undefined
22120 Internet status [ 'OK' ]
23121 Internet status [ 'OK' ]
24122 Internet status [ 'OK' ]
25124 Internet status [ 'OK' ]
26126 Internet status [ 'OK' ]
27128 Internet status [ 'OK' ]
28127 Internet status [ 'OK' ]
29130 Internet status [ 'OK' ]
30128 Internet status [ 'OK' ]
30394 put [ '1646820489823' ]
active
replicated from remote: {"ok":true,"start_time":"2022-03-09T10:07:39.821Z","docs_read":2,"docs_written":2,"doc_write_failures":0,"errors":[],"last_seq":"81-g1AAAACbeJzLYWBgYMpgTmEQTM4vTc5ISXIwNDLXMwBCwxyQVCJDUv3___-zMpgT9XOBAuypqUapyclJ2DTgMSaPBUgyNACp_1DTlMCmGSQbGxgaG2LTlwUAbyYo6w","docs":[{"_id":"1646820489823","_rev":"1-8faebf904b39abb25f4ce960347896db","test":"foo"}],"pending":0}
31129 Internet status [ 'OK' ]
paused undefined
32132 Internet status [ 'OK' ]
33134 Internet status [ 'OK' ]
34132 Internet status [ 'OK' ]
35133 Internet status [ 'OK' ]
36132 Internet status [ 'OK' ]
```

**Comment by grahamdaw** [comment]
Thanks for testing the script & it's really interesting to see the output from your test. I'll have a dig into that and it'll be interesting to hear from others if there is similar behaviour.
