### ISSUE TITLE
Cannot read properties of null (reading '$eq') with null value in array and $elemMatch or $allMatch

### ISSUE THREAD

**Issue by paolosanchi** [pouchdb/pouchdb#8463]
### Issue
I found an issue with the .find() function for the local database.
If the value of an array is null, the operator $elemMatch and $allMatch don't work.

example:
document:
`       
{
	_id: '1',
	values: [null, null]
}
`
queries:
```
{
	selector: {
        	values: {$elemMatch: {$eq: null}},
	}
}

{
	selector: {
        	values: {$allMatch: {$eq: null}},
	}
}
```

Obtained error:
```
TypeError: Cannot read properties of null (reading '$eq')
    at getFieldFromDoc (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.find.js:3225:18)
    at http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.find.js:3972:25
    at Array.every (<anonymous>)
    at rowFilter (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.find.js:3969:25)
    at http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.find.js:4154:16
    at Array.every (<anonymous>)
    at Object.$allMatch (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.find.js:4153:28)
    at match (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.find.js:4049:32)
    at http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.find.js:3993:16
    at Array.every (<anonymous>)
```

I found that the issue is caused by in-memory-filter.js because the value null is mistaken for an object.
I've already fixed it and added the relative tests. I'll add a pull request soon.

**Comment by AlbaHerrerias** [comment]
Your fix https://github.com/pouchdb/pouchdb/pull/8465 has been merged to master, so I'm closing this issue. Thank you again!
