### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by topse** [pouchdb/pouchdb#8476]
### Issue
I am using pouchdb in a nextjs environment. I don't know, how long it can be used, but the problem can be reproduced here:

https://stackblitz.com/edit/github-x3cxgz?file=pages%2F_document.tsx

Or:

1. go to https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript
2. click on "open in Stackblitz"
3. npm install pouchdb-find pouchdb-browser
4. Add the following code to _document.js:

```
import * as PouchDB from 'pouchdb-browser';
import * as PouchFind from 'pouchdb-find';

PouchDB.plugin(PouchFind);
```

Then you get the error:
```
error - ReferenceError: self is not defined
ReferenceError: self is not defined
    at Object.<anonymous> (C:\Users\tobia\home\projects\opensetlist\node_modules\pouchdb-browser\lib\index.js:1031:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.pouchdb-browser (C:\Users\tobia\home\projects\opensetlist\.next\server\pages\_document.js:252:18)
    at __webpack_require__ (C:\Users\tobia\home\projects\opensetlist\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_document.tsx:15:73)
```

I have no idea what to do about this or where it comes from. I had a look at pouchdb-browser\lib\index.js:1031:24:

```
// this is not used in the browser

---> 1031  var setImmediateShim = self.setImmediate || self.setTimeout;
var MD5_CHUNK_SIZE = 32768;

function rawToBase64(raw) {
  return thisBtoa(raw);
}
```

... but I dont have a clue, what is wrong here :-/

Can anyone help?

Best Regards,
          Tobias

**Comment by shameen** [comment]
The nextjs template you have uses server-side rendering (SSR), but you're using the package `pouchdb-browser` which is for in-browser use only

Easiest solution in this case is to swap to the regular `pouchdb` package.
(You could instead remove all the SSR functionality if that suits your needs better)

**Comment by topse** [comment]
Doh :-//

Thanks and sorry for bothering...

Best Regards,
           Tobias
