### ISSUE TITLE
TypeError issue in the browser with `Object` being undefined (SSR with vite)

### ISSUE THREAD

**Issue by colearendt** [pouchdb/pouchdb#8535]
### Issue
When building a project using `pouchdb` with `vite` (`vite build`), everything runs smoothly when building or running the dev server, but then we get this when loading the SSR generated static files in the browser

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at Object.create.Ve.exports (index.70e0c1cf.js:32:921)
    at index.70e0c1cf.js:32:5677
```

Minified excerpt:
```
typeof Object.create=="function"?Ne.exports=function(t,n){n&&(t.super_=n,t.prototype=Object.create(n.prototype,{constructor:{value:t,enumerable:!1,writable:!0,configurable:!0}}))}:
```
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/23075542/181759210-792d9e12-742a-49dd-8d46-5b4e2328c2a4.png">

I have shimmed the `global` issue (#8516 ), but then am stuck on this one and cannot find exactly where this is defined. The closest I came was finding this code, which seems to match the minified version:

```
  module.exports = function inherits(ctor, superCtor) {
    ctor.super_ = superCtor
    ctor.prototype = Object.create(superCtor.prototype, {
      constructor: {
        value: ctor,
        enumerable: false,
        writable: true,
        configurable: true
      }
    });
  };
```
https://github.com/pouchdb/npm-browser/blob/41a57412d020a8a8acdf91d11deeb113ca39df0d/scripts/deps/pouchdb.load.js#L962-L972

### Info
- Environment: Node.js SSR, error shows up in the browser
- Platform:Chrome
- Adapter: indexeddb IIRC (the default)
- Server: CouchDB

### Reproduce
Minimalish fresh repo reproducing the issue (`vite`, `vue`, `vuetify`, and `pouchdb`). To build the site, `npm run build`
https://github.com/colearendt/js-issue-20220729

Live site: https://colearendt.github.io/js-issue-20220729/

### Opinions

It seems to me that `pouchdb` has a _lot_ of potential value in the SSR / PWA story. However, without some of these rough edges removed, I am likely to just implement my own client library for `CouchDB` using `axios` or something like that. I lose the benefit of local storage and sync, but at least I can build the site / host it cheaply 😄

**Comment by Anchakor** [comment]
FYI you might consider using the prebuilt bundles, that's how I got it working in service workers in modern stack:
https://github.com/pouchdb/pouchdb/issues/7973#issuecomment-1221635070

**Comment by sureshvv** [comment]
Is #8543 related?

**Comment by lokeshparmar998** [comment]
I am trying to use pouchdb with nuxt-3 and faced the same error "global is not defined". I fixed it by changing the builder in nuxt.config.ts from vite (default builder) to webpack 5.

`export default defineNuxtConfig({ builder: 'webpack' })`

Do not forget to install `@nuxt/webpack-builder` as a dev dependency.

And import it like this for typescript: `import * as PouchDB from '@/node_modules/pouchdb/dist/pouchdb'`

**Comment by colearendt** [comment]
Quiet stale-bot! This is still very much an issue 😄

**Comment by colearendt** [comment]
Yuck. I finally chased this code down in the `inherits` module. `npm explain inherits` suggests it is a super common dependency in the upstream dependency tree though 😞 

https://github.com/isaacs/inherits/blob/e6265134c91f9fb6a3d5e771f034ec94d20c6708/inherits_browser.js

**Comment by colearendt** [comment]
If I get time to go through all of the details of the shenanigans that I ran into and different options tried, I will. However, this solved the issue for me 🤷 :
```
npm install process events
```

**Comment by colearendt** [comment]
Not cool, stale bot. You lied to me!
