### ISSUE TITLE
Problems running pouchdb-quick-search with vite

### ISSUE THREAD

**Issue by sureshvv** [pouchdb/pouchdb#8543]
### Issue
at node_modules/pouchdb-promise/node_modules/lie/lib/index.js (index.js:13:1)
    at __require2 (chunk-S5KM4IGW.js?v=86ad731b:18:50)
    at node_modules/pouchdb-promise/src/index.js (index.js:1:17)
    at __init (chunk-S5KM4IGW.js?v=86ad731b:15:56)
    at node_modules/pouchdb-mapreduce-no-ddocs/node_modules/pouchdb-utils/src/adapterFun.js (adapterFun.js:1:1)
    at __init (chunk-S5KM4IGW.js?v=86ad731b:15:56)
    at node_modules/pouchdb-mapreduce-no-ddocs/node_modules/pouchdb-utils/src/index.js (index.js:1:1)
    at __init (chunk-S5KM4IGW.js?v=86ad731b:15:56)
    at node_modules/pouchdb-mapreduce-no-ddocs/src/index.js (index.js:1:1)
    at __init (chunk-S5KM4IGW.js?v=86ad731b:15:56)

    process.nextTick(function () {
        updateView(view);
     });

### Info
- Environment: Using Vite to build and deploy Node.js/browser
- Platform: Chrome
- Adapter: indexeddb
- Server: CouchDB

### Reproduce
vite build

**Comment by ramblin-rose** [comment]
#8266

**Comment by sureshvv** [comment]
@ramblin-rose I checked this issue and followed all the instructions in it and the problem persists.

I have 2 questions.

1. The traceback seems to start from pouchdb-promise which may not be needed anymore. Can I get rid of it?
2. The process which is used in pouchdb-mapreduce-no-ddocs/src/index.js is not imported from anywhere. Should it be qualified?

**Comment by sureshvv** [comment]
It appears that pouchdb-quick-search@1.3.0 is the culprit.

**Comment by sureshvv** [comment]
https://github.com/pouchdb-community/pouchdb-quick-search/issues/106
