### ISSUE TITLE
error with putAttachment

### ISSUE THREAD

**Issue by Productivix** [pouchdb/pouchdb#8550]
### Issue
Error when adding an attachment

`Error
    at new CustomPouchError (C:\test_njs_pouchdb\node_modules\pouchdb\lib\index.js:656:21)
    at createError (C:\test_njs_pouchdb\node_modules\pouchdb\lib\index.js:665:10)
    at C:\test_njs_pouchdb\node_modules\pouchdb\lib\index.js:1830:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 409,
  name: 'conflict',
  message: 'Document update conflict',
  error: true
}`
### Info
- Environment: (Node.js) v16.14.1
- Platform: Windws 10
- Adapter: ? no
- Server: CouchDB last version

### Reproduce
in Node : here is the code , issued from the API reference : https://pouchdb.com/api.html#save_attachment
before : yarn add pouchdb
"dependencies": {
    "pouchdb": "^7.3.0"
  }

Code : of AddAttachment.js
```
//Requiring the package
var PouchDB = require("pouchdb");

//Creating the database object
var db = new PouchDB("mydatabase");

//Preparing the attachment
var myattachment = "Welcome to tutorialspoint";

//Adding attachment to a document
db.putAttachment(
  "001",
  "att.txt",
  myattachment,
  "text/plain",
  function (err, res) {
    if (err) {
      return console.log(err);
    }
  }
);

```
call : node ./AddAttachment.js
and you get the error listed at the beginning

**Comment by DarrenCook** [comment]
Your example differs from the one in the documentation you linked to, as you are passing a string, whereas you are supposed to wrap it in a Blob or Buffer:
`var attachment = new Blob(['Is there life on Mars?'], {type: 'text/plain'});`

But it is strange you get a 409. So I think that is because you have run this test code more than once, and the document already exists? If you want to be able to do that you need to either first wipe out any existing DB of the same name like this:

```
await new PouchDB("mydatabase").destroy().catch(e => {});
var db = new PouchDB("mydatabase");
```

(The `catch` is to suppress errors about it not existing; not recommended for production code!)

Or delete the document, before creating it:

```
await db.remove("001").catch(e => {});
db.putAttachment(...)
```

Or the other way is to do `db.get("001")` to see if it exists, and if so then pass the `_rev` to the `putAttachment()` call.

**Comment by Productivix** [comment]
thanks but I am using Node ,so "Blob" is incorrect first , then if use "Buffer", we have a warning , I have 001 record  without attachement : 
here is the code upgraded , you can test yourself : 

`//Requiring the package
var PouchDB = require("pouchdb");

//Creating the database object,
var db = new PouchDB("mydatabase");

//Preparing the attachment : a blob /Buffer in Node
var myattachment = new Buffer("Is there life on Mars?");

//Reading the contents of a Document
db.get("001", function (err, doc) {
  if (err) {
    return console.log(err);
  } else {
    console.log(doc);
  }
});

//Adding attachment to a document
db.remove("001").catch((e) => {});
db.putAttachment(
  "001",
  "att.txt",
  myattachment,
  "text/plain",
  function (err, res) {
    if (err) {
      return console.log(err);
    }
  }
);`

then you get the response : 
`$ node ./AddAttachment.js
(node:35946) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
{
  name: 'Ram',
  age: 32,
  Designation: 'Programmer',
  _id: '001',
  _rev: '8-3e62c3c12f90ff736153e6f9c3078956'
}
Error
    at new CustomPouchError (/home/test_njs_pouchdb/node_modules/pouchdb/lib/index.js:656:21)
    at createError (/home/test_njs_pouchdb/node_modules/pouchdb/lib/index.js:665:10)
    at /home/test_njs_pouchdb/node_modules/pouchdb/lib/index.js:1830:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 409,
  name: 'conflict',
  message: 'Document update conflict',
  error: true`

**Comment by Productivix** [comment]
news please @DarrenCook ?

**Comment by DarrenCook** [comment]
If the problems continue you might want to try asking on StackOverflow.
But 409 handling is the most fundamental part of working with Pouch/CouchDB, and it is generally a right pain, so get used to it.

You are missing the `await` on the `db.remove()` (and you will also want one on the `db.putAttachment()` too). Oh, and one on the `db.get()` too!

So maybe I should have said understanding async is the most fundamental part of working with PouchDB. Then 409s :-)

P.S. Use triple backquotes in markdown for blocks of code, and it will keep the indent formatting.

**Comment by Productivix** [comment]
hi, 
yes I know that I should "await" but you cannot put an await in front : I correct that (but warning if "await" in front of "db.get")
At the origin, I refer to the doc that should be right :and I wrote : 
" in Node : here is the code , issued from the API reference : https://pouchdb.com/api.html#save_attachment"
(the doc is not correct, so I try to find a solution, or the program is bugged) 

I corrected the issue on Buffer but still have the problem at put attachment : 
```
//Requiring the package
var PouchDB = require("pouchdb");

//Creating the database object,
var db = new PouchDB("mydatabase");

//Reading the contents of a Document (no await)
db.get("001", function (err, doc) {
  if (err) {
    return console.log(err);
  } else {
    console.log("1st log:", doc);
  }
});
/* I get : 
1st log: {
  name: 'Ram',
  age: 32,
  Designation: 'Programmer',
  _id: '001',
  _rev: '8-3e62c3c12f90ff736153e6f9c3078956'
}
*/

const attach = async () => {
  try {
    //var attachment = new Blob(['Is there life on Mars?'], {type: 'text/plain'});//no, a buffer in Node
    var attachment = new Buffer.from("Is there life on Mars?", "utf8"); //in Node
    var result = await db.putAttachment(
      "001",
      "att.txt",
      attachment,
      "text/plain"
    ); //here is an error
    console.log("result:", result);
    //Reading the contents of a Document after
    db.get("001", function (err, doc) {
      if (err) {
        return console.log(err);
      } else {
        console.log(doc);
      }
    });
  } catch (err) {
    console.log(err);
  }
};

attach();
```
thanks for suggestions or solutions

**Comment by Productivix** [comment]
hello, 
I see the doc on [https://pouchdb.com/api.html#save_attachment](https://pouchdb.com/api.html#save_attachment )
has changed, 
but still bugged , even with new
 ```
"dependencies": {
    "pouchdb": "^8.0.0"
  }
```
allways "conflict: "Document update conflict"
(and 
//Creating the database object var db = new PouchDB('my_database'); in comment is a so big mistake.)

**Comment by Productivix** [comment]
Hi
here is the solution : be carefull to know whether the doc to which you add an attachment exists or not  !
In my case , I did not wrote it was existing (!) , sorry.

so the code newlook that runs is : with lany remarks : 

```

//Requiring the package
var PouchDB = require("pouchdb");

//Creating the database object,
let db = new PouchDB("mydatabase");
let attachment = new Buffer.from("Is there life on Mars?", "utf8"); //in Node
//or :
let my_attachment = new Buffer.from(["Welcome to tutorialspoint"], {
  type: "text/plain",
});
//var attachment = new Blob(['Is there life on Mars?'], {type: 'text/plain'});//NO, use a buffer in Node

console.log("buffer attachements crées");

const rev = async (doc) => {
  let resultrev = await db.get(doc);
  return resultrev._rev;
};

const attach = async (doc) => {
  try {
    let revdoc = await rev(doc);
    let result = await db.putAttachment(
      doc,
      "att.txt",
      revdoc,
      my_attachment,
      "text/plain"
    ); // or with attachment instead of my_attachment
    console.log("result:", result);
    //Reading the contents of a Document after
    db.get(doc, function (err, doc) {
      if (err) {
        return console.log(err);
      } else {
        console.log(doc);
      }
    });
  } catch (err) {
    console.log(err);
  }
};

attach("001"); //important : the doc '001' already exists in db

/* runs on existing doc : put the revision , in this order,
db.putAttachment(
  "001",
  "att_1.txt",
  rev,
  my_attachment,
  "text/plain",
  function (err, res) {
    if (err) {
      return console.log(err);
    } else {
      console.log(res + "Attachment added successfully");
    }
  }
);
*/

//data with attachement : runs ok
/* var doc = {
  _id: "doc",
  title: "Legendary Hearts",
  _attachments: {
    "att.txt": {
      content_type: "text/plain",
      data: new Buffer(["And she's hooked to the silver screen"], {
        type: "text/plain",
      }),
    },
    "att2.txt": {
      content_type: "text/plain",
      data: new Buffer(["But the film is a saddening bore"], {
        type: "text/plain",
      }),
    },
  },
};
db.put(doc, function (err, result) {
  if (err) {
    return console.log(err);
  }
  // handle result
});
*/

```
