### ISSUE TITLE
Javascript new PouchDB parameters and examples for no-cors for COUCH

### ISSUE THREAD

**Issue by digimbyte** [pouchdb/pouchdb#8556]
Documentation is utterly useless.
As title says, HOW DO YOU DEFINE NO-CORS?
```
from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
I found some jank code on how to intercept the actual fetch request, with no idea if that even does anything. 
```
new PouchDB(couchdb,
                    {
                        //no-cors ??
                        fetch: function (url, opts) {
                            opts.crossOrigin = false;
                            opts.headers.set('X-Some-Special-Header', 'foo');
                            return PouchDB.fetch(url, opts);
                        }
                    });
```
beyond that, I have searched high and low for ANY breadcrumb all the way back to couchdb v1 integration on how to define cross origin definitions or worst case, disable cors entirely.

and if its documented, show me where.
the information available is on par with the international standard cup of tea.

**Comment by digimbyte** [comment]
I managed to set the 'opts.mode' to 'no-cors' which removed the no-cors error but it hasn't been passing the credentials at all.
the url contains the username and password as `http://username:password@ip:port`

**Comment by digimbyte** [comment]
not sure if it is related:
I am having this message show after the GET request
`ERR SyntaxError: Unexpected end of input (at pouchdb.min.js:7:101753)
    at pouchdb.min.js:7:101753`

**Comment by ramblin-rose** [comment]
How is the couchDB CORS configured? FWIW [StackOverflow](https://stackoverflow.com) is replete with CORS/pouchDB Q/A's, for example [this](https://stackoverflow.com/questions/20897033/how-to-add-cors-in-couchdb-no-access-control-allow-origin-header-is-present)

**Comment by digimbyte** [comment]
default configuration, all interaction is direct IP, 
Cors has been disabled at this current time with 
if CORS configuration changes are required from Pouch to work, it should be outlined in the setup page.
I can connect to our couch instance using Nano for server/node requests.
This is a situation where we need a UI/client integration so it is limited to the web browser environment.

**Comment by alxndrsn** [comment]
CORS configuration is done on the remote end of any HTTP server PouchDB connects to.

You can see some discussion of enabling CORS on *CouchDB* at https://github.com/pouchdb/add-cors-to-couchdb.
