### ISSUE TITLE
How is this possible? 

### ISSUE THREAD

**Issue by mike-niemand** [pouchdb/pouchdb#8610]
Hi All,

In index-browser.es.js there is a once function:

`
function once(fun) {
    var called = false;
  return function (...args) {
    /* istanbul ignore if */
    if (called) {
      // this is a smoke test and should never actually happen
      throw new Error('once called more than once');
    } else {
      called = true;
      fun.apply(this, args);
    }
  };
}
`

How is that error being thrown? I have it popping up in Sentry occasionally.

_Error: once called more than once
  at callback (./node_modules/pouchdb/lib/index-browser.es.js:205:1)
  at <anonymous> (./node_modules/pouchdb/lib/index-browser.es.js:6415:1)_

**Comment by mike-niemand** [comment]
Apologies. I must have broken it somehow. Working after reinstalling.
