### ISSUE TITLE
ci: test-webpack failures show misleading error messages

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8667]
There seems to be a commonly-occurring error in CI relating to `test-webpack.sh`:

```
Error: 'default' is not exported by node_modules/inherits/inherits.js
```

See e.g.

* https://github.com/pouchdb/pouchdb/actions/runs/5313910108/jobs/9620480887#step:4:1592
* https://github.com/pouchdb/pouchdb/pull/8666#issuecomment-1597199001
* https://github.com/pouchdb/pouchdb/pull/8569#issuecomment-1523449019

This may be a race condition, as https://github.com/pouchdb/pouchdb/actions/runs/5313910108/jobs/9620480887#step:4:1592 was re-run successfully.

Full example log from https://github.com/pouchdb/pouchdb/actions/runs/5313910108/jobs/9620480887#step:4:1592:

```
CLIENT=selenium:firefox npm run test-webpack
  shell: /usr/bin/bash -e {0}
  env:
    NODE_VERSION: 14
    SELENIUM_HUB_HOST: hub
    TEST_HOST: localhost

> pouchdb-monorepo@7.0.0-prerelease test-webpack
> ./bin/test-webpack.sh


> pouchdb-monorepo@7.0.0-prerelease build
> npm run build-modules && npm run build-test


> pouchdb-monorepo@7.0.0-prerelease build-modules
> node bin/build-modules.js

Building pouchdb...
Building pouchdb-abstract-mapreduce...
Building pouchdb-adapter-http...
Building pouchdb-adapter-idb...
Building pouchdb-adapter-indexeddb...
Building pouchdb-adapter-leveldb...
Building pouchdb-adapter-leveldb-core...
Building pouchdb-adapter-localstorage...
Building pouchdb-adapter-memory...
Building pouchdb-adapter-utils...
Building pouchdb-browser...
Building pouchdb-binary-utils...
Building pouchdb-changes-filter...
Building pouchdb-checkpointer...
Building pouchdb-collate...
Building pouchdb-collections...
Building pouchdb-core...
Building pouchdb-errors...
Building pouchdb-fetch...
Building pouchdb-find...
Building pouchdb-for-coverage...
Building pouchdb-generate-replication-id...
Building pouchdb-json...
Building pouchdb-mapreduce...
Building pouchdb-mapreduce-utils...
Building pouchdb-md5...
Building pouchdb-merge...
Building pouchdb-node...
Building pouchdb-replication...
Building pouchdb-selector-core...
Building pouchdb-utils...
Building sublevel-pouchdb...
  ✓ wrote pouchdb-adapter-localstorage/lib/index.js in vanilla mode
  ✓ wrote pouchdb-adapter-localstorage/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-adapter-memory/lib/index.js in vanilla mode
  ✓ wrote pouchdb-adapter-memory/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-checkpointer/lib/index.js in vanilla mode
  ✓ wrote pouchdb-checkpointer/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-errors/lib/index.js in vanilla mode
  ✓ wrote pouchdb-errors/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-generate-replication-id/lib/index.js in vanilla mode
  ✓ wrote pouchdb-generate-replication-id/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-adapter-http/lib/index.js in vanilla mode
  ✓ wrote pouchdb-adapter-http/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-adapter-leveldb/lib/index.js in node mode
  ✓ wrote pouchdb-adapter-leveldb/lib/index.es.js in node mode
  ✓ wrote pouchdb-adapter-leveldb/lib/index-browser.js in browser mode
  ✓ wrote pouchdb-adapter-leveldb/lib/index-browser.es.js in browser mode
  ✓ wrote pouchdb-adapter-leveldb-core/lib/index.js in node mode
  ✓ wrote pouchdb-adapter-leveldb-core/lib/index.es.js in node mode
  ✓ wrote pouchdb-adapter-leveldb-core/lib/index-browser.js in browser mode
  ✓ wrote pouchdb-adapter-leveldb-core/lib/index-browser.es.js in browser mode
'pouchdb-adapter-idb' is imported by packages/node_modules/pouchdb-browser/src/index.js, but could not be resolved – treating it as an external dependency
  ✓ wrote pouchdb-changes-filter/lib/index.js in node mode
  ✓ wrote pouchdb-changes-filter/lib/index.es.js in node mode
  ✓ wrote pouchdb-changes-filter/lib/index-browser.js in browser mode
  ✓ wrote pouchdb-changes-filter/lib/index-browser.es.js in browser mode
  ✓ wrote pouchdb-collate/lib/index.js in vanilla mode
  ✓ wrote pouchdb-collate/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-fetch/lib/index.js in node mode
  ✓ wrote pouchdb-fetch/lib/index.es.js in node mode
  ✓ wrote pouchdb-fetch/lib/index-browser.js in browser mode
  ✓ wrote pouchdb-fetch/lib/index-browser.es.js in browser mode
  ✓ wrote pouchdb-json/lib/index.js in vanilla mode
  ✓ wrote pouchdb-json/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-mapreduce-utils/lib/index.js in vanilla mode
  ✓ wrote pouchdb-mapreduce-utils/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-md5/lib/index.js in node mode
  ✓ wrote pouchdb-md5/lib/index.es.js in node mode
  ✓ wrote pouchdb-md5/lib/index-browser.js in browser mode
  ✓ wrote pouchdb-md5/lib/index-browser.es.js in browser mode
  ✓ wrote pouchdb-abstract-mapreduce/lib/index.js in vanilla mode
  ✓ wrote pouchdb-abstract-mapreduce/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-adapter-idb/lib/index.js in vanilla mode
  ✓ wrote pouchdb-adapter-idb/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-adapter-indexeddb/lib/index.js in vanilla mode
  ✓ wrote pouchdb-adapter-indexeddb/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-adapter-utils/lib/index.js in vanilla mode
  ✓ wrote pouchdb-adapter-utils/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-binary-utils/lib/index.js in node mode
  ✓ wrote pouchdb-binary-utils/lib/index.es.js in node mode
  ✓ wrote pouchdb-binary-utils/lib/index-browser.js in browser mode
  ✓ wrote pouchdb-binary-utils/lib/index-browser.es.js in browser mode
  ✓ wrote pouchdb-collections/lib/index.js in vanilla mode
  ✓ wrote pouchdb-collections/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-merge/lib/index.js in vanilla mode
  ✓ wrote pouchdb-merge/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-selector-core/lib/index.js in vanilla mode
  ✓ wrote pouchdb-selector-core/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-utils/lib/index.js in node mode
  ✓ wrote pouchdb-utils/lib/index.es.js in node mode
  ✓ wrote pouchdb-utils/lib/index-browser.js in browser mode
  ✓ wrote pouchdb-utils/lib/index-browser.es.js in browser mode
  ✓ wrote sublevel-pouchdb/lib/index.js in vanilla mode
  ✓ wrote sublevel-pouchdb/lib/index.es.js in vanilla mode
  ✓ wrote pouchdb-mapreduce/lib/index.js in node mode
  ✓ wrote pouchdb-mapreduce/lib/index.es.js in node mode
  ✓ wrote pouchdb-mapreduce/lib/index-browser.js in browser mode
  ✓ wrote pouchdb-mapreduce/lib/index-browser.es.js in browser mode
  ✓ wrote pouchdb-replication/lib/index.js in vanilla mode
  ✓ wrote pouchdb-replication/lib/index.es.js in vanilla mode
'pouchdb-mapreduce' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-mapreduce' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-replication' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-replication' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
Circular dependency: packages/node_modules/pouchdb-core/src/setup.js -> packages/node_modules/pouchdb-core/src/constructor.js -> packages/node_modules/pouchdb-core/src/adapter.js -> packages/node_modules/pouchdb-core/src/changes.js -> packages/node_modules/pouchdb-core/src/setup.js
Circular dependency: packages/node_modules/pouchdb-core/src/constructor.js -> packages/node_modules/pouchdb-core/src/parseAdapter.js -> packages/node_modules/pouchdb-core/src/constructor.js
  ✓ wrote pouchdb-core/lib/index.js in vanilla mode
  ✓ wrote pouchdb-core/lib/index.es.js in vanilla mode
'pouchdb-core' is imported by packages/node_modules/pouchdb-browser/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-core' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-core' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-core' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-core' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-core' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-core' is imported by packages/node_modules/pouchdb-adapter-leveldb-core/lib/index.es.js, but could not be resolved – treating it as an external dependency
'pouchdb-mapreduce' is imported by packages/node_modules/pouchdb-browser/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-mapreduce' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-replication' is imported by packages/node_modules/pouchdb-browser/src/index.js, but could not be resolved – treating it as an external dependency
'pouchdb-replication' is imported by packages/node_modules/pouchdb-node/src/index.js, but could not be resolved – treating it as an external dependency
  ✓ wrote pouchdb-find/lib/index.js in node mode
  ✓ wrote pouchdb-find/lib/index.es.js in node mode
  ✓ wrote pouchdb-find/lib/index-browser.js in browser mode
  ✓ wrote pouchdb-find/lib/index-browser.es.js in browser mode
Circular dependency: packages/node_modules/pouchdb-utils/lib/index-browser.es.js -> packages/node_modules/pouchdb-utils/lib/index-browser.es.js
Circular dependency: packages/node_modules/pouchdb-collections/lib/index.es.js -> packages/node_modules/pouchdb-collections/lib/index.es.js
  ✓ wrote pouchdb-browser/lib/index.js in vanilla mode
  ✓ wrote pouchdb-browser/lib/index.es.js in vanilla mode
Circular dependency: packages/node_modules/pouchdb-utils/lib/index.es.js -> packages/node_modules/pouchdb-utils/lib/index.es.js
Circular dependency: packages/node_modules/pouchdb-collections/lib/index.es.js -> packages/node_modules/pouchdb-collections/lib/index.es.js
  ✓ wrote pouchdb-node/lib/index.js in vanilla mode
  ✓ wrote pouchdb-node/lib/index.es.js in vanilla mode
build error
Error: 'default' is not exported by node_modules/inherits/inherits.js
    at error (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:13349:9)
    at handleMissingExport (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:13039:21)
    at Module.traceVariable (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:13453:17)
    at ModuleScope.findVariable (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:12726:29)
    at Identifier$$1.bind (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:10111:40)
    at CallExpression.NodeBase.bind (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:9183:23)
    at CallExpression.bind (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:10224:31)
    at ExpressionStatement$$1.NodeBase.bind (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:9183:23)
    at Program.NodeBase.bind (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:9179:31)
    at Module.bindReferences (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:13303:18)
    at Graph.link (/home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:21489:20)
    at /home/runner/work/pouchdb/pouchdb/node_modules/rollup/dist/rollup.js:21584:19
    at async Promise.all (index 0)
    at async Promise.all (index 20)
Error: Process completed with exit code 1.
```

**Comment by alxndrsn** [comment]
This seems to happen if `npm run build` is called after `./bin/test-webpack.sh`.  This means that if the first attempt at `test-webpack` fails in CI for legitimate reasons, the first and second retries will fail with `...'default' is not exported...` instead of the actual cause of the problem.

Suggestions:

* `git reset --hard` could be run to revert changes to `node_modules/packages/*/package.json` files before `test-webpack` is re-run.
* `test-webpack` could fail fast if the git working copy is dirty

**Comment by alxndrsn** [comment]
Repro:

```sh
node bin/update-package-json-for-publish.js &&
CLIENT=firefox npm run test-webpack
```
