### ISSUE TITLE
Frequent test failure: test.retry.js-http-local target doesn't leak "destroyed" event

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8689]
https://github.com/pouchdb/pouchdb/actions/runs/5372105205/jobs/9745435702#step:5:1465
```
  1) test.retry.js-http-local target doesn't leak "destroyed" event:
     AssertionError: numListeners should never increase by +1/-1: expected 6 to be within 2..4
      at Hn.<anonymous> (test.retry.js:283:40)
      at d (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:1629)
      at s.emit (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:4615)
      at C (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:133666)
```

https://github.com/pouchdb/pouchdb/actions/runs/5372099418/jobs/9745289725#step:5:1458
```
  1) test.retry.js-http-local target doesn't leak "destroyed" event:
     AssertionError: numListeners should never increase by +1/-1: expected 6 to be within 2..4
      at Hn.<anonymous> (test.retry.js:283:40)
      at d (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:1629)
      at s.emit (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:4615)
      at C (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:133666)
```

https://github.com/pouchdb/pouchdb/actions/runs/5372105205/jobs/9745435702#step:6:1458
```
   1) test.retry.js-http-local target doesn't leak "destroyed" event:
     AssertionError: numListeners should never increase by +1/-1: expected 6 to be within 2..4
      at Hn.<anonymous> (test.retry.js:283:40)
      at d (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:1629)
      at s.emit (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:4615)
      at C (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:133666)
```

https://github.com/pouchdb/pouchdb/actions/runs/5372099418/jobs/9745289428#step:5:1461
```
  1) test.retry.js-http-local target doesn't leak "destroyed" event:
     AssertionError: numListeners should never increase by +1/-1: expected 6 to be within 2..4
      at Hn.<anonymous> (test.retry.js:283:40)
      at d (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:1629)
      at s.emit (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:4615)
      at C (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:133666)
```

https://github.com/pouchdb/pouchdb/actions/runs/5328503152/jobs/9653604140#step:5:1453
```
  1) test.retry.js-http-local target doesn't leak "destroyed" event:
     AssertionError: numListeners should never increase by +1/-1: expected 5 to be within 2..4
      at Hn.<anonymous> (test.retry.js:283:40)
      at d (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:1629)
      at s.emit (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:4615)
      at C (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:133666)
```

**Comment by alxndrsn** [comment]
Test relates to https://github.com/pouchdb/pouchdb/issues/3699.

**Comment by alxndrsn** [comment]
Closing as ancient.  Open new issues if there are intermittent failures in the test suite.
