### ISSUE TITLE
Frequent test failure: test.issue3179.js-local-http #3179 conflicts synced, non-live sync

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8690]
https://github.com/pouchdb/pouchdb/actions/runs/5372099418/jobs/9745290104#step:4:1362
```
  1) test.issue3179.js-local-http #3179 conflicts synced, non-live sync:
     TypeError: Cannot read properties of undefined (reading '0')
      at tests/integration/test.issue3179.js:85:54
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

https://github.com/pouchdb/pouchdb/actions/runs/5328992647/jobs/9654247095#step:5:4629
```
   1) test.issue3179.js-local-http #3179 conflicts synced, non-live sync:
     TypeError: Cannot read property '0' of undefined
      at tests/integration/test.issue3179.js:85:54
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

https://github.com/pouchdb/pouchdb/actions/runs/5372099418/jobs/9745289133#step:4:1360
```
  1) test.issue3179.js-local-http #3179 conflicts synced, non-live sync:
     TypeError: Cannot read properties of undefined (reading '0')
      at tests/integration/test.issue3179.js:85:54
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by SourceR85** [comment]
https://github.com/pouchdb/pouchdb/actions/runs/6509460488/job/17681109144?pr=8775#step:4:4609
```
  1) test.issue3179.js-local-http #3179 conflicts synced, non-live sync:
     AssertionError: conflicts expected, but none were found: expected undefined to exist
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at Assertion.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:286:25)
      at Assertion.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at Object.should.exist (node_modules/chai/lib/chai/interface/should.js:126:34)
      at tests/integration/test.issue3179.js:86:18
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by alxndrsn** [comment]
Closing as ancient.  Open new issues if there are intermittent failures in the test suite.
