### ISSUE TITLE
Frequent test failure: "after each" hook for "Changes with invalid ddoc view name 2"

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8693]
https://github.com/pouchdb/pouchdb/actions/runs/5372099418/jobs/9745288441#step:5:316
```
1)  "after each" hook for "Changes with invalid ddoc view name 2":
     Error: done() invoked with non-Error: {"id":"0ad5a70d80de8147aa800b8543012c49","error":"unknown_error","reason":"undefined","name":"unknown_error","status":500,"message":"undefined","stack":"Error\n    at W (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:39916)\n    at [http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:103340\n](http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:103340/n)    at Array.map (<anonymous>)\n    at u (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:103297)\n    at async r._bulkDocs (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:108035)"}
      at Context.<anonymous> (test.setup_global_hooks.js:24:3)
```

**Comment by alxndrsn** [comment]
Closing as ancient.  Open new issues if there are intermittent failures in the test suite.
