### ISSUE TITLE
Frequent test failure: "after each" hook for "Changes with style = all_docs"

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8694]
https://github.com/pouchdb/pouchdb/actions/runs/5339252762/jobs/9713918736#step:5:317
```
1)  "after each" hook for "Changes with style = all_docs":
     Error: done() invoked with non-Error: {"id":"110dba6901e7d9971f30f57b8f00fee6","error":"unknown_error","reason":"undefined","name":"unknown_error","status":500,"message":"undefined","stack":"Error\n    at W (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:39916)\n    at [http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:103340\n](http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:103340/n)    at Array.map (<anonymous>)\n    at u (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:103297)\n    at async r._bulkDocs (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:108035)"}
      at Context.<anonymous> (test.setup_global_hooks.js:24:3)
```

**Comment by alxndrsn** [comment]
Closing as ancient.  Open new issues if there are intermittent failures in the test suite.
