### ISSUE TITLE
Intermittent test failure: test.sync.js-http-local 5782 sync rev-1 conflicts

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8696]
https://github.com/pouchdb/pouchdb/actions/runs/5339252762/jobs/9713923413#step:4:2181
```
1) test.sync.js-http-local 5782 sync rev-1 conflicts:

      AssertionError: expected { Object (total_rows, offset, ...) } to deeply equal { Object (total_rows, offset, ...) }
      + expected - actual

         "rows": [
           {
             "doc": {
               "_id": "random-1687385651093"
      -        "_rev": "1-18daa9a6572dc3e4dec9f60795bb8ebe"
      -        "baz": "fubar"
      +        "_rev": "1-55e763278f3fb77b7d9a63ef12b0143e"
               "foo": "bar"
             }
             "id": "random-1687385651093"
             "key": "random-1687385651093"
             "value": {
      -        "rev": "1-18daa9a6572dc3e4dec9f60795bb8ebe"
      +        "rev": "1-55e763278f3fb77b7d9a63ef12b0143e"
             }
           }
           {
             "doc": {
      
      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.<computed> (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at Assertion.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:21)
      at Assertion.ctx.<computed> [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at tests/integration/test.sync.js:901:28
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by alxndrsn** [comment]
Closing as ancient.  Open new issues if there are intermittent failures in the test suite.
