### ISSUE TITLE
Intermittent test failure: test.mapreduce.js-temp should query correctly with a variety of criteria

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8698]
https://github.com/pouchdb/pouchdb/actions/runs/5316742697/jobs/9626599160#step:5:3770
```
  1) test.mapreduce.js-temp should query correctly with a variety of criteria:
     missing
  Error
      at generateErrorFromResponse (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.js:3387:18)
      at fetchJSON (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.js:9731:19)
      at async http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.js:10104:22
```

**Comment by alxndrsn** [comment]
Closing as ancient.  Open new issues if there are intermittent failures in the test suite.
