### ISSUE TITLE
Intermittent test failure: test.mapreduce.js-temp should query correctly with skip/limit and multiple keys/values

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8699]
https://github.com/pouchdb/pouchdb/actions/runs/5328500385/jobs/9653602099#step:5:337
```

  1) test.mapreduce.js-temp should query correctly with skip/limit and multiple keys/values:

      AssertionError: expected [ Array(12) ] to deeply equal [ Array(12) ]
      + expected - actual

       [
      -  "multiple values!"
      +  [null]
         "crayon!"
         "crayon!"
      +  "multiple values!"
         [null]
      -  "multiple values!"
         "crayon!"
         "crayon!"
      +  "multiple values!"
         [null]
      -  [null]
         "fooValue"
         [null]
         "fooValue"
       ]
      
      at Assertion.assertEqual (http://127.0.0.1:8000/node_modules/chai/chai.js:774:19)
      at ctx.<computed> (http://127.0.0.1:8000/node_modules/chai/chai.js:4192:25)
      at doAsserterAsyncAndAddThen (http://127.0.0.1:8000/node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at Assertion.<anonymous> (http://127.0.0.1:8000/node_modules/chai-as-promised/lib/chai-as-promised.js:255:21)
      at ctx.<computed> [as equal] (http://127.0.0.1:8000/node_modules/chai/chai.js:5341:33)
      at test.mapreduce.js:2745:47
```

**Comment by alxndrsn** [comment]
Closing as ancient.  Open new issues if there are intermittent failures in the test suite.
