### ISSUE TITLE
Intermittent test failure: test.bulk_docs.js-http #6039 test id in bulk docs for conflict

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8700]
https://github.com/pouchdb/pouchdb/actions/runs/5326757967/jobs/9649268649#step:5:3762
```
  1) test.bulk_docs.js-http #6039 test id in bulk docs for conflict:

      AssertionError: expected [ Array(5) ] to deeply equal [ Array(5) ]
      + expected - actual

           "id": "1"
           "rev": "rev_placeholder"
         }
         {
      -    "id": "3"
      -    "rev": "rev_placeholder"
      -  }
      -  {
           "error": true
           "id": "2"
           "name": "conflict"
           "status": 409
         }
         {
      +    "id": "3"
      +    "rev": "rev_placeholder"
      +  }
      +  {
           "error": true
           "id": "4"
           "name": "conflict"
           "status": 409
      
      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.<computed> (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at Assertion.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:21)
      at Assertion.ctx.<computed> [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at tests/integration/test.bulk_docs.js:121:25
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by alxndrsn** [comment]
I suspect the `http` adapter does not guarantee order of results and/or inserts using `bulkDocs()`.

**Comment by alxndrsn** [comment]
Closing as ancient.  Open new issues if there are intermittent failures in the test suite.
