### ISSUE TITLE
PouchDB in Nextjs throws error

### ISSUE THREAD

**Issue by spiritanand** [pouchdb/pouchdb#8754]
### Issue
Whenever I try running my nextjs app using pouchDB (I am only using it on the server side and **NOT** on the client side) I get
<img width="1021" alt="image" src="https://github.com/pouchdb/pouchdb/assets/53999998/daab3e91-bbb1-439c-aa13-3ae25078d8ca">

Am I missing something?

### Info
- Environment: (Nextjs (backend code Node.js))
- Platform: (Brave)
- Adapter: (leveldb)
- Server: (no server, I am working in local with in nextjs)

### Reproduce
Initi a nextjs app. Setup pouchDB
```
import PouchDB from "pouchdb-node";
const db = new PouchDB("llmshare");
export default db;
```

use pouchDB in any API's `route.ts`
```
import { NextResponse } from "next/server";
import db from "@/db/pouchDB";

export async function GET() {
  try {
    const res = await db.post({ title: "new code" });

    return NextResponse.json({ id: res.id });
  } catch (e) {
    console.log({ e });
  }
}
```

**Comment by jagnani73** [comment]
Facing the same issue

**Comment by jagnani73** [comment]
> Facing the same issue, except I'm only using it on the client side, not the server side

```shell
- error node_modules/node-gyp-build/index.js (56:0) @ load.path
- error Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc
    at __webpack_require__ (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/webpack-runtime.js:33:43)
    at eval (./utils/services/pouch.ts:6:65)
    at (ssr)/./utils/services/pouch.ts (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/app/tx/[tx_hash]/page.js:12178:1)
    at __webpack_require__ (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/webpack-runtime.js:33:43)
    at eval (./components/shared/addresses-layout/addresses-layout.tsx:20:79)
    at (ssr)/./components/shared/addresses-layout/addresses-layout.tsx (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/app/tx/[tx_hash]/page.js:10671:1)
    at __webpack_require__ (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/webpack-runtime.js:33:43)
    at eval (./components/shared/addresses-layout/index.tsx:6:75)
    at (ssr)/./components/shared/addresses-layout/index.tsx (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/app/tx/[tx_hash]/page.js:10704:1)
    at __webpack_require__ (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/webpack-runtime.js:33:43)
    at eval (./components/shared/index.tsx:13:75)
    at (ssr)/./components/shared/index.tsx (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/app/tx/[tx_hash]/page.js:11001:1)
    at __webpack_require__ (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/webpack-runtime.js:33:43)
    at eval (./components/tx/tx.tsx:17:76)
    at (ssr)/./components/tx/tx.tsx (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/app/tx/[tx_hash]/page.js:11287:1)
    at __webpack_require__ (/media/gizmoclardin/Yashvardhan/Work/covalent/goldrush/.next/server/webpack-runtime.js:33:43)
    ```

**Comment by alxndrsn** [comment]
@jagnani73 are you using the [`pouchdb-browser`](https://www.npmjs.com/package/pouchdb-browser) module?  It might also be worth trying to include it from a CDN (see https://pouchdb.com/download.html#cdn).

**Comment by alxndrsn** [comment]
@spiritanand the error message suggests that the `leveldown` version doesn't support Apple Silicon.

Similar issues:

* https://github.com/pouchdb/pouchdb/issues/8526
* https://github.com/pouchdb/pouchdb/issues/8416

Upgrading pouchdb's `leveldown` dependency may fix this (https://github.com/Level/leveldown/issues/766).

There are some open PRs attempting to do this:

* https://github.com/pouchdb/pouchdb/pull/8727
* https://github.com/pouchdb/pouchdb/pull/8666
* https://github.com/pouchdb/pouchdb/pull/8529

**Comment by fabriciovasc** [comment]
same problem with express server bundle

**Comment by alxndrsn** [comment]
@fabriciovasc the other reports here look specific to Mac; could you share your logs?

**Comment by alxndrsn** [comment]
If anyone can share a minimal reproduction of the issue, it would probably help if someone is looking to fix it.

**Comment by fabriciovasc** [comment]
@alxndrsn I have server bundle generated with esbuild ts node, when try starting the bundled script I have errors in leveldown packages... I found more issues to update level down dependency, but not working

``node server.js``
```shell
      throw new Error("No native build was found for " + target);
      ^

Error: No native build was found for platform=win32 arch=x64 runtime=node abi=108 uv=1 libc=glibc
    at load.path (C:\Users\dev\Desktop\dist\infra\http\express\server.js:117170:13)
    at load (C:\Users\dev\Desktop\dist\infra\http\express\server.js:117137:34)
    at ../../node_modules/leveldown/binding.js (C:\Users\dev\Desktop\dist\infra\http\express\server.js:117265:47)
    at __require (C:\Users\dev\Desktop\dist\infra\http\express\server.js:12:50)
    at ../../node_modules/leveldown/leveldown.js (C:\Users\dev\Desktop\dist\infra\http\express\server.js:117347:19)
    at __require (C:\Users\dev\Desktop\dist\infra\http\express\server.js:12:50)
    at ../../node_modules/level/level.js (C:\Users\dev\Desktop\dist\infra\http\express\server.js:117466:48)
    at __require (C:\Users\dev\Desktop\dist\infra\http\express\server.js:12:50)
    at ../../node_modules/pouchdb/lib/index.js (C:\Users\dev\Desktop\dist\infra\http\express\server.js:120489:33)
    at __require (C:\Users\dev\Desktop\dist\infra\http\express\server.js:12:50)
```

``etsc.config.js``
```
  esbuild: {
    bundle: true,
    target: 'esnext',
    platform: 'node'
  },
```

**Comment by fabriciovasc** [comment]
@alxndrsn I run this bundle as a node process within electron, do you think if I include level down it could solve the problem?

**Comment by alxndrsn** [comment]
@fabriciovasc I suspect updating `leveldown` in this repo would be helpful, but I'm not familiar with this area of `pouchdb`.

**Comment by christrain91** [comment]
> If anyone can share a minimal reproduction of the issue, it would probably help if someone is looking to fix it.

Here's a [codesandbox](https://codesandbox.io/p/sandbox/zen-chandrasekhar-gjgy2r?file=%2Fapp%2Fpage.jsx%3A6%2C31)

**Comment by VictorDiasO** [comment]
Facing the same error... As I saw that its not solved yet Im looking to use an alternative lib for pouchdb in my app :(

**Comment by lewisdorigo** [comment]
I've also been experiencing the same issue.

To work around this, I've used a wrapper around components that use make use of PouchDB to prevent NextJS from trying to pre-render those components on build.

For example:
`/components/ClientOnly.tsx`
```tsx
import React, { FC, PropsWithChildren, useEffect, useState } from 'react';

const ClientOnly:FC<PropsWithChildren> = function ClientOnly({ children }) {
    /** this is probably a super inefficient way of doing this **/
    const [isMounted, setIsMounted] = useState<boolean>(false);
    useEffect(() => { setIsMounted(true); }, []);

    if (!isMounted) { return null; };

    return children;
};

export default ClientOnly;
```

`/app/page.tsx`
```tsx
import React from 'react';

import SomeComponent from '@/components/SomeComponent'
import ClientOnly from '@/components/ClientOnly';
import ComponentWithPouch from '@/components/ComponentWithPouch';

const Page:FC = function Page() {
    return (
        <>
            <SomeComponent />
            <ClientOnly>
                <ComponentWithPouch />
            </ClientOnly>
        </>
    )
};

export default Page;
```

**Comment by juhrlass** [comment]
I solved it by using next/dynamic and skipping ssr

[Next.js - Skipping SSR](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#skipping-ssr)

```js
import React from 'react';
import dynamic from "next/dynamic"

const ComponentWithPouch = dynamic(() => import("@/components/ComponentWithPouch "), {
  ssr: false,
})

export default function Page(): ReactElement {
  return (
    <>
      <ComponentWithPouch />
    <>
  )
}
```

**Comment by MidnightLightning** [comment]
I also hit this issue attempting to add PouchDB to a NextJS application. This error ("No native build was found") happens on build if using the `pouchb` package, and if attempting to drop in `pouchdb-browser` instead (as my intended use-case is all Client Components in NextJS), the buil error changes to "ReferenceError: self is not defined". So neither of the PouchDB exports seem to play well with the NextJS server/client auto-detection.

I've not encountered this error before with any other libraries, so unsure if this is something that PouchDB needs to fix, or NextJS?

**Comment by juniardiakbar** [comment]
You prevent Next.js from bundling `leveldown` on the server, add the following to your `next.config.js`:

```js
module.exports = {
	webpack: (config, { isServer }) => {
		if (isServer) {
			config.externals.push('leveldown')
		}

		return config
	},
}
```

**Comment by nicotroia** [comment]
Also getting `"No native build was found"` when connecting to `pouchdb` from a Next.js application (on Mac silicon M1). And `"ReferenceError: self is not defined"` when using `pouchdb-browser`. @MidnightLightning were you able to solve it? I've tried the ClientOnly and lazy loading solutions mentioned above

My versions
node v18.19.1
yarn (workspaces) 1.22.19
"next": "15.0.0",
"pouchdb": "^9.0.0",
"pouchdb-browser": "^9.0.0",
"react": "^19.0.0",
Mac 15 Sequoia on M1 Max
