### ISSUE TITLE
Intermittent test failure: test.persisted.js Return ok for viewCleanup after modding view, old format

### ISSUE THREAD

**Issue by SourceR85** [pouchdb/pouchdb#8788]
https://github.com/pouchdb/pouchdb/actions/runs/6509460488/job/17681109144?pr=8775#step:4:283
```
  1) test.persisted.js Return ok for viewCleanup after modding view, old format:
     Design document was updated or deleted.
  Error
      at W (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:39916)
      at http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.min.js:7:124168
```

**Comment by alxndrsn** [comment]
Closing as ancient.  Open new issues if there are intermittent failures in the test suite.
