### ISSUE TITLE
indexeddb adapter does not work on webkit

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#8803]
```
$ BROWSER_CONSOLE=1 COUCH_HOST='http://admin:password@localhost:5984' CLIENT=webkit ADAPTERS=indexeddb npm run test
...
Unhandled error in test page: Error [DataCloneError]: Failed to store record in an IDBObjectStore: BlobURLs are not yet supported.
    at put (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.indexeddb.js:4280:35)
    at write (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.indexeddb.js:4280:35)
    at unknown (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.indexeddb.js:4098:14)
    at forEach ([native code]:0:0)
    at processDocs$$1 (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.indexeddb.js:4060:17)
    at readDone (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.indexeddb.js:4041:23)
```

This corresponds to code:

```js
4032   function fetchExistingDocs(txn, docs) {                                       
4033     var fetched = 0;                                                            
4034     var oldDocs = {};                                                           
4035    
4036     function readDone(e) {                                                      
4037       if (e.target.result) {                                                    
4038         oldDocs[e.target.result.id] = e.target.result;                          
4039       }                                                                         
4040       if (++fetched === docs.length) {                                          
4041         processDocs$$1(txn, docs, oldDocs);                                     
4042       }                                                                         
4043     }                                                                           
4044                                                                                 
4045     docs.forEach(function (doc) {                                               
4046       txn.objectStore(DOC_STORE).get(doc.id).onsuccess = readDone;              
4047     });                                                                         
4048   }    
```
which comes from: https://github.com/pouchdb/pouchdb/blob/70bd2afcdc908bc4cb964dde15544ca1eb1f1654/packages/node_modules/pouchdb-adapter-indexeddb/src/bulkDocs.js#L49-L65

ref: safari

**Comment by alxndrsn** [comment]
Maybe relevant: https://github.com/pouchdb/pouchdb/pull/7194

**Comment by alxndrsn** [comment]
This is handled in `adapter-idb` at https://github.com/pouchdb/pouchdb/blob/70bd2afcdc908bc4cb964dde15544ca1eb1f1654/packages/node_modules/pouchdb-adapter-idb/src/index.js#L781-L787
